#!/usr/bin/env python3
"""Exact convention certificate for the classical Euler--Poincare--Suslov body."""
from __future__ import annotations
import argparse,json
from fractions import Fraction as F
from hashlib import sha256
from pathlib import Path
SOURCE_COMMIT="b89544f1f7b1043f4158dfdf9db77787b332f146"; EVALUATOR_SHA256="6f13fc94be84eaf22c518dd0c530e442cd625f3cdcb9d3d34e67cc11c881194c"; SCOPE="NO_BAD_EULER_OR_ROOT_NUMBER"; FIXED_EPOCH=1788048000
ROOT=Path(__file__).resolve().parents[1]; DEFAULT_OUTPUT=ROOT/"results/c255_suslov_evidence.json"
CASES=[
 ("generic_01",F(2),F(3),F(6),F(1),F(1),F(1)),("generic_02",F(1),F(2),F(5),F(1,2),F(1),F(3,2)),("generic_03",F(3),F(4),F(7),F(-1),F(2),F(2)),("generic_04",F(5),F(2),F(6),F(0),F(1),F(2)),("generic_05",F(2),F(5),F(6),F(1),F(0),F(3)),("generic_06",F(4),F(3),F(5),F(-1),F(1,2),F(1)),
 ("generic_07",F(3,2),F(5,2),F(4),F(1,2),F(-1),F(2)),("generic_08",F(7),F(4),F(8),F(2),F(1),F(1,2)),("generic_09",F(2),F(2),F(3),F(1),F(-1),F(5,2)),("generic_10",F(1),F(3),F(4),F(-1,2),F(-1),F(1)),("generic_11",F(6),F(5),F(7),F(2),F(-1),F(3)),("generic_12",F(5,2),F(7,2),F(5),F(1),F(-1,2),F(4)),
 ("principal_01",F(1),F(2),F(3),F(0),F(0),F(1)),("principal_02",F(2),F(3),F(4),F(0),F(0),F(2)),("principal_03",F(3),F(5),F(7),F(0),F(0),F(1,2)),("principal_04",F(4),F(1),F(6),F(0),F(0),F(3))]
def qt(x):
 x=x if isinstance(x,F) else F(x); return str(x.numerator) if x.denominator==1 else f"{x.numerator}/{x.denominator}"
def ph(d):
 b=dict(d); b.pop("payload_sha256",None); return sha256(json.dumps(b,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def row(c):
 cid,I1,I2,I3,a,b,H=c; sch=I3-a*a/I1-b*b/I2; det=I1*I2*sch; q2=a*a/I1+b*b/I2; generic=q2>0
 out={"case_id":cid,"I1":qt(I1),"I2":qt(I2),"I3":qt(I3),"a":qt(a),"b":qt(b),"H":qt(H),"schur_complement":qt(sch),"inertia_determinant":qt(det),"regime":"generic heteroclinic plus clean rotations" if generic else "principal-axis clean-rotation boundary","q_squared":qt(q2),"R_squared":qt(2*H),"kappa_squared":qt(2*H*q2/(I1*I2)),"equilibrium_raw_direction":None,"energy_scale_squared":None,"equilibrium_speed_squared":None,"period_squared_over_pi_squared":None,"unstable_divergence_squared":None,"reduced_orbit_statement":"all positive-energy non-equilibrium reduced states lie on one of two complete heteroclinic arcs" if generic else "every reduced state is an equilibrium","full_reconstruction_statement":"each nonzero reduced equilibrium gives Q(t)=Q0 exp(t hat(omega)), a clean SO(3) periodic rotation","proof_role":"exact rational normalization receipt; radicals remain formula-level"}
 if generic:
  denom=I1*b*b+I2*a*a; c2=2*H/denom; speed2=c2*(a*a+b*b); k2=2*H*q2/(I1*I2)
  out.update({"equilibrium_raw_direction":[qt(b),qt(-a)],"energy_scale_squared":qt(c2),"equilibrium_speed_squared":qt(speed2),"period_squared_over_pi_squared":qt(4/speed2),"unstable_divergence_squared":qt(k2)})
 return out
def build():
 rows=[row(c) for c in CASES]
 d={"schema":"hcs-c255-suslov-nonholonomic-heteroclinic-v1","candidate_id":"HCS-C255","evaluation_date":"2026-08-31","source_commit":SOURCE_COMMIT,"fixed_epoch":FIXED_EPOCH,"scope_literal":SCOPE,"evaluator":{"path":"flow_systems/skills/route-a-evaluator.md","version":"0.2.0","sha256":EVALUATOR_SHA256},
 "headline":"The classical Suslov body has a complete positive-energy reduced heteroclinic atlas, a singular Poisson measure, and clean periodic SO(3) reconstruction on every permanent-rotation line.",
 "frozen_object":{"configuration":"SO(3)","constraint":"body angular velocity omega_3=0","inertia":"[[I1,0,a],[0,I2,b],[a,b,I3]] with I1,I2>0 and I3>a^2/I1+b^2/I2","dynamics":"I omega_dot=(I omega) cross omega+lambda e3","clock":"physical rigid-body time","normalization":"u=sqrt(I1)omega1, v=sqrt(I2)omega2","arithmetic_origin":"none; nonholonomic rigid-body mechanics","determinant_convention":"none","forbidden_data":"target primes/zeros, arithmetic local data, Euler factors, root numbers, automorphy, target divisors, functional equations, Hilbert--Polya operators"},
 "theorem":{"reduction":"With ell=a omega1+b omega2, I1 omega1dot=-ell omega2 and I2 omega2dot=ell omega1; H=(I1 omega1^2+I2 omega2^2)/2 is conserved.","heteroclinics":"For q^2=a^2/I1+b^2/I2>0 and H>0, set u=R cos phi, v=R sin phi, R=sqrt(2H), cos delta=(a/sqrt(I1))/q, sin delta=(b/sqrt(I2))/q, kappa=Rq/sqrt(I1 I2). Then phi'=kappa cos(phi-delta); the two branches satisfy sin(phi-delta)=tanh(kappa(t-t0)), cos(phi-delta)=sigma sech(kappa(t-t0)), sigma=+/-1.","endpoints":"Each energy ellipse has two antipodal permanent rotations ell=0. One is reduced-unstable with exponent +kappa and the other reduced-stable with exponent -kappa; both heteroclinic arcs run from the former to the latter.","clean_reconstruction":"Every nonzero reduced equilibrium has constant body angular velocity and reconstructs as Q(t)=Q0 exp(t hat(omega)), with primitive attitude period 2pi/|omega|. For fixed omega the distinct circles form an SO(3)/SO(2) clean family; energy adds a continuum. These periodic rotations are not omitted or called isolated.","poisson_measure":"The reduced bracket is {omega1,omega2}=-ell/(I1 I2). On each ell half-plane, d omega1 d omega2/|ell| is invariant. It is singular at ell=0, and no positive C1 density extends across a nonzero permanent rotation.","reversor":"(Q,omega)->(Q,-omega) reverses the full flow.","boundaries":"If a=b=0, the reduced vector field vanishes on every energy ellipse and every nonzero state reconstructs as a clean SO(3) rotation; H=0 is fixed. One-zero off-diagonal cases remain generic.","scope":"The exact reduced Poisson bracket is a source-local formal hint, not a target quantization or Hilbert--Polya operator."},
 "regression":{"rows":rows,"row_count":16,"regime_counts":{"generic":12,"principal_axis":4},"boundary_rows":[{"boundary":"H=0","law":"omega=0 and Q is fixed"},{"boundary":"a=b=0","law":"all reduced states fixed; every nonzero full state is a clean periodic rotation"},{"boundary":"a=0,b!=0","law":"generic two-endpoint/two-heteroclinic atlas"},{"boundary":"b=0,a!=0","law":"generic two-endpoint/two-heteroclinic atlas"},{"boundary":"Schur equality","law":"singular inertia; excluded rather than divided through"}],"boundary_row_count":5},
 "exact_identities":["I1 omega1dot=-ell omega2","I2 omega2dot=ell omega1","Hdot=0","ell=a omega1+b omega2","q^2=a^2/I1+b^2/I2","phi'=kappa cos(phi-delta)","sin theta=tanh z and cos theta=sigma sech z","two energy-ellipse heteroclinic components","permanent rotations ell=0","Q(t)=Q0 exp(t hat(omega))","T=2pi/|omega|","Poisson bracket=-ell/(I1 I2)","invariant density=1/|ell| on each half-plane","divergence at a nonzero permanent rotation is nonzero","reversor omega->-omega","Schur complement controls positive definiteness"],
 "route_a":{"tuple":["A0_FAIL","A1_WEAK","A2_FAIL","A3_FAIL","A4_FORMAL_HINT"],"overall":"ROUTE_A_REJECTED","route_b_invocation_allowed":False,"strongest_positive":"The reduced flow and every permanent-rotation reconstruction are analytic for the full positive-energy family.","strongest_failure":"Periodic rotations form clean continua rather than an intrinsic arithmetic primitive ledger; the singular reduced bracket supplies no target determinant or same-clock self-adjoint operator."},
 "scope_flags":{k:False for k in ["uses_target_zero_table","uses_prime_table","claims_arithmetic_local_data","claims_euler_factors","claims_root_numbers","claims_automorphy","claims_target_divisor_or_functional_equation","claims_hilbert_polya_operator","invokes_route_b"]},
 "citations":[{"key":"GarciaNaranjoEtAl2024","claim":"classical Suslov constraint, reduced equations and reduced Poisson bracket","source":"L. C. Garcia-Naranjo, J. C. Marrero, D. Martin de Diego and P. E. Petit Valdes, Almost-Poisson Brackets for Nonholonomic Systems with Gyroscopic Terms and Hamiltonisation, Journal of Nonlinear Science 34 (2024), article 110","url":"https://doi.org/10.1007/s00332-024-10084-w"},{"key":"FedorovMaciejewskiPrzybylska2009","claim":"full-space reconstruction and scattering context for the classical Suslov problem","source":"Y. N. Fedorov, A. J. Maciejewski and M. Przybylska, The Poisson equations in the nonholonomic Suslov problem, Nonlinearity 22 (2009), 2231--2259","url":"https://doi.org/10.1088/0951-7715/22/9/009"},{"key":"FedorovKozlov1995","claim":"authoritative n-dimensional rigid-body and Suslov context","source":"Y. N. Fedorov and V. V. Kozlov, Various Aspects of n-Dimensional Rigid Body Dynamics, American Mathematical Society Translations 168 (1995), 141--171","url":"https://doi.org/10.1090/trans2/168/06"}],
 "nonclaims":["a literature-priority or novelty theorem","closed elementary reconstruction for non-equilibrium attitudes","isolated periodic rotations or a finite primitive census","a zeta/Fredholm or target determinant","arithmetic local data, target functional equation, or Hilbert--Polya operator"]}
 d["payload_sha256"]=ph(d); return d
def main():
 ap=argparse.ArgumentParser(); ap.add_argument("--output",type=Path,default=DEFAULT_OUTPUT); a=ap.parse_args(); a.output.parent.mkdir(parents=True,exist_ok=True); d=build(); a.output.write_text(json.dumps(d,sort_keys=True,indent=2,ensure_ascii=False)+"\n"); print(json.dumps({"status":"C255_PRODUCER_PASS","rows":d["regression"]["row_count"],"boundary_rows":d["regression"]["boundary_row_count"],"payload_sha256":d["payload_sha256"]},sort_keys=True))
if __name__=="__main__": main()
