#!/usr/bin/env python3
"""Independent process-separated Review-B control for P192.

The carrier is generated by recursively splitting cycles of the residual
permutation.  This is neither the author's Hurwitz-orbit traversal nor Review
A's Cartesian product/filter.  Paper and Review-A modules are never imported.
"""

from collections import Counter, defaultdict
from functools import lru_cache
from hashlib import sha256
from itertools import combinations, product
from math import factorial
from pathlib import Path


MAX_N = 8
assertions = 0
transitions = 0
generated_states = 0
target_checks = 0
content_vectors = 0
history_mask_checks = 0


def demand(condition, label="check"):
    global assertions
    assertions += 1
    if not condition:
        raise AssertionError(label)


def compose(left, right):
    """left*right under the convention that right acts first."""
    return tuple(left[right[i]] for i in range(len(left)))


def identity(n):
    return tuple(range(n))


def long_cycle(n):
    return tuple(range(1, n)) + (0,)


def inverse_cycle(n):
    return (n - 1,) + tuple(range(n - 1))


def edge_permutation(edge, n):
    a, b = edge
    out = list(range(n))
    out[a], out[b] = out[b], out[a]
    return tuple(out)


def factor_product(state, edges, n):
    out = identity(n)
    for edge_id in state:
        out = compose(out, edge_permutation(edges[edge_id], n))
    return out


def cycle_labels(permutation):
    labels = [-1] * len(permutation)
    count = 0
    for start in range(len(permutation)):
        if labels[start] >= 0:
            continue
        vertex = start
        while labels[vertex] < 0:
            labels[vertex] = count
            vertex = permutation[vertex]
        count += 1
    return tuple(labels), count


def left_multiply_transposition(permutation, edge):
    """Return edge*permutation by swapping the two output labels."""
    a, b = edge
    return tuple(b if value == a else a if value == b else value
                 for value in permutation)


def cycle_splitting_carrier(n):
    """Generate tau_1...tau_(n-1)=c_n by residual-cycle splitting."""
    edges = tuple(combinations(range(n), 2))
    states = []
    prefix = []

    def visit(residual):
        labels, cycle_count = cycle_labels(residual)
        demand(cycle_count == len(prefix) + 1, "residual-cycle-rank")
        if cycle_count == n:
            demand(residual == identity(n), "split-terminal")
            demand(len(prefix) == n - 1, "split-length")
            states.append(tuple(prefix))
            return
        for edge_id, edge in enumerate(edges):
            if labels[edge[0]] != labels[edge[1]]:
                continue
            following = left_multiply_transposition(residual, edge)
            _, following_count = cycle_labels(following)
            demand(following_count == cycle_count + 1, "not-a-cycle-split")
            prefix.append(edge_id)
            visit(following)
            prefix.pop()

    visit(long_cycle(n))
    demand(len(states) == len(set(states)), "duplicate-split-state")
    return edges, tuple(states)


def conjugate_edge(edge, by):
    a, b = by

    def image(vertex):
        return b if vertex == a else a if vertex == b else vertex

    return tuple(sorted((image(edge[0]), image(edge[1]))))


def first_collision(state, edges):
    for index in range(len(state) - 1):
        if edges[state[index]][0] == edges[state[index + 1]][0]:
            return index
    return None


def hurwitz(state, index, edges, edge_index):
    x = edges[state[index]]
    y = edges[state[index + 1]]
    out = list(state)
    out[index] = state[index + 1]
    out[index + 1] = edge_index[conjugate_edge(x, y)]
    return tuple(out)


def inverse_hurwitz(state, index, edges, edge_index):
    u = edges[state[index]]
    v = edges[state[index + 1]]
    out = list(state)
    out[index] = edge_index[conjugate_edge(v, u)]
    out[index + 1] = state[index]
    return tuple(out)


def update(state, edges, edge_index):
    index = first_collision(state, edges)
    if index is None:
        return state, None
    return hurwitz(state, index, edges, edge_index), index


def lower_word(state, edges):
    return tuple(edges[edge_id][0] + 1 for edge_id in state)


def is_parking(word):
    return all(value <= position for position, value in enumerate(sorted(word), 1))


def canonical_chain(n, edge_index):
    return tuple(edge_index[(i, i + 1)] for i in range(n - 1))


def sharp_witness(n, edge_index):
    if n == 2:
        return (edge_index[(0, 1)],)
    return ((edge_index[(0, n - 1)], edge_index[(0, 1)]) +
            tuple(edge_index[(i, i + 1)] for i in range(1, n - 2)))


def predicted_predecessors(target, edges, edge_index):
    collision = first_collision(target, edges)
    stop = len(target) - 1 if collision is None else collision
    parents = {target} if collision is None else set()
    for index in range(stop):
        a, b = edges[target[index]]
        following = edges[target[index + 1]]
        if b not in following:
            continue
        other = following[0] if following[1] == b else following[1]
        if other > a:
            parents.add(inverse_hurwitz(target, index, edges, edge_index))
    return parents


def depth_history(state, arrows, selected):
    seen = set()
    current = state
    history = []
    while selected[current] is not None:
        demand(current not in seen, "functional-cycle")
        seen.add(current)
        history.append(selected[current] + 1)
        current = arrows[current]
    return tuple(history), current


def weak_compositions(total, parts, prefix=()):
    if parts == 1:
        yield prefix + (total,)
        return
    for first in range(total + 1):
        yield from weak_compositions(total - first, parts - 1,
                                     prefix + (first,))


def content_count_control(length):
    """Count adjacent-unequal parking words by multiset DP, not circles."""
    global content_vectors

    @lru_cache(maxsize=None)
    def no_equal_adjacent(remaining, last):
        if not any(remaining):
            return 1
        total = 0
        for letter, count in enumerate(remaining):
            if count == 0 or letter == last:
                continue
            following = list(remaining)
            following[letter] -= 1
            total += no_equal_adjacent(tuple(following), letter)
        return total

    parking_total = 0
    fixed_total = 0
    admissible_contents = 0
    for counts in weak_compositions(length, length):
        content_vectors += 1
        if any(sum(counts[:r]) < r for r in range(1, length + 1)):
            continue
        admissible_contents += 1
        multiplicity = factorial(length)
        for count in counts:
            multiplicity //= factorial(count)
        parking_total += multiplicity
        fixed_total += no_equal_adjacent(counts, length)
    demand(parking_total == (length + 1) ** (length - 1), "content-parking-count")
    demand(fixed_total == length ** (length - 1), "content-fixed-count")
    return parking_total, fixed_total, admissible_contents, no_equal_adjacent.cache_info().currsize


def orientation_probe(states, edges, edge_index, n):
    reverse_states = {tuple(reversed(state)) for state in states}
    demand(all(factor_product(state, edges, n) == inverse_cycle(n)
               for state in reverse_states), "reverse-product")
    histories = Counter()
    max_tail = 0
    for state in reverse_states:
        current = state
        history = []
        while True:
            following, index = update(current, edges, edge_index)
            demand(following in reverse_states, "inverse-carrier-not-closed")
            if index is None:
                break
            history.append(index + 1)
            current = following
        histories[tuple(history)] += 1
        max_tail = max(max_tail, len(history))
    return max_tail, histories


digest = sha256()
summaries = []
orientation_summary = None

for n in range(2, MAX_N + 1):
    edges, states = cycle_splitting_carrier(n)
    edge_index = {edge: index for index, edge in enumerate(edges)}
    state_set = set(states)
    generated_states += len(states)
    demand(len(states) == n ** (n - 2), "Cayley-cardinality")

    chain = canonical_chain(n, edge_index)
    demand(chain in state_set, "canonical-missing")
    demand(factor_product(chain, edges, n) == long_cycle(n), "canonical-orientation")
    if n >= 3:
        reverse_chain = tuple(reversed(chain))
        demand(factor_product(reverse_chain, edges, n) == inverse_cycle(n),
               "reverse-chain-orientation")

    observed_lower = {lower_word(state, edges) for state in states}
    parking_words = {
        word for word in product(range(1, n), repeat=n - 1) if is_parking(word)
    }
    demand(len(observed_lower) == len(states), "lower-map-not-injective")
    demand(observed_lower == parking_words, "lower-map-not-surjective")

    arrows = {}
    selected = {}
    incoming = defaultdict(set)
    for state in states:
        demand(factor_product(state, edges, n) == long_cycle(n), "wrong-product")
        image, index = update(state, edges, edge_index)
        demand(image in state_set, "Hurwitz-not-closed")
        demand(factor_product(image, edges, n) == long_cycle(n), "product-not-preserved")
        arrows[state] = image
        selected[state] = index
        incoming[image].add(state)
        transitions += 1

    depth_hist = Counter()
    history_hist = Counter()
    terminals = set()
    for state in states:
        history, terminal = depth_history(state, arrows, selected)
        demand(all(history[j] < history[j + 1] for j in range(len(history) - 1)),
               "history-not-strict")
        demand(len(history) <= n - 2, "tail-bound")
        depth_hist[len(history)] += 1
        history_hist[history] += 1
        terminals.add(terminal)
        digest.update((f"{n}|{state}|{arrows[state]}|{history}|"
                       f"{len(incoming[state])}\n").encode("ascii"))

    fixed = {state for state in states if selected[state] is None}
    demand(terminals == fixed, "terminal-fixed-set")
    demand(len(fixed) == (n - 1) ** (n - 2), "fixed-count")

    witness = sharp_witness(n, edge_index)
    demand(witness in state_set, "sharp-witness-not-in-carrier")
    witness_history, witness_terminal = depth_history(witness, arrows, selected)
    demand(witness_history == tuple(range(1, n - 1)), "sharp-history")
    demand(witness_terminal == chain, "sharp-terminal")
    demand(max(depth_hist) == n - 2, "sharp-tail")
    if n == 2:
        demand(states == (chain,), "n2-carrier")
        demand(fixed == {chain}, "n2-fixed")
        demand(depth_hist == Counter({0: 1}), "n2-depth")

    max_fibre = 0
    maximizers = []
    for target in states:
        actual = incoming[target]
        predicted = predicted_predecessors(target, edges, edge_index)
        demand(predicted <= state_set, "predicted-parent-outside-carrier")
        demand(predicted == actual, "every-target-fibre")
        for source in predicted:
            image, source_index = update(source, edges, edge_index)
            demand(image == target, "inverse-does-not-return-target")
            if source != target:
                target_collision = first_collision(target, edges)
                sentinel = len(target) - 1
                demand(source_index < (sentinel if target_collision is None else target_collision),
                       "inverse-scheduler-boundary")
        degree = len(actual)
        if degree > max_fibre:
            max_fibre = degree
            maximizers = [target]
        elif degree == max_fibre:
            maximizers.append(target)
        target_checks += 1
    demand(sum(map(len, incoming.values())) == len(states), "fibre-mass")
    demand(max_fibre == n - 1, "maximum-fibre")
    demand(maximizers == [chain], "unique-fibre-maximizer")
    if n == 2:
        demand(incoming[chain] == {chain}, "n2-self-fibre")

    # Finite evidence only: never consumed by a proved-axis assertion.
    for mask in range(1 << max(0, n - 2)):
        history = tuple(i + 1 for i in range(n - 2) if mask & (1 << i))
        expected = (n - 1) ** (n - 2 - len(history))
        demand(history_hist[history] == expected, "finite-history-evidence")
        history_mask_checks += 1

    if n == 4:
        inverse_max, inverse_histories = orientation_probe(states, edges, edge_index, n)
        demand(history_hist[(1, 2)] == 1, "positive-orientation-full-history")
        demand(inverse_histories[(1, 2)] == 0, "orientation-probe-not-distinct")
        demand(inverse_max == 1, "inverse-orientation-tail")
        orientation_summary = "n4_positive_tail=2 inverse_tail=1 inverse_history_1_2=0"

    histogram = ",".join(f"{d}:{depth_hist[d]}" for d in sorted(depth_hist))
    summaries.append(
        f"n={n} states={len(states)} fixed={len(fixed)} max_tail={max(depth_hist)} "
        f"max_fibre={max_fibre} depth_hist={histogram}"
    )

content_summaries = []
for length in range(1, 10):
    parking_total, fixed_total, contents, dp_states = content_count_control(length)
    content_summaries.append(
        f"N={length} parking={parking_total} adjacent_unequal={fixed_total} "
        f"parking_contents={contents} dp_states={dp_states}"
    )

# Deterministic integrity quarantine for the closest owner and the conjecture.
root = Path(__file__).resolve().parents[4]
main_text = (root / "papers/192-first-collision-hurwitz/main.tex").read_text()
claims_text = (root / "papers/192-first-collision-hurwitz/CLAIMS_EVIDENCE.md").read_text()
source_text = (root / "papers/192-first-collision-hurwitz/SOURCE_VERIFICATION.md").read_text()
bib_text = (root / "papers/192-first-collision-hurwitz/references.bib").read_text()
n9_text = (root / "papers/192-first-collision-hurwitz/code/CANONICAL_N9.txt").read_text()
demand(r"\begin{conjecture}[history-set law]" in main_text, "history-not-conjecture")
demand("receive no theorem status" in main_text, "history-status-not-withheld")
demand("**Conjecture**" in claims_text and "**Conjectural consequence**" in claims_text,
       "claims-ledger-promotes-history")
demand("conjecture_status=n9_verified_not_claimed_all_n" in n9_text,
       "n9-control-promotes-history")
demand("CampionLothRattan2025" in main_text and
       "CampionLothRattan2025" in bib_text and "Campion Loth" in source_text,
       "Campion-Loth-Rattan-subtraction-missing")
demand("zero contribution credit" in main_text and
       "not a novelty claim" in main_text, "owner-boundary-too-strong")
demand("OWNER\\_RED\\_AMBER/HOLD\\_EXTERNAL" in main_text,
       "release-gate-missing")

print("P192 independent residual-cycle-splitting Review B")
print("representation=cycle_splitting_residual_permutations_plus_parking_content_dp")
print("author_or_review_a_code_imported=false")
print("product_convention=rightmost_factor_acts_first")
for line in summaries:
    print(line)
print("orientation_probe=" + orientation_summary)
for line in content_summaries:
    print(line)
print(f"states={generated_states}")
print(f"transitions={transitions}")
print(f"targets={target_checks}")
print(f"parking_content_vectors={content_vectors}")
print(f"history_mask_checks={history_mask_checks}")
print(f"assertions={assertions}")
print(f"record_digest={digest.hexdigest()}")
print("history_law_status=CONJECTURE_ONLY_FINITE_N_LE_8_PLUS_PINNED_N9")
print("Campion_Loth_Rattan_status=CITED_ZERO_CREDIT_DISTINCT_OWNER_NEIGHBOUR")
print("open_critical=0 open_major=0 open_minor=0")
print("external_state=OWNER_RED_AMBER/HOLD_EXTERNAL")
print("status=PASS")
