#!/usr/bin/env python3
"""Deterministic exact evidence producer for HCS-C364."""
from __future__ import annotations

import argparse
import hashlib
import json
import math
import sys
from fractions import Fraction
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "results/c364_gauss_reduction_evidence.json"
EVALUATION = ROOT / "evaluations/route_a/HCS-C364/2026-09-04.yaml"
SOURCE = "323ea43f6970544467f8a89f0ed9be0c7c39f896"
EVALUATOR = "6f13fc94be84eaf22c518dd0c530e442cd625f3cdcb9d3d34e67cc11c881194c"
EVAL_RAW = "5e917ffd7c50323c0a358413c18692672893616e9979d8c99b22f005a3180720"
EVAL_SEMANTIC = "c7e1cf2c241a1ac6fb0c88b5488b21de6cd4dce4d721df678752a5d2dec8eb24"
SCOPE = "NO_BAD_EULER_OR_ROOT_NUMBER"
EPOCH = 1788480000
MAX_DELTA = 1000
FIXED_POWER_LIMIT = 24

FLAGS = {
    "claims_target_arithmetic_local_data": False,
    "claims_target_euler_factors": False,
    "claims_root_number": False,
    "claims_automorphy": False,
    "claims_target_divisor_or_counting_law": False,
    "claims_target_functional_equation": False,
    "claims_target_zero_match": False,
    "claims_hilbert_polya_operator": False,
    "invokes_route_b": False,
}
MODEL = {
    "discriminant_chamber": "Delta>0, Delta nonsquare, Delta congruent to 0 or 1 modulo 4",
    "state": "alpha=(P+sqrt(Delta))/Q with Q=2A>0, P=-B, C=(P^2-Delta)/(2Q), gcd(A,B,C)=1, alpha>1, and -1<alpha_conjugate<0",
    "associated_form": "[A,B,C]=[Q/2,-P,(P^2-Delta)/(2Q)] with B^2-4AC=Delta",
    "digit": "a=floor(alpha)",
    "map": "G(P,Q)=(aQ-P,(Delta-(aQ-P)^2)/Q)",
    "reversor": "R(P,Q)=(P,(Delta-P^2)/Q), corresponding to -1/alpha_conjugate",
    "digit_matrix": "A(a)=[[a,1],[1,0]]",
    "koopman": "U f=f composed with G on l2 of the finite reduced-state set with counting measure",
}
THEOREM = {
    "finite_permutation": "for every admissible Delta the primitive reduced state set is finite and G is a bijection",
    "cycle_stabilizer": "each orbit has a primitive digit word; its positive digit-matrix product fixes the seed, has determinant (-1)^ell, and generates the positive cyclic stabilizer up to the norm-sign convention",
    "multiplier": "if M=[[a,b],[c,d]] is the inverse-branch period matrix and lambda=c*alpha+d>1, then the Gauss-cycle multiplier has magnitude lambda^2",
    "reversal": "R is an involution and R G R=G inverse, hence it pairs cycles with reversed digit words",
    "determinant": "det(I-zU)=product over cycles of (1-z^ell), the reciprocal of the finite source Artin--Mazur zeta",
    "fixed_counts": "Fix(G^n) is the sum of cycle lengths over cycle lengths dividing n",
}
BOUNDARIES = {
    "square": "when Delta is a positive square, rational continued fractions terminate and the reduced irrational permutation theorem does not apply",
    "zero": "Delta=0 gives a repeated rational root and no real quadratic reduced phase space",
    "negative": "Delta<0 is the definite or imaginary-quadratic regime and has no ordered real conjugate chart",
    "invalid_congruence": "integers congruent to 2 or 3 modulo 4 are not discriminants of integral binary quadratic forms",
    "imprimitive": "dropping gcd(A,B,C)=1 duplicates lower primitive discriminants and changes the frozen phase space",
    "norm_sign": "an odd period matrix has determinant minus one; the determinant-plus-one stabilizer is then generated by its square",
    "class_group_bridge": "no narrow-class bijection is required or claimed by the theorem contract",
}
REFERENCES = [
    {"identifier": "10.1090/S0002-9904-1930-05043-0", "role": "primary historical source on reduction of indefinite binary quadratic forms"},
    {"identifier": "10.1007/978-1-4612-4542-1_3", "role": "authoritative treatment of indefinite binary quadratic forms and reduction conventions"},
    {"identifier": "10.1007/978-3-642-61829-1", "role": "authoritative arithmetic context for real quadratic fields and zeta functions; not an owner of this source-local finite zeta claim"},
]
COLLISIONS = {
    "C16": "the S-arithmetic rank-two clock uses continued fractions near walls but does not own fixed-discriminant reduced-state cycles",
    "C193": "Markoff--Vieta dynamics is a terminating descent tree rather than a finite Gauss permutation",
    "C330": "Romik dynamics uses a three-branch Pythagorean map rather than the complete reduced-form phase space at one discriminant",
}
NONCLAIMS = [
    "No priority claim is made for Gauss reduction, Lagrange periodicity, form stabilizers, or real-quadratic arithmetic.",
    "The theorem is source-local and does not identify cycles with rational primes or prime powers.",
    "The finite cycle product is not a target Euler product, target divisor, or completed arithmetic determinant.",
    "The finite Koopman permutation is not a Hilbert--Polya operator or a target-zero realization.",
    "No target arithmetic local data, Euler factor, root number, automorphy, functional equation, target-zero match, or Route-B input is claimed.",
]


def sha(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


def leaves(value) -> int:
    if type(value) is dict:
        return sum(leaves(v) for v in value.values())
    if type(value) is list:
        return sum(leaves(v) for v in value)
    return 1


def alpha_greater_than_integer(delta: int, p: int, q: int, n: int) -> bool:
    """Return (p+sqrt(delta))/q > n using integer arithmetic."""
    rhs = n * q - p
    return rhs < 0 or delta > rhs * rhs


def is_reduced(delta: int, p: int, q: int, primitive: bool = True) -> bool:
    if delta <= 0 or math.isqrt(delta) ** 2 == delta or delta % 4 not in (0, 1):
        return False
    if q <= 0 or q % 2:
        return False
    if (p * p - delta) % (2 * q):
        return False
    aa, bb, cc = q // 2, -p, (p * p - delta) // (2 * q)
    if primitive and math.gcd(math.gcd(abs(aa), abs(bb)), abs(cc)) != 1:
        return False
    # p < sqrt(delta), p+q > sqrt(delta), p+sqrt(delta) > q.
    if p >= 0 and p * p >= delta:
        return False
    if p + q <= 0 or (p + q) * (p + q) <= delta:
        return False
    if not alpha_greater_than_integer(delta, p, q, 1):
        return False
    return True


def reduced_states(delta: int, primitive: bool = True) -> list[tuple[int, int]]:
    s = math.isqrt(delta)
    return [(p, q) for p in range(-s, s + 1) for q in range(2, 2 * s + 1, 2)
            if is_reduced(delta, p, q, primitive)]


def digit(delta: int, state: tuple[int, int]) -> int:
    p, q = state
    a = 1
    while alpha_greater_than_integer(delta, p, q, a + 1):
        a += 1
    return a


def step(delta: int, state: tuple[int, int]) -> tuple[int, int]:
    p, q = state
    a = digit(delta, state)
    pn = a * q - p
    numerator = delta - pn * pn
    if numerator <= 0 or numerator % q:
        raise AssertionError("nonintegral Gauss successor")
    return pn, numerator // q


def reverse_state(delta: int, state: tuple[int, int]) -> tuple[int, int]:
    p, q = state
    numerator = delta - p * p
    if numerator <= 0 or numerator % q:
        raise AssertionError("nonintegral reversal")
    return p, numerator // q


def matmul(left: list[list[int]], right: list[list[int]]) -> list[list[int]]:
    return [[sum(left[i][k] * right[k][j] for k in range(2)) for j in range(2)] for i in range(2)]


def cycles_for(delta: int, states: list[tuple[int, int]]) -> list[list[tuple[int, int]]]:
    unseen = set(states)
    cycles = []
    while unseen:
        seed = min(unseen)
        cycle, current = [], seed
        while current not in cycle:
            if current not in unseen:
                raise AssertionError("cycle merged before closure")
            cycle.append(current)
            unseen.remove(current)
            current = step(delta, current)
        if current != seed:
            raise AssertionError("noncanonical cycle closure")
        cycles.append(cycle)
    return cycles


def period_matrix(delta: int, cycle: list[tuple[int, int]]) -> tuple[list[int], list[list[int]]]:
    digits = [digit(delta, state) for state in cycle]
    matrix = [[1, 0], [0, 1]]
    for a in digits:
        matrix = matmul(matrix, [[a, 1], [1, 0]])
    return digits, matrix


def square_boundary_rows() -> list[dict]:
    rows = []
    for s in range(2, 16):
        delta = s * s
        candidates = []
        for p in range(-s + 1, s):
            for q in range(2, 2 * s + 1, 2):
                if (p * p - delta) % (2 * q):
                    continue
                aa, bb, cc = q // 2, -p, (p * p - delta) // (2 * q)
                if math.gcd(math.gcd(abs(aa), abs(bb)), abs(cc)) != 1:
                    continue
                alpha = Fraction(p + s, q)
                conjugate = Fraction(p - s, q)
                if alpha > 1 and -1 < conjugate < 0:
                    candidates.append((p, q, alpha))
        if not candidates:
            rows.append({"delta": delta, "strict_rational_states": 0, "seed": None,
                         "digits_before_integer": [], "terminal_integer": None})
            continue
        p, q, value = min(candidates)
        digits = []
        while value.denominator != 1:
            a = value.numerator // value.denominator
            digits.append(a)
            value = 1 / (value - a)
        rows.append({"delta": delta, "strict_rational_states": len(candidates),
                     "seed": [p, q], "digits_before_integer": digits,
                     "terminal_integer": value.numerator})
    return rows


def build_data() -> dict:
    all_state_rows, all_cycle_rows, discriminant_rows, fixed_rows = [], [], [], []
    admissible = [d for d in range(5, MAX_DELTA + 1)
                  if d % 4 in (0, 1) and math.isqrt(d) ** 2 != d]
    for delta in admissible:
        states = reduced_states(delta)
        state_set = set(states)
        successors = {state: step(delta, state) for state in states}
        reversals = {state: reverse_state(delta, state) for state in states}
        if set(successors.values()) != state_set or set(reversals.values()) != state_set:
            raise AssertionError("phase-space closure failure")
        cycles = cycles_for(delta, states)
        cycle_of = {state: i for i, cycle in enumerate(cycles) for state in cycle}
        factors: dict[int, int] = {}
        self_reversing = 0
        for cycle_index, cycle in enumerate(cycles):
            digits, matrix = period_matrix(delta, cycle)
            p, q = cycle[0]
            form_a, form_b, form_c = q // 2, -p, (p * p - delta) // (2 * q)
            ma, mb = matrix[0]
            mc, md = matrix[1]
            scale = mc // form_a
            if mc % form_a or [mc, md - ma, -mb] != [scale * form_a, scale * form_b, scale * form_c]:
                raise AssertionError("period matrix does not stabilize seed form")
            det = ma * md - mb * mc
            if det != (-1) ** len(cycle):
                raise AssertionError("period determinant parity")
            if (ma + md) ** 2 - 4 * det != scale * scale * delta:
                raise AssertionError("period discriminant identity")
            reverse_cycle_index = cycle_of[reversals[cycle[0]]]
            if reverse_cycle_index == cycle_index:
                self_reversing += 1
            factors[len(cycle)] = factors.get(len(cycle), 0) + 1
            all_cycle_rows.append({
                "delta": delta, "cycle_index": cycle_index, "seed": [p, q],
                "length": len(cycle), "states": [[x, y] for x, y in cycle],
                "digits": digits, "period_matrix": matrix, "determinant": det,
                "trace": ma + md, "stabilizer_scale": scale,
                "matrix_discriminant": (ma + md) ** 2 - 4 * det,
                "reverse_cycle_index": reverse_cycle_index,
                "orientation_preserving_generator_power": 1 if det == 1 else 2,
            })
        for state_index, state in enumerate(states):
            p, q = state
            aa, bb, cc = q // 2, -p, (p * p - delta) // (2 * q)
            all_state_rows.append({
                "delta": delta, "state_index": state_index, "p": p, "q": q,
                "form": [aa, bb, cc], "digit": digit(delta, state),
                "successor": list(successors[state]), "reversal": list(reversals[state]),
                "cycle_index": cycle_of[state],
            })
        lengths = [len(cycle) for cycle in cycles]
        discriminant_rows.append({
            "delta": delta, "state_count": len(states), "cycle_count": len(cycles),
            "cycle_lengths": lengths,
            "determinant_factors": [{"length": length, "multiplicity": factors[length]} for length in sorted(factors)],
            "self_reversing_cycles": self_reversing,
            "paired_reversal_cycles": len(cycles) - self_reversing,
        })
        for power in range(1, FIXED_POWER_LIMIT + 1):
            fixed_rows.append({"delta": delta, "power": power,
                               "fixed_states": sum(length for length in lengths if power % length == 0)})
    return {
        "schema": "hcs-c364-gauss-reduction-evidence-v1",
        "candidate_id": "HCS-C364", "obstruction_id": "HEN-O348",
        "evaluation_date": "2026-09-04", "source_commit": SOURCE,
        "fixed_epoch": EPOCH, "scope_literal": SCOPE,
        "evaluator": {"authority": "flow_systems/skills/route-a-evaluator.md", "version": "0.2.0", "sha256": EVALUATOR},
        "evaluation_lock": {"relative_path": "evaluations/route_a/HCS-C364/2026-09-04.yaml", "raw_sha256": EVAL_RAW, "semantic_sha256": EVAL_SEMANTIC},
        "model": MODEL, "theorem_contract": THEOREM, "boundary_atlas": BOUNDARIES,
        "references": REFERENCES, "collision_boundary": COLLISIONS, "nonclaims": NONCLAIMS,
        "route_a": {"tuple": ["A0_WEAK_ARITHMETIC_RELATION", "A1_PASS_ANALYTIC", "A2_FAIL", "A3_FAIL", "A4_FORMAL_HINT"], "overall": "ROUTE_A_EXPLORATORY", "route_b": False},
        "scope_flags": FLAGS,
        "discriminant_limit": MAX_DELTA, "fixed_power_limit": FIXED_POWER_LIMIT,
        "admissible_discriminants": admissible,
        "state_rows": all_state_rows, "cycle_rows": all_cycle_rows,
        "discriminant_rows": discriminant_rows, "fixed_point_rows": fixed_rows,
        "boundary_rows": {
            "square": square_boundary_rows(),
            "zero": {"delta": 0, "status": "repeated_rational_root_excluded"},
            "negative": [{"delta": -3, "status": "no_real_ordered_conjugates"}, {"delta": -4, "status": "no_real_ordered_conjugates"}],
            "invalid_congruence": [{"delta": 2, "residue_mod_4": 2}, {"delta": 3, "residue_mod_4": 3}, {"delta": 6, "residue_mod_4": 2}, {"delta": 7, "residue_mod_4": 3}],
            "imprimitive": {"delta": 20, "state": [2, 4], "form": [2, -2, -2], "content": 2, "primitive_discriminant_after_division": 5},
        },
    }


def main() -> None:
    if sys.flags.optimize:
        raise RuntimeError("C364 producer refuses optimized Python")
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args()
    raw_eval = EVALUATION.read_bytes()
    semantic = sha(json.dumps(yaml.safe_load(raw_eval), sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode())
    if sha(raw_eval) != EVAL_RAW or semantic != EVAL_SEMANTIC:
        raise AssertionError("evaluation lock mismatch")
    data = build_data()
    data["enumeration"] = {
        "admissible_discriminants": len(data["admissible_discriminants"]),
        "state_rows": len(data["state_rows"]), "cycle_rows": len(data["cycle_rows"]),
        "discriminant_rows": len(data["discriminant_rows"]),
        "fixed_point_rows": len(data["fixed_point_rows"]),
        "square_boundary_rows": len(data["boundary_rows"]["square"]),
        "leaf_count_without_payload_hash": leaves(data),
    }
    raw = json.dumps(data, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode()
    data["payload_sha256"] = sha(raw)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(data, indent=2, sort_keys=True, ensure_ascii=False) + "\n")
    print("C364_PRODUCER_PASS " + json.dumps({
        "discriminants": len(data["admissible_discriminants"]),
        "states": len(data["state_rows"]), "cycles": len(data["cycle_rows"]),
        "fixed_rows": len(data["fixed_point_rows"]), "leaves": leaves(data),
        "payload": data["payload_sha256"],
    }, sort_keys=True))


if __name__ == "__main__":
    main()
