#!/usr/bin/env python3
"""Producer-independent strict checker for HCS-C364."""
from __future__ import annotations

import argparse
import hashlib
import json
import math
import sys
from fractions import Fraction
from pathlib import Path

import yaml
from yaml.tokens import AliasToken, AnchorToken

ROOT = Path(__file__).resolve().parents[1]
EVIDENCE = ROOT / "results/c364_gauss_reduction_evidence.json"
EVALUATION = ROOT / "evaluations/route_a/HCS-C364/2026-09-04.yaml"
SOURCE = "323ea43f6970544467f8a89f0ed9be0c7c39f896"
EVALUATOR = "6f13fc94be84eaf22c518dd0c530e442cd625f3cdcb9d3d34e67cc11c881194c"
EVAL_RAW = "5e917ffd7c50323c0a358413c18692672893616e9979d8c99b22f005a3180720"
EVAL_SEMANTIC = "c7e1cf2c241a1ac6fb0c88b5488b21de6cd4dce4d721df678752a5d2dec8eb24"
SCOPE = "NO_BAD_EULER_OR_ROOT_NUMBER"
EPOCH = 1788480000
MAX_DELTA = 1000
POWER_LIMIT = 24
CHECKS = 0

FLAGS = {
    "claims_target_arithmetic_local_data": False, "claims_target_euler_factors": False,
    "claims_root_number": False, "claims_automorphy": False,
    "claims_target_divisor_or_counting_law": False, "claims_target_functional_equation": False,
    "claims_target_zero_match": False, "claims_hilbert_polya_operator": False,
    "invokes_route_b": False,
}
MODEL = {
    "discriminant_chamber": "Delta>0, Delta nonsquare, Delta congruent to 0 or 1 modulo 4",
    "state": "alpha=(P+sqrt(Delta))/Q with Q=2A>0, P=-B, C=(P^2-Delta)/(2Q), gcd(A,B,C)=1, alpha>1, and -1<alpha_conjugate<0",
    "associated_form": "[A,B,C]=[Q/2,-P,(P^2-Delta)/(2Q)] with B^2-4AC=Delta",
    "digit": "a=floor(alpha)", "map": "G(P,Q)=(aQ-P,(Delta-(aQ-P)^2)/Q)",
    "reversor": "R(P,Q)=(P,(Delta-P^2)/Q), corresponding to -1/alpha_conjugate",
    "digit_matrix": "A(a)=[[a,1],[1,0]]",
    "koopman": "U f=f composed with G on l2 of the finite reduced-state set with counting measure",
}
THEOREM = {
    "finite_permutation": "for every admissible Delta the primitive reduced state set is finite and G is a bijection",
    "cycle_stabilizer": "each orbit has a primitive digit word; its positive digit-matrix product fixes the seed, has determinant (-1)^ell, and generates the positive cyclic stabilizer up to the norm-sign convention",
    "multiplier": "if M=[[a,b],[c,d]] is the inverse-branch period matrix and lambda=c*alpha+d>1, then the Gauss-cycle multiplier has magnitude lambda^2",
    "reversal": "R is an involution and R G R=G inverse, hence it pairs cycles with reversed digit words",
    "determinant": "det(I-zU)=product over cycles of (1-z^ell), the reciprocal of the finite source Artin--Mazur zeta",
    "fixed_counts": "Fix(G^n) is the sum of cycle lengths over cycle lengths dividing n",
}
BOUNDARIES = {
    "square": "when Delta is a positive square, rational continued fractions terminate and the reduced irrational permutation theorem does not apply",
    "zero": "Delta=0 gives a repeated rational root and no real quadratic reduced phase space",
    "negative": "Delta<0 is the definite or imaginary-quadratic regime and has no ordered real conjugate chart",
    "invalid_congruence": "integers congruent to 2 or 3 modulo 4 are not discriminants of integral binary quadratic forms",
    "imprimitive": "dropping gcd(A,B,C)=1 duplicates lower primitive discriminants and changes the frozen phase space",
    "norm_sign": "an odd period matrix has determinant minus one; the determinant-plus-one stabilizer is then generated by its square",
    "class_group_bridge": "no narrow-class bijection is required or claimed by the theorem contract",
}
REFERENCES = [
    {"identifier": "10.1090/S0002-9904-1930-05043-0", "role": "primary historical source on reduction of indefinite binary quadratic forms"},
    {"identifier": "10.1007/978-1-4612-4542-1_3", "role": "authoritative treatment of indefinite binary quadratic forms and reduction conventions"},
    {"identifier": "10.1007/978-3-642-61829-1", "role": "authoritative arithmetic context for real quadratic fields and zeta functions; not an owner of this source-local finite zeta claim"},
]
COLLISIONS = {
    "C16": "the S-arithmetic rank-two clock uses continued fractions near walls but does not own fixed-discriminant reduced-state cycles",
    "C193": "Markoff--Vieta dynamics is a terminating descent tree rather than a finite Gauss permutation",
    "C330": "Romik dynamics uses a three-branch Pythagorean map rather than the complete reduced-form phase space at one discriminant",
}
NONCLAIMS = [
    "No priority claim is made for Gauss reduction, Lagrange periodicity, form stabilizers, or real-quadratic arithmetic.",
    "The theorem is source-local and does not identify cycles with rational primes or prime powers.",
    "The finite cycle product is not a target Euler product, target divisor, or completed arithmetic determinant.",
    "The finite Koopman permutation is not a Hilbert--Polya operator or a target-zero realization.",
    "No target arithmetic local data, Euler factor, root number, automorphy, functional equation, target-zero match, or Route-B input is claimed.",
]

TOP_KEYS = {"schema", "candidate_id", "obstruction_id", "evaluation_date", "source_commit", "fixed_epoch", "scope_literal", "evaluator", "evaluation_lock", "model", "theorem_contract", "boundary_atlas", "references", "collision_boundary", "nonclaims", "route_a", "scope_flags", "discriminant_limit", "fixed_power_limit", "admissible_discriminants", "state_rows", "cycle_rows", "discriminant_rows", "fixed_point_rows", "boundary_rows", "enumeration", "payload_sha256"}
STATE_KEYS = {"delta", "state_index", "p", "q", "form", "digit", "successor", "reversal", "cycle_index"}
CYCLE_KEYS = {"delta", "cycle_index", "seed", "length", "states", "digits", "period_matrix", "determinant", "trace", "stabilizer_scale", "matrix_discriminant", "reverse_cycle_index", "orientation_preserving_generator_power"}
DISC_KEYS = {"delta", "state_count", "cycle_count", "cycle_lengths", "determinant_factors", "self_reversing_cycles", "paired_reversal_cycles"}
FIXED_KEYS = {"delta", "power", "fixed_states"}


def need(condition: bool, label: str) -> None:
    global CHECKS
    CHECKS += 1
    if not condition:
        raise AssertionError(label)


def typed_equal(actual, expected) -> bool:
    """Recursive equality that never conflates JSON booleans, integers, or floats."""
    if type(actual) is not type(expected):
        return False
    if type(expected) is dict:
        return set(actual) == set(expected) and all(
            typed_equal(actual[key], expected[key]) for key in expected
        )
    if type(expected) is list:
        return len(actual) == len(expected) and all(
            typed_equal(left, right) for left, right in zip(actual, expected)
        )
    return actual == expected


def sha(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


def unique(pairs):
    out = {}
    for key, value in pairs:
        if key in out:
            raise ValueError("duplicate JSON key")
        out[key] = value
    return out


class UniqueLoader(yaml.SafeLoader):
    pass


def unique_mapping(loader, node, deep=False):
    out = {}
    for key_node, value_node in node.value:
        key = loader.construct_object(key_node, deep=deep)
        if type(key) is not str or key in out:
            raise ValueError("non-string or duplicate YAML key")
        out[key] = loader.construct_object(value_node, deep=deep)
    return out


UniqueLoader.add_constructor(yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, unique_mapping)


def parse_yaml(raw: bytes):
    for token in yaml.scan(raw):
        if isinstance(token, (AliasToken, AnchorToken)):
            raise ValueError("YAML alias or anchor")
    value = yaml.load(raw, Loader=UniqueLoader)
    if type(value) is not dict:
        raise ValueError("YAML root")
    return value


def leaves(value) -> int:
    if type(value) is dict:
        return sum(leaves(v) for v in value.values())
    if type(value) is list:
        return sum(leaves(v) for v in value)
    return 1


def root_gt_integer(delta: int, p: int, q: int, n: int) -> bool:
    bound = n * q - p
    return bound < 0 or bound * bound < delta


def independent_states(delta: int) -> list[tuple[int, int]]:
    """Enumerate primitive forms [A,B,C], then translate to (P,Q)."""
    s = math.isqrt(delta)
    found = []
    for form_a in range(1, s + 1):
        for form_b in range(-s, s + 1):
            numerator = form_b * form_b - delta
            if numerator % (4 * form_a):
                continue
            form_c = numerator // (4 * form_a)
            if math.gcd(math.gcd(form_a, abs(form_b)), abs(form_c)) != 1:
                continue
            p, q = -form_b, 2 * form_a
            if p >= 0 and p * p >= delta:
                continue
            if p + q <= 0 or (p + q) * (p + q) <= delta:
                continue
            if not root_gt_integer(delta, p, q, 1):
                continue
            found.append((p, q))
    return sorted(found)


def independent_digit(delta: int, state: tuple[int, int]) -> int:
    p, q = state
    estimate = (p + math.isqrt(delta)) // q
    while root_gt_integer(delta, p, q, estimate + 1):
        estimate += 1
    while estimate > 0 and not root_gt_integer(delta, p, q, estimate):
        estimate -= 1
    return estimate


def independent_step(delta: int, state: tuple[int, int]) -> tuple[int, int]:
    p, q = state
    a = independent_digit(delta, state)
    next_p = a * q - p
    return next_p, (delta - next_p * next_p) // q


def independent_reverse(delta: int, state: tuple[int, int]) -> tuple[int, int]:
    p, q = state
    return p, (delta - p * p) // q


def independent_cycles(delta: int, states: list[tuple[int, int]]) -> list[list[tuple[int, int]]]:
    permutation = {state: independent_step(delta, state) for state in states}
    unused, cycles = set(states), []
    while unused:
        start = min(unused)
        row, current = [], start
        while True:
            row.append(current); unused.remove(current); current = permutation[current]
            if current == start:
                break
        cycles.append(row)
    return cycles


def independent_matrix(digits: list[int]) -> list[list[int]]:
    aa, bb, cc, dd = 1, 0, 0, 1
    for digit_value in digits:
        aa, bb, cc, dd = aa * digit_value + bb, aa, cc * digit_value + dd, cc
    return [[aa, bb], [cc, dd]]


def check_evaluation(raw: bytes) -> None:
    need(sha(raw) == EVAL_RAW, "evaluation raw")
    value = parse_yaml(raw)
    semantic = sha(json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode())
    need(semantic == EVAL_SEMANTIC, "evaluation semantic")
    keys = {"schema", "candidate_id", "title", "evaluation_date", "source_commit", "fixed_epoch", "scope_literal", "evaluator_authority", "evaluator_version", "evaluator_authority_sha256", "obstruction_id", "candidate_definition", "family", "phase_space", "dynamics", "parameters", "parameter_provenance", "arithmetic_origin", "clock", "normalization", "determinant_convention", "orbit_cutoff", "precision", "training_data", "forbidden_data", "artifact_paths", "a0", "a1", "a2", "a3", "a4", "tuple", "overall_verdict", "route_b_invocation_allowed", "route_b_lock_reason", "scope_flags", "theorem_status", "finite_evidence_role", "source_owner_tokens"}
    need(set(value) == keys, "evaluation keys")
    need(typed_equal([value["schema"], value["candidate_id"], value["obstruction_id"], value["evaluation_date"]], ["route-a-evaluation-v0.2.0", "HCS-C364", "HEN-O348", "2026-09-04"]), "evaluation identity")
    need(typed_equal(value["source_commit"], SOURCE) and typed_equal(value["fixed_epoch"], EPOCH) and typed_equal(value["scope_literal"], SCOPE), "evaluation provenance")
    need(value["evaluator_authority"] == "flow_systems/skills/route-a-evaluator.md" and value["evaluator_version"] == "0.2.0" and value["evaluator_authority_sha256"] == EVALUATOR, "evaluation authority")
    need(value["title"] == "Fixed-discriminant Gauss reduction cycles, stabilizers, reversal, and finite dynamical determinant", "evaluation title")
    need(typed_equal(value["artifact_paths"], ["results/c364_gauss_reduction_evidence.json", "THEOREM_PACKAGE.md", "paper/main.pdf"]), "artifact paths")
    verdicts = ["A0_WEAK_ARITHMETIC_RELATION", "A1_PASS_ANALYTIC", "A2_FAIL", "A3_FAIL", "A4_FORMAL_HINT"]
    statuses = ["PROVED", "PROVED", "STOP_SCOPED", "STOP_SCOPED", "PROVED"]
    for index, name in enumerate(("a0", "a1", "a2", "a3", "a4")):
        need(set(value[name]) == {"verdict", "evidence_status", "strongest_evidence", "strongest_failure"}, f"{name} keys")
        need(value[name]["verdict"] == verdicts[index] and value[name]["evidence_status"] == statuses[index], f"{name} lock")
        need(type(value[name]["strongest_evidence"]) is str and len(value[name]["strongest_evidence"]) > 50, f"{name} evidence")
        need(type(value[name]["strongest_failure"]) is str and len(value[name]["strongest_failure"]) > 50, f"{name} failure")
    need(typed_equal(value["tuple"], verdicts) and typed_equal(value["overall_verdict"], "ROUTE_A_EXPLORATORY"), "evaluation tuple")
    need(type(value["route_b_invocation_allowed"]) is bool and value["route_b_invocation_allowed"] is False and typed_equal(value["scope_flags"], FLAGS), "evaluation firewall")
    need(value["theorem_status"] == "PROVABLE_AS_STATED_AFTER_CONVENTION_LOCK", "theorem status")
    need(type(value["finite_evidence_role"]) is str and len(value["finite_evidence_role"]) > 120, "finite role")
    need(typed_equal(value["source_owner_tokens"], ["10.1090/S0002-9904-1930-05043-0", "10.1007/978-1-4612-4542-1_3", "10.1007/978-3-642-61829-1"]), "source tokens")
    for name in ("candidate_definition", "family", "phase_space", "dynamics", "parameters", "parameter_provenance", "arithmetic_origin", "clock", "normalization", "determinant_convention", "orbit_cutoff", "precision", "training_data", "forbidden_data", "route_b_lock_reason"):
        need(type(value[name]) is str and len(value[name]) > 3, f"evaluation text {name}")


def expected_square_rows() -> list[dict]:
    rows = []
    for square_root in range(2, 16):
        delta = square_root * square_root
        candidates = []
        for form_a in range(1, square_root + 1):
            for form_b in range(-square_root + 1, square_root):
                numerator = form_b * form_b - delta
                if numerator % (4 * form_a):
                    continue
                form_c = numerator // (4 * form_a)
                if math.gcd(math.gcd(form_a, abs(form_b)), abs(form_c)) != 1:
                    continue
                p, q = -form_b, 2 * form_a
                value, conjugate = Fraction(p + square_root, q), Fraction(p - square_root, q)
                if value > 1 and -1 < conjugate < 0:
                    candidates.append((p, q, value))
        if not candidates:
            rows.append({"delta": delta, "strict_rational_states": 0, "seed": None, "digits_before_integer": [], "terminal_integer": None})
            continue
        p, q, value = min(candidates)
        digits = []
        while value.denominator != 1:
            floor_value = value.numerator // value.denominator
            digits.append(floor_value); value = 1 / (value - floor_value)
        rows.append({"delta": delta, "strict_rational_states": len(candidates), "seed": [p, q], "digits_before_integer": digits, "terminal_integer": value.numerator})
    return rows


def check(path: Path, evaluation: Path) -> None:
    check_evaluation(evaluation.read_bytes())
    data = json.loads(path.read_text(), object_pairs_hook=unique,
                      parse_constant=lambda token: (_ for _ in ()).throw(ValueError(token)))
    need(set(data) == TOP_KEYS, "top keys")
    need(type(data["payload_sha256"]) is str and len(data["payload_sha256"]) == 64, "payload type")
    payload = dict(data); claimed = payload.pop("payload_sha256")
    need(claimed == sha(json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode()), "payload hash")
    need(typed_equal(data["schema"], "hcs-c364-gauss-reduction-evidence-v1"), "schema")
    need(typed_equal([data["candidate_id"], data["obstruction_id"], data["evaluation_date"]], ["HCS-C364", "HEN-O348", "2026-09-04"]), "identity")
    need(typed_equal(data["source_commit"], SOURCE) and typed_equal(data["fixed_epoch"], EPOCH) and typed_equal(data["scope_literal"], SCOPE), "provenance")
    need(typed_equal(data["evaluator"], {"authority": "flow_systems/skills/route-a-evaluator.md", "version": "0.2.0", "sha256": EVALUATOR}), "evaluator")
    need(typed_equal(data["evaluation_lock"], {"relative_path": "evaluations/route_a/HCS-C364/2026-09-04.yaml", "raw_sha256": EVAL_RAW, "semantic_sha256": EVAL_SEMANTIC}), "evaluation lock")
    need(typed_equal(data["model"], MODEL) and typed_equal(data["theorem_contract"], THEOREM), "model theorem")
    need(typed_equal(data["boundary_atlas"], BOUNDARIES) and typed_equal(data["references"], REFERENCES), "boundary references")
    need(typed_equal(data["collision_boundary"], COLLISIONS) and typed_equal(data["nonclaims"], NONCLAIMS), "collision nonclaims")
    route = {"tuple": ["A0_WEAK_ARITHMETIC_RELATION", "A1_PASS_ANALYTIC", "A2_FAIL", "A3_FAIL", "A4_FORMAL_HINT"], "overall": "ROUTE_A_EXPLORATORY", "route_b": False}
    need(typed_equal(data["route_a"], route) and typed_equal(data["scope_flags"], FLAGS), "route firewall")
    need(typed_equal(data["discriminant_limit"], MAX_DELTA) and typed_equal(data["fixed_power_limit"], POWER_LIMIT), "limits")

    admissible = [d for d in range(5, MAX_DELTA + 1) if d % 4 in (0, 1) and math.isqrt(d) ** 2 != d]
    need(typed_equal(data["admissible_discriminants"], admissible), "discriminant enumeration")
    state_cursor = cycle_cursor = fixed_cursor = 0
    for disc_index, delta in enumerate(admissible):
        states = independent_states(delta)
        state_set = set(states)
        permutation = {state: independent_step(delta, state) for state in states}
        reversals = {state: independent_reverse(delta, state) for state in states}
        need(set(permutation.values()) == state_set, "permutation closure")
        need(set(reversals.values()) == state_set, "reversal closure")
        inverse = {target: source for source, target in permutation.items()}
        need(len(inverse) == len(states), "permutation injective")
        for state in states:
            need(independent_reverse(delta, independent_reverse(delta, state)) == state, "reversal involution")
            need(independent_reverse(delta, independent_step(delta, independent_reverse(delta, state))) == inverse[state], "reversor identity")
        cycles = independent_cycles(delta, states)
        cycle_of = {state: index for index, cycle in enumerate(cycles) for state in cycle}
        factors = {}
        self_reversing = 0
        for local_index, cycle in enumerate(cycles):
            row = data["cycle_rows"][cycle_cursor]; cycle_cursor += 1
            need(set(row) == CYCLE_KEYS, "cycle keys")
            need(typed_equal(row["delta"], delta) and typed_equal(row["cycle_index"], local_index), "cycle coordinate")
            digits = [independent_digit(delta, state) for state in cycle]
            matrix = independent_matrix(digits)
            ma, mb = matrix[0]; mc, md = matrix[1]
            p, q = cycle[0]; form_a, form_b, form_c = q // 2, -p, (p * p - delta) // (2 * q)
            need(mc % form_a == 0, "stabilizer divisibility")
            scale = mc // form_a
            determinant = ma * md - mb * mc
            reverse_index = cycle_of[reversals[cycle[0]]]
            expected = {
                "delta": delta, "cycle_index": local_index, "seed": [p, q], "length": len(cycle),
                "states": [list(state) for state in cycle], "digits": digits, "period_matrix": matrix,
                "determinant": determinant, "trace": ma + md, "stabilizer_scale": scale,
                "matrix_discriminant": (ma + md) ** 2 - 4 * determinant,
                "reverse_cycle_index": reverse_index,
                "orientation_preserving_generator_power": 1 if determinant == 1 else 2,
            }
            for key in CYCLE_KEYS:
                need(typed_equal(row[key], expected[key]), f"cycle field {key}")
            need([mc, md - ma, -mb] == [scale * form_a, scale * form_b, scale * form_c], "fixed polynomial")
            need(row["matrix_discriminant"] == scale * scale * delta, "matrix discriminant")
            need(determinant == (-1) ** len(cycle), "determinant parity")
            factors[len(cycle)] = factors.get(len(cycle), 0) + 1
            self_reversing += int(reverse_index == local_index)
        for local_index, state in enumerate(states):
            row = data["state_rows"][state_cursor]; state_cursor += 1
            need(set(row) == STATE_KEYS, "state keys")
            p, q = state; form = [q // 2, -p, (p * p - delta) // (2 * q)]
            expected = {"delta": delta, "state_index": local_index, "p": p, "q": q, "form": form,
                        "digit": independent_digit(delta, state), "successor": list(permutation[state]),
                        "reversal": list(reversals[state]), "cycle_index": cycle_of[state]}
            for key in STATE_KEYS:
                need(typed_equal(row[key], expected[key]), f"state field {key}")
            need(form[1] * form[1] - 4 * form[0] * form[2] == delta, "form discriminant")
            need(math.gcd(math.gcd(abs(form[0]), abs(form[1])), abs(form[2])) == 1, "form primitive")
        lengths = [len(cycle) for cycle in cycles]
        drow = data["discriminant_rows"][disc_index]
        need(set(drow) == DISC_KEYS, "discriminant keys")
        expected_drow = {"delta": delta, "state_count": len(states), "cycle_count": len(cycles),
                         "cycle_lengths": lengths,
                         "determinant_factors": [{"length": length, "multiplicity": factors[length]} for length in sorted(factors)],
                         "self_reversing_cycles": self_reversing,
                         "paired_reversal_cycles": len(cycles) - self_reversing}
        for key in DISC_KEYS:
            need(typed_equal(drow[key], expected_drow[key]), f"discriminant field {key}")
        for power in range(1, POWER_LIMIT + 1):
            frow = data["fixed_point_rows"][fixed_cursor]; fixed_cursor += 1
            need(set(frow) == FIXED_KEYS, "fixed keys")
            need(typed_equal(frow, {"delta": delta, "power": power, "fixed_states": sum(length for length in lengths if power % length == 0)}), "fixed formula")
    need(state_cursor == len(data["state_rows"]), "state row closure")
    need(cycle_cursor == len(data["cycle_rows"]), "cycle row closure")
    need(fixed_cursor == len(data["fixed_point_rows"]), "fixed row closure")

    boundaries = data["boundary_rows"]
    need(set(boundaries) == {"square", "zero", "negative", "invalid_congruence", "imprimitive"}, "boundary keys")
    need(typed_equal(boundaries["square"], expected_square_rows()), "square boundaries")
    need(typed_equal(boundaries["zero"], {"delta": 0, "status": "repeated_rational_root_excluded"}), "zero boundary")
    need(typed_equal(boundaries["negative"], [{"delta": -3, "status": "no_real_ordered_conjugates"}, {"delta": -4, "status": "no_real_ordered_conjugates"}]), "negative boundary")
    need(typed_equal(boundaries["invalid_congruence"], [{"delta": 2, "residue_mod_4": 2}, {"delta": 3, "residue_mod_4": 3}, {"delta": 6, "residue_mod_4": 2}, {"delta": 7, "residue_mod_4": 3}]), "congruence boundary")
    need(typed_equal(boundaries["imprimitive"], {"delta": 20, "state": [2, 4], "form": [2, -2, -2], "content": 2, "primitive_discriminant_after_division": 5}), "imprimitive boundary")
    enum = data["enumeration"]
    need(set(enum) == {"admissible_discriminants", "state_rows", "cycle_rows", "discriminant_rows", "fixed_point_rows", "square_boundary_rows", "leaf_count_without_payload_hash"}, "enumeration keys")
    base = dict(payload); base.pop("enumeration")
    expected_enum = {"admissible_discriminants": len(admissible), "state_rows": state_cursor,
                     "cycle_rows": cycle_cursor, "discriminant_rows": len(admissible),
                     "fixed_point_rows": fixed_cursor, "square_boundary_rows": 14,
                     "leaf_count_without_payload_hash": leaves(base)}
    need(typed_equal(enum, expected_enum), "enumeration")
    print(f"C364 independent Gauss-reduction checker: PASS ({CHECKS} checks)")


def main() -> None:
    if sys.flags.optimize:
        raise RuntimeError("C364 checker refuses optimized Python")
    parser = argparse.ArgumentParser()
    parser.add_argument("--evidence", type=Path, default=EVIDENCE)
    parser.add_argument("--evaluation", type=Path, default=EVALUATION)
    args = parser.parse_args()
    check(args.evidence, args.evaluation)


if __name__ == "__main__":
    main()
