#!/usr/bin/env python3
"""Process-separated exact control for P192 hostile Review A.

The factorization carrier is generated by direct Cartesian enumeration and a
literal product filter.  No Hurwitz-orbit generator, tree code, paper-local
module, or author verifier is imported.  Parking words and Pollak circles are
enumerated separately from the factorization graph.
"""

from __future__ import annotations

from collections import Counter, defaultdict
from hashlib import sha256
from itertools import product
from pathlib import Path


ASSERTIONS = 0
SEQUENCES_SCANNED = 0
FACTORIZATIONS = 0
TRANSITIONS = 0
TARGETS = 0
PARKING_WORDS = 0
CIRCULAR_WORDS = 0


def check(condition: bool, message: object) -> None:
    global ASSERTIONS
    ASSERTIONS += 1
    if not condition:
        raise AssertionError(message)


Permutation = tuple[int, ...]
Edge = tuple[int, int]
Factorization = tuple[Edge, ...]


def compose(left: Permutation, right: Permutation) -> Permutation:
    """Return left*right, with right acting first."""
    return tuple(left[right[i]] for i in range(len(left)))


def identity(n: int) -> Permutation:
    return tuple(range(n))


def edge_permutation(edge: Edge, n: int) -> Permutation:
    a, b = edge
    values = list(range(n))
    values[a], values[b] = values[b], values[a]
    return tuple(values)


def long_cycle(n: int) -> Permutation:
    return tuple((i + 1) % n for i in range(n))


def factorization_product(factors: Factorization, n: int) -> Permutation:
    result = identity(n)
    for edge in factors:
        result = compose(result, edge_permutation(edge, n))
    return result


def all_edges(n: int) -> tuple[Edge, ...]:
    return tuple((a, b) for a in range(n) for b in range(a + 1, n))


def conjugate_edge(edge: Edge, by: Edge) -> Edge:
    def act(vertex: int) -> int:
        if vertex == by[0]:
            return by[1]
        if vertex == by[1]:
            return by[0]
        return vertex

    return tuple(sorted((act(edge[0]), act(edge[1]))))  # type: ignore[return-value]


def hurwitz(factors: Factorization, index: int) -> Factorization:
    """H_i(x,y)=(y,yxy), using a zero-based index."""
    left, right = factors[index], factors[index + 1]
    out = list(factors)
    out[index] = right
    out[index + 1] = conjugate_edge(left, right)
    return tuple(out)


def inverse_hurwitz(factors: Factorization, index: int) -> Factorization:
    """H_i^{-1}(u,v)=(uvu,u), using a zero-based index."""
    left, right = factors[index], factors[index + 1]
    out = list(factors)
    out[index] = conjugate_edge(right, left)
    out[index + 1] = left
    return tuple(out)


def first_collision(factors: Factorization) -> int | None:
    for index in range(len(factors) - 1):
        if factors[index][0] == factors[index + 1][0]:
            return index
    return None


def update(factors: Factorization) -> tuple[Factorization, int | None]:
    index = first_collision(factors)
    if index is None:
        return factors, None
    return hurwitz(factors, index), index


def lower_word(factors: Factorization) -> tuple[int, ...]:
    return tuple(edge[0] + 1 for edge in factors)


def is_parking(word: tuple[int, ...]) -> bool:
    return all(value <= index for index, value in enumerate(sorted(word), 1))


def direct_carrier(n: int) -> tuple[Factorization, ...]:
    global SEQUENCES_SCANNED
    edges = all_edges(n)
    carrier = []
    for factors in product(edges, repeat=n - 1):
        SEQUENCES_SCANNED += 1
        if factorization_product(factors, n) == long_cycle(n):
            carrier.append(factors)
    return tuple(carrier)


def predicted_predecessors(target: Factorization) -> set[Factorization]:
    # Paper indices are one-based.  Its sentinel is n-1, while the valid
    # Hurwitz indices are 1,...,n-2; in zero-based coordinates the exclusive
    # upper bound for a fixed target is therefore len(target)-1.
    sentinel = len(target) - 1
    collision = first_collision(target)
    first = sentinel if collision is None else collision
    parents: set[Factorization] = set()
    if collision is None:
        parents.add(target)
    for index in range(first):
        a, b = target[index]
        following = target[index + 1]
        if b not in following:
            continue
        c = following[0] if following[1] == b else following[1]
        if c > a:
            parents.add(inverse_hurwitz(target, index))
    return parents


def depth_and_history(state: Factorization) -> tuple[int, tuple[int, ...], Factorization]:
    history = []
    current = state
    for _ in range(len(state)):
        following, index = update(current)
        if index is None:
            return len(history), tuple(history), current
        history.append(index + 1)
        current = following
    raise AssertionError(("nontermination", state, history))


def canonical_chain(n: int) -> Factorization:
    return tuple((i, i + 1) for i in range(n - 1))


def sharp_witness(n: int) -> Factorization:
    if n == 2:
        return ((0, 1),)
    return ((0, n - 1), (0, 1)) + tuple((i, i + 1) for i in range(1, n - 2))


def verify_factorization_box(n: int, digest) -> tuple[int, int, int, int, str]:
    global FACTORIZATIONS, TRANSITIONS, TARGETS
    carrier = direct_carrier(n)
    carrier_set = set(carrier)
    expected_size = n ** (n - 2)
    check(len(carrier) == expected_size, ("carrier-size", n, len(carrier), expected_size))
    check(len(carrier_set) == len(carrier), ("carrier-duplicates", n))

    chain = canonical_chain(n)
    check(chain in carrier_set, ("canonical-not-in-carrier", n))
    check(factorization_product(chain, n) == long_cycle(n), ("canonical-orientation", n))
    if n >= 3:
        reversed_product = factorization_product(tuple(reversed(chain)), n)
        check(reversed_product != long_cycle(n), ("orientation-not-sensitive", n))
        check(compose(long_cycle(n), reversed_product) == identity(n),
              ("reverse-not-inverse-cycle", n))

    parking_words = {
        word for word in product(range(1, n), repeat=n - 1) if is_parking(word)
    }
    observed_lower = {lower_word(state) for state in carrier}
    check(len(observed_lower) == len(carrier), ("lower-map-not-injective", n))
    check(observed_lower == parking_words,
          ("lower-map-not-bijection", n, len(observed_lower), len(parking_words)))

    transition: dict[Factorization, Factorization] = {}
    histories: dict[Factorization, tuple[int, ...]] = {}
    depth_hist = Counter()
    incoming: dict[Factorization, set[Factorization]] = defaultdict(set)
    for state in carrier:
        image, selected = update(state)
        check(image in carrier_set, ("not-closed", n, state, image))
        check(factorization_product(image, n) == long_cycle(n),
              ("product-not-preserved", n, state, image))
        expected_index = first_collision(state)
        check(selected == expected_index, ("not-least-index", n, state, selected, expected_index))
        transition[state] = image
        incoming[image].add(state)
        depth, history, terminal = depth_and_history(state)
        check(all(history[i] < history[i + 1] for i in range(len(history) - 1)),
              ("history-not-strict", n, state, history))
        check(depth == len(history) <= n - 2, ("tail-bound", n, state, depth, history))
        check(first_collision(terminal) is None, ("terminal-not-fixed", n, terminal))
        histories[state] = history
        depth_hist[depth] += 1
        digest.update(f"F|{n}|{state}|{image}|{history}\n".encode())
        TRANSITIONS += 1

    witness = sharp_witness(n)
    check(witness in carrier_set, ("witness-not-carrier", n, witness))
    witness_depth, witness_history, witness_terminal = depth_and_history(witness)
    check(witness_depth == n - 2, ("witness-depth", n, witness_depth))
    check(witness_history == tuple(range(1, n - 1)), ("witness-history", n, witness_history))
    check(witness_terminal == chain, ("witness-terminal", n, witness_terminal, chain))

    fixed = {state for state in carrier if transition[state] == state}
    fixed_by_rule = {state for state in carrier if first_collision(state) is None}
    check(fixed == fixed_by_rule, ("fixed-rule", n))
    check(len(fixed) == (n - 1) ** (n - 2),
          ("fixed-count", n, len(fixed), (n - 1) ** (n - 2)))

    max_fibre = 0
    maximizers = []
    for target in carrier:
        actual = incoming.get(target, set())
        predicted = predicted_predecessors(target)
        check(predicted == actual,
              ("inverse-atlas", n, target, sorted(actual), sorted(predicted)))
        for source in predicted:
            image, selected = update(source)
            check(image == target, ("inverse-image", n, source, target, image))
            if source != target:
                check(selected is not None and selected < (
                    first_collision(target) if first_collision(target) is not None else len(target) - 1
                ), ("inverse-scheduler", n, source, target, selected))
        degree = len(actual)
        if degree > max_fibre:
            max_fibre = degree
            maximizers = [target]
        elif degree == max_fibre:
            maximizers.append(target)
        TARGETS += 1

    check(sum(len(parents) for parents in incoming.values()) == len(carrier),
          ("edge-mass", n))
    check(max_fibre == n - 1, ("max-fibre", n, max_fibre))
    check(maximizers == [chain], ("maximizer", n, maximizers, chain))

    FACTORIZATIONS += len(carrier)
    histogram = ",".join(f"{d}:{depth_hist[d]}" for d in sorted(depth_hist))
    return len(carrier), len(fixed), max(depth_hist), max_fibre, histogram


def circular_park(preferences: tuple[int, ...]) -> int:
    size = len(preferences) + 1
    occupied = [False] * size
    for preference in preferences:
        spot = preference
        while occupied[spot]:
            spot = (spot + 1) % size
        occupied[spot] = True
    return occupied.index(False)


def translate(word: tuple[int, ...], shift: int, modulus: int) -> tuple[int, ...]:
    return tuple((value + shift) % modulus for value in word)


def verify_pollak(max_n: int, digest) -> list[str]:
    global PARKING_WORDS, CIRCULAR_WORDS
    rows = []
    for n in range(2, max_n + 1):
        length = n - 1
        ordinary = [word for word in product(range(1, length + 1), repeat=length)
                    if is_parking(word)]
        adjacent_unequal = [word for word in ordinary
                            if all(word[i] != word[i + 1] for i in range(length - 1))]
        expected = length ** (length - 1)
        check(len(adjacent_unequal) == expected,
              ("parking-fixed-count", n, len(adjacent_unequal), expected))
        PARKING_WORDS += len(ordinary)

        if length <= 6:
            alphabet = length + 1
            circular = [word for word in product(range(alphabet), repeat=length)
                        if all(word[i] != word[i + 1] for i in range(length - 1))]
            check(len(circular) == alphabet * expected,
                  ("circular-count", n, len(circular), alphabet * expected))
            representatives = set()
            for word in circular:
                empty = circular_park(word)
                normalized = translate(word, length - empty, alphabet)
                check(circular_park(normalized) == length,
                      ("empty-normalization", n, word, empty, normalized))
                check(length not in normalized, ("empty-preferred", n, normalized))
                converted = tuple(value + 1 for value in normalized)
                check(is_parking(converted), ("normalized-not-parking", n, converted))
                check(all(converted[i] != converted[i + 1] for i in range(length - 1)),
                      ("normalization-lost-inequality", n, converted))
                orbit = {translate(word, shift, alphabet) for shift in range(alphabet)}
                check(len(orbit) == alphabet, ("translation-not-free", n, word))
                representatives.add(normalized)
                digest.update(f"P|{n}|{word}|{empty}|{normalized}\n".encode())
            check(len(representatives) == expected,
                  ("pollak-orbits", n, len(representatives), expected))
            CIRCULAR_WORDS += len(circular)

        rows.append(f"n{n}_parking{len(ordinary)}_fixed{len(adjacent_unequal)}")
    return rows


def verify_conjecture_quarantine() -> None:
    root = Path(__file__).resolve().parents[4]
    manuscript = (root / "papers/192-first-collision-hurwitz/main.tex").read_text()
    evidence = (root / "papers/192-first-collision-hurwitz/CLAIMS_EVIDENCE.md").read_text()
    check(r"\begin{conjecture}[history-set law]" in manuscript,
          "history law is not in a conjecture environment")
    check("receive no theorem status" in manuscript,
          "manuscript does not withhold theorem status")
    check("no all-$n$ bijection" in manuscript.lower(),
          "manuscript omits missing all-n bridge")
    check("**Conjecture**" in evidence and "**Conjectural consequence**" in evidence,
          "claim ledger promotes history law")


def main() -> None:
    digest = sha256()
    rows = []
    for n in range(2, 7):
        size, fixed, max_tail, max_fibre, histogram = verify_factorization_box(n, digest)
        rows.append(
            f"n={n} states={size} fixed={fixed} max_tail={max_tail} "
            f"max_fibre={max_fibre} depth_hist={histogram}"
        )
    pollak_rows = verify_pollak(8, digest)
    verify_conjecture_quarantine()

    print("P192_HOSTILE_REVIEW_A_EXACT_CONTROL")
    print("REPRESENTATION=direct_cartesian_product_filter_plus_independent_parking_circles")
    print("AUTHOR_CODE_IMPORTED=false")
    print("PRODUCT_CONVENTION=left_factor_after_right_factor_rightmost_acts_first")
    for row in rows:
        print(row)
    print("POLLAK=" + ";".join(pollak_rows))
    print(f"SEQUENCES_SCANNED={SEQUENCES_SCANNED}")
    print(f"FACTORIZATIONS={FACTORIZATIONS}")
    print(f"TRANSITIONS={TRANSITIONS}")
    print(f"TARGETS={TARGETS}")
    print(f"PARKING_WORDS={PARKING_WORDS}")
    print(f"CIRCULAR_WORDS={CIRCULAR_WORDS}")
    print(f"ASSERTIONS={ASSERTIONS}")
    print(f"CONTROL_DIGEST={digest.hexdigest()}")
    print("HISTORY_LAW_STATUS=CONJECTURE_ONLY_NOT_USED_IN_PROVED_AXES")
    print("CRITICAL_FINDINGS=0")
    print("MAJOR_FINDINGS=0")
    print("MINOR_FINDINGS=0")
    print("VERDICT=PROVABLE_AS_STATED_AFTER_ACCEPTED_REPAIR")
    print("OWNER_GATE=OWNER_RED_AMBER")
    print("EXTERNAL_STATE=HOLD_EXTERNAL")
    print("FINITE_CONTROL_IS_NOT_PROOF_OR_NOVELTY=true")
    print("RESULT=PASS")


if __name__ == "__main__":
    main()
