#!/usr/bin/env python3
"""Producer-independent recursive, block and unitary audit for C223."""
from __future__ import annotations

import argparse
from fractions import Fraction as F
from hashlib import sha256
import json
from pathlib import Path
import mpmath as mp
import sympy as sp

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EVIDENCE = ROOT / "results/c223_jaynes_cummings_evidence.json"
SOURCE_COMMIT = "86c7bb8a39cdd1b8e941e45833b068170ca06287"
EVALUATOR = {"path": "flow_systems/skills/route-a-evaluator.md", "version": "0.2.0", "sha256": "6f13fc94be84eaf22c518dd0c530e442cd625f3cdcb9d3d34e67cc11c881194c"}
SCOPE = "NO_BAD_EULER_OR_ROOT_NUMBER"
HEADLINE = "Jaynes--Cummings dynamics decomposes exactly into conserved-excitation blocks with closed dressed spectrum and propagator"
PARAMETERS = [
    ("resonant", F(1), F(1), F(1, 2)),
    ("negative_detuning", F(2), F(1), F(1, 3)),
    ("positive_detuning_negative_coupling", F(1), F(3), F(-1, 4)),
    ("uncoupled_degenerate", F(3, 2), F(3, 2), F(0)),
]
N_VALUES = list(range(1, 9))
T_VALUES = [F(1, 3), F(1)]


def payload_hash(data: dict) -> str:
    body = dict(data)
    body.pop("payload_sha256", None)
    return sha256(json.dumps(body, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode()).hexdigest()


def q(value: F) -> mp.mpf:
    return mp.mpf(value.numerator) / value.denominator


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--evidence", type=Path, default=DEFAULT_EVIDENCE)
    data = json.loads(parser.parse_args().evidence.read_text())
    mp.mp.dps = 100
    assertions = 0

    def check(condition, message: str) -> None:
        nonlocal assertions
        assertions += 1
        if not condition:
            raise AssertionError(message)

    def keys(obj, expected, where: str) -> None:
        check(isinstance(obj, dict), where + " mapping")
        check(set(obj) == set(expected), where + " keys")

    keys(data, ["schema", "candidate_id", "evaluation_date", "source_commit", "scope_literal", "evaluator", "headline", "frozen_object", "theorem", "regression", "summary", "route_a", "scope_flags", "citations", "nonclaims", "payload_sha256"], "top")
    keys(data["evaluator"], ["path", "version", "sha256"], "evaluator")
    frozen_keys = ["hilbert_space", "hamiltonian", "parameters", "clock", "excitation_convention", "normalization", "determinant_convention", "arithmetic_origin", "allowed_data", "forbidden_data"]
    theorem_keys = ["conservation", "vacuum", "block", "dressed_spectrum", "propagator", "transition", "invariants", "population_revival", "state_revival", "boundaries", "operator_boundary"]
    keys(data["frozen_object"], frozen_keys, "frozen")
    keys(data["theorem"], theorem_keys, "theorem")
    keys(data["regression"], ["parameter_rows", "n_values", "t_values", "block_rows", "dynamics_rows", "vacuum_rows", "boundary_rows"], "regression")
    keys(data["summary"], ["parameter_count", "block_row_count", "dynamics_row_count", "vacuum_row_count", "boundary_row_count", "serialized_decimal_digits"], "summary")
    keys(data["route_a"], ["tuple", "overall", "route_b_invocation_allowed", "strongest_positive", "strongest_failure"], "route")
    flags = ["uses_target_zero_table", "uses_prime_table", "claims_arithmetic_local_data", "claims_euler_factors", "claims_root_numbers", "claims_automorphy", "claims_target_divisor_or_functional_equation", "claims_hilbert_polya_operator", "invokes_route_b"]
    keys(data["scope_flags"], flags, "scope_flags")
    check(data["schema"] == "hcs-c223-jaynes-cummings-v1" and data["candidate_id"] == "HCS-C223", "identity")
    check(data["evaluation_date"] == "2026-08-28" and data["source_commit"] == SOURCE_COMMIT, "date/source")
    check(data["scope_literal"] == SCOPE and data["evaluator"] == EVALUATOR and data["headline"] == HEADLINE, "locks")
    expected_frozen = {
        "hilbert_space": "two-level atom tensor bosonic Fock space",
        "hamiltonian": "H=omega_c*a_dagger*a+(omega_q/2)*sigma_z+g*(a_dagger*sigma_-+a*sigma_+), with hbar=1",
        "parameters": "real omega_c, omega_q and g; physical t; block index n>=1",
        "clock": "physical unitary time generated by H",
        "excitation_convention": "N=a_dagger*a+sigma_+*sigma_-; block n uses ordered basis {|e,n-1>,|g,n>}",
        "normalization": "atomic sigma_z eigenvalues are +1 on |e> and -1 on |g>",
        "determinant_convention": "ordinary 2x2 block determinants only; no infinite-dimensional Fredholm determinant",
        "arithmetic_origin": "none; excitation number is a Fock label, not a primitive arithmetic owner",
        "allowed_data": "exact rational frequencies/couplings/times and source-local finite excitation blocks",
        "forbidden_data": "prime or zero tables, target labels, Euler factors, root numbers, automorphy and Route-B input",
    }
    expected_theorem = {
        "conservation": "[H,N]=0, so the vacuum and every fixed-excitation subspace are invariant",
        "vacuum": "|g,0> is an eigenstate with energy -omega_q/2",
        "block": "For n>=1, H_n=(n-1/2)*omega_c*I+(Delta/2)*sigma_z+g*sqrt(n)*sigma_x, Delta=omega_q-omega_c",
        "dressed_spectrum": "E_{n,+/-}=(n-1/2)*omega_c +/- Omega_n/2, Omega_n=sqrt(Delta^2+4*g^2*n)",
        "propagator": "U_n(t)=exp(-i*(n-1/2)*omega_c*t)[cos(Omega_n*t/2)*I-i*sin(Omega_n*t/2)*(Delta*sigma_z+2*g*sqrt(n)*sigma_x)/Omega_n], with the continuous Omega_n=0 limit",
        "transition": "P_{|e,n-1> to |g,n>}(t)=(4*g^2*n/Omega_n^2)*sin^2(Omega_n*t/2), interpreted as zero when g=Delta=0",
        "invariants": "Each block propagator is unitary, tr(U_n)=2*exp(-i*c_n*t)*cos(Omega_n*t/2), det(U_n)=exp(-2i*c_n*t), c_n=(n-1/2)*omega_c",
        "population_revival": "For a finite active set of coupled bare blocks, universal bare-population revival at T>0 holds iff Omega_n*T is in 2*pi*Z for every active n; equivalently their positive Omega_n are rationally commensurate",
        "state_revival": "A common state-vector revival additionally requires alignment of the block center phases, the parity signs from Omega_n*T/(2*pi), and any occupied vacuum phase",
        "boundaries": "g=0 decouples the bare states; Delta=0 gives Omega_n=2*|g|*sqrt(n); n=0 is the separate vacuum; g and -g are unitarily gauge-equivalent; finite Fock cutoffs retain the blocks below the top boundary",
        "operator_boundary": "On the full Fock space the unitary is noncompact and not Schatten, so no ordinary trace or Fredholm determinant is asserted",
    }
    check(data["frozen_object"] == expected_frozen, "frozen semantics")
    check(data["theorem"] == expected_theorem, "theorem semantics")
    check(data["route_a"]["tuple"] == ["A0_FAIL", "A1_FAIL", "A2_FAIL", "A3_FAIL", "A4_NATURAL_QUANTIZATION"], "route tuple")
    check(data["route_a"]["overall"] == "ROUTE_A_REJECTED" and data["route_a"]["route_b_invocation_allowed"] is False, "route verdict")
    check(all(value is False for value in data["scope_flags"].values()), "scope flags")
    check(data["payload_sha256"] == payload_hash(data), "payload hash")

    expected_params = [{"parameter_label": label, "omega_c": str(wc), "omega_q": str(wq), "g": str(g)} for label, wc, wq, g in PARAMETERS]
    check(data["regression"]["parameter_rows"] == expected_params, "parameter rows")
    check(data["regression"]["n_values"] == N_VALUES and data["regression"]["t_values"] == [str(t) for t in T_VALUES], "grids")
    lookup = {label: (wc, wq, g) for label, wc, wq, g in PARAMETERS}
    tol = mp.mpf("1e-70")
    block_keys = ["case_id", "parameter_label", "omega_c", "omega_q", "g", "n", "center_energy", "detuning", "rabi_frequency_squared", "rabi_frequency", "lower_energy", "upper_energy", "block_trace", "block_determinant", "mixing_fraction"]
    seen = set()
    for i, row in enumerate(data["regression"]["block_rows"]):
        keys(row, block_keys, f"block[{i}]")
        check(row["parameter_label"] in lookup and row["n"] in N_VALUES, f"block[{i}] domain")
        label, n = row["parameter_label"], row["n"]
        wc, wq, g = lookup[label]
        ident = (label, n)
        check(ident not in seen, f"block[{i}] duplicate")
        seen.add(ident)
        check(row["case_id"] == f"{label}_n{n}" and (row["omega_c"], row["omega_q"], row["g"]) == (str(wc), str(wq), str(g)), f"block[{i}] identity")
        center, delta = (F(n) - F(1, 2)) * wc, wq - wc
        omega_sq = delta * delta + 4 * g * g * n
        omega = mp.sqrt(q(omega_sq))
        check(row["center_energy"] == str(center) and row["detuning"] == str(delta) and row["rabi_frequency_squared"] == str(omega_sq), f"block[{i}] exact scalars")
        check(abs(mp.mpf(row["rabi_frequency"]) - omega) < tol, f"block[{i}] omega")
        check(abs(mp.mpf(row["lower_energy"]) - (q(center) - omega / 2)) < tol and abs(mp.mpf(row["upper_energy"]) - (q(center) + omega / 2)) < tol, f"block[{i}] eigenvalues")
        check(row["block_trace"] == str(2 * center) and row["block_determinant"] == str(center * center - omega_sq / 4), f"block[{i}] invariants")
        mixing = mp.mpf(0) if omega_sq == 0 else q(4 * g * g * n / omega_sq)
        check(abs(mp.mpf(row["mixing_fraction"]) - mixing) < tol and 0 <= mixing <= 1, f"block[{i}] mixing")
    check(len(seen) == len(PARAMETERS) * len(N_VALUES), "block closure")

    dyn_keys = ["case_id", "parameter_label", "omega_c", "omega_q", "g", "n", "t", "cosine_half_rabi", "sine_half_rabi", "transition_probability", "survival_probability", "propagator_trace_real", "propagator_trace_imag", "propagator_determinant_real", "propagator_determinant_imag", "unitarity_residual"]
    seen_dyn = set()
    max_unitarity = mp.mpf(0)
    for i, row in enumerate(data["regression"]["dynamics_rows"]):
        keys(row, dyn_keys, f"dynamics[{i}]")
        label, n, t = row["parameter_label"], row["n"], F(row["t"])
        check(label in lookup and n in N_VALUES and t in T_VALUES, f"dynamics[{i}] domain")
        wc, wq, g = lookup[label]
        ident = (label, n, t)
        check(ident not in seen_dyn, f"dynamics[{i}] duplicate")
        seen_dyn.add(ident)
        check(row["case_id"] == f"{label}_n{n}_t{t}" and (row["omega_c"], row["omega_q"], row["g"]) == (str(wc), str(wq), str(g)), f"dynamics[{i}] identity")
        center, delta = (F(n) - F(1, 2)) * wc, wq - wc
        omega_sq = delta * delta + 4 * g * g * n
        omega, tt = mp.sqrt(q(omega_sq)), q(t)
        cosine, sine = mp.cos(omega * tt / 2), mp.sin(omega * tt / 2)
        transition = mp.mpf(0) if omega_sq == 0 else q(4 * g * g * n / omega_sq) * sine * sine
        check(abs(mp.mpf(row["cosine_half_rabi"]) - cosine) < tol and abs(mp.mpf(row["sine_half_rabi"]) - sine) < tol, f"dynamics[{i}] trig")
        check(abs(mp.mpf(row["transition_probability"]) - transition) < tol and abs(mp.mpf(row["survival_probability"]) - (1 - transition)) < tol, f"dynamics[{i}] probabilities")
        check(-tol <= transition <= 1 + tol, f"dynamics[{i}] probability range")
        phase = mp.exp(-1j * q(center) * tt)
        trace, determinant = 2 * phase * cosine, phase * phase
        check(abs(mp.mpf(row["propagator_trace_real"]) - mp.re(trace)) < tol and abs(mp.mpf(row["propagator_trace_imag"]) - mp.im(trace)) < tol, f"dynamics[{i}] trace")
        check(abs(mp.mpf(row["propagator_determinant_real"]) - mp.re(determinant)) < tol and abs(mp.mpf(row["propagator_determinant_imag"]) - mp.im(determinant)) < tol, f"dynamics[{i}] determinant")
        if omega_sq == 0:
            U = mp.matrix([[phase, 0], [0, phase]])
        else:
            az = q(delta) / omega
            ax = 2 * q(g) * mp.sqrt(n) / omega
            U = phase * mp.matrix([[cosine - 1j * az * sine, -1j * ax * sine], [-1j * ax * sine, cosine + 1j * az * sine]])
        gram = U.transpose_conj() * U - mp.eye(2)
        residual = max(abs(gram[r, c]) for r in range(2) for c in range(2))
        max_unitarity = max(max_unitarity, residual)
        check(residual < tol and abs(mp.mpf(row["unitarity_residual"])) < tol, f"dynamics[{i}] unitarity")
    check(len(seen_dyn) == len(PARAMETERS) * len(N_VALUES) * len(T_VALUES), "dynamics closure")

    vacuum_keys = ["parameter_label", "omega_q", "vacuum_energy"]
    check(len(data["regression"]["vacuum_rows"]) == len(PARAMETERS), "vacuum count")
    for i, row in enumerate(data["regression"]["vacuum_rows"]):
        keys(row, vacuum_keys, f"vacuum[{i}]")
        wc, wq, g = lookup[row["parameter_label"]]
        check(row["omega_q"] == str(wq) and row["vacuum_energy"] == str(-wq / 2), f"vacuum[{i}] energy")

    # Direct finite Fock-space reconstruction, independent of producer rows.
    photon_dim = 5
    annihilation = sp.zeros(photon_dim)
    for n in range(1, photon_dim):
        annihilation[n - 1, n] = sp.sqrt(n)
    creation = annihilation.T
    number = creation * annihilation
    ident_p, ident_a = sp.eye(photon_dim), sp.eye(2)
    sz = sp.diag(1, -1)
    sm = sp.Matrix([[0, 0], [1, 0]])
    spm = sm.T
    excitation = sp.diag(1, 0)
    wc, wq, g = sp.Rational(1), sp.Rational(1), sp.Rational(1, 2)
    H = wc * sp.kronecker_product(number, ident_a) + wq / 2 * sp.kronecker_product(ident_p, sz) + g * (sp.kronecker_product(creation, sm) + sp.kronecker_product(annihilation, spm))
    N = sp.kronecker_product(number, ident_a) + sp.kronecker_product(ident_p, excitation)
    check(H * N - N * H == sp.zeros(2 * photon_dim), "finite Fock commutator")
    for n in range(1, photon_dim):
        # basis index 2*k for |e,k>, 2*k+1 for |g,k>
        indices = [2 * (n - 1), 2 * n + 1]
        block = H.extract(indices, indices)
        expected = sp.Matrix([[(n - 1) * wc + wq / 2, g * sp.sqrt(n)], [g * sp.sqrt(n), n * wc - wq / 2]])
        check(block == expected, f"finite Fock block {n}")

    boundaries = {
        "vacuum": "n=0 is one-dimensional and is not inserted into the n>=1 square-root formula",
        "zero_coupling": "g=0 gives diagonal bare evolution, including the Omega=0 continuous-limit block",
        "resonance": "Delta=0 gives complete exchange amplitude for every coupled block",
        "coupling_sign": "g and -g are related by a diagonal atomic phase and have identical energies and probabilities",
        "finite_cutoff": "a finite Fock compression preserves excitation blocks below its top dangling state",
        "full_fock_operator": "the full unitary has infinite singular values equal to one and is neither compact nor Schatten",
        "revival": "finite-support population and full state-vector revival conditions are distinguished",
    }
    check(len(data["regression"]["boundary_rows"]) == len(boundaries), "boundary count")
    for i, row in enumerate(data["regression"]["boundary_rows"]):
        keys(row, ["boundary_id", "statement"], f"boundary[{i}]")
        check(row["boundary_id"] in boundaries and row["statement"] == boundaries[row["boundary_id"]], f"boundary[{i}] semantics")
    for i, citation in enumerate(data["citations"]):
        keys(citation, ["key", "claim", "title", "authors", "venue", "date", "url", "persistent_url"], f"citation[{i}]")
    expected_citations = [
        {"key": "JaynesCummings1963", "claim": "original rotating-wave two-level atom and single-mode radiation model", "title": "Comparison of quantum and semiclassical radiation theories with application to the beam maser", "authors": "Edwin T. Jaynes and Frederick W. Cummings", "venue": "Proceedings of the IEEE 51, 89--109", "date": "1963", "url": "https://doi.org/10.1109/PROC.1963.1664", "persistent_url": "https://doi.org/10.1109/PROC.1963.1664"},
        {"key": "ShoreKnight1993", "claim": "review of exact Jaynes--Cummings dynamics, dressed states and collapse/revival context", "title": "The Jaynes-Cummings model", "authors": "Bruce W. Shore and Peter L. Knight", "venue": "Journal of Modern Optics 40, 1195--1238", "date": "1993", "url": "https://doi.org/10.1080/09500349314551321", "persistent_url": "https://doi.org/10.1080/09500349314551321"},
    ]
    check(data["citations"] == expected_citations, "citation semantics")
    expected_nonclaims = [
        "priority for the Jaynes--Cummings model, dressed states or Rabi oscillations",
        "the finite excitation grid proves an infinite-dimensional operator theorem",
        "dressed energies or Rabi frequencies are target zeros or arithmetic spectral data",
        "an ordinary trace or Fredholm determinant exists for the full Fock-space unitary",
        "a Hilbert-Polya operator, target divisor, Euler factor, root number, automorphy, external peer review, or Route-B authorization",
    ]
    check(data["nonclaims"] == expected_nonclaims, "nonclaims")
    expected_summary = {"parameter_count": 4, "block_row_count": 32, "dynamics_row_count": 64, "vacuum_row_count": 4, "boundary_row_count": 7, "serialized_decimal_digits": 82}
    check(data["summary"] == expected_summary, "summary")
    print(json.dumps({"status": "C223_CHECKER_PASS", "assertions": assertions, "block_rows": len(seen), "dynamics_rows": len(seen_dyn), "finite_fock_dimension": 2 * photon_dim, "max_unitarity_residual": mp.nstr(max_unitarity, 5), "producer_imported": False}, sort_keys=True))


if __name__ == "__main__":
    main()
