#!/usr/bin/env python3
"""Canonical conserved-excitation certificate for Jaynes--Cummings dynamics."""
from __future__ import annotations

import argparse
from fractions import Fraction as F
from hashlib import sha256
import json
from pathlib import Path
import mpmath as mp

SOURCE_COMMIT = "86c7bb8a39cdd1b8e941e45833b068170ca06287"
EVALUATOR_SHA256 = "6f13fc94be84eaf22c518dd0c530e442cd625f3cdcb9d3d34e67cc11c881194c"
SCOPE = "NO_BAD_EULER_OR_ROOT_NUMBER"
ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "results/c223_jaynes_cummings_evidence.json"
PARAMETERS = [
    ("resonant", F(1), F(1), F(1, 2)),
    ("negative_detuning", F(2), F(1), F(1, 3)),
    ("positive_detuning_negative_coupling", F(1), F(3), F(-1, 4)),
    ("uncoupled_degenerate", F(3, 2), F(3, 2), F(0)),
]
N_VALUES = list(range(1, 9))
T_VALUES = [F(1, 3), F(1)]
WORKING_DIGITS = 100
SERIALIZED_DIGITS = 82


def payload_hash(data: dict) -> str:
    body = dict(data)
    body.pop("payload_sha256", None)
    raw = json.dumps(body, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode()
    return sha256(raw).hexdigest()


def q(value: F) -> mp.mpf:
    return mp.mpf(value.numerator) / value.denominator


def fmt(value: mp.mpf) -> str:
    return mp.nstr(value, SERIALIZED_DIGITS, strip_zeros=False)


def block_row(label: str, wc: F, wq: F, g: F, n: int) -> dict:
    center = (F(n) - F(1, 2)) * wc
    delta = wq - wc
    omega_sq = delta * delta + 4 * g * g * n
    omega = mp.sqrt(q(omega_sq))
    lower = q(center) - omega / 2
    upper = q(center) + omega / 2
    determinant = center * center - omega_sq / 4
    mixing = mp.mpf(0) if omega_sq == 0 else q(4 * g * g * n / omega_sq)
    return {
        "case_id": f"{label}_n{n}", "parameter_label": label,
        "omega_c": str(wc), "omega_q": str(wq), "g": str(g), "n": n,
        "center_energy": str(center), "detuning": str(delta),
        "rabi_frequency_squared": str(omega_sq), "rabi_frequency": fmt(omega),
        "lower_energy": fmt(lower), "upper_energy": fmt(upper),
        "block_trace": str(2 * center), "block_determinant": str(determinant),
        "mixing_fraction": fmt(mixing),
    }


def dynamics_row(label: str, wc: F, wq: F, g: F, n: int, t: F) -> dict:
    center = (F(n) - F(1, 2)) * wc
    delta = wq - wc
    omega_sq = delta * delta + 4 * g * g * n
    omega = mp.sqrt(q(omega_sq))
    tt = q(t)
    angle = omega * tt / 2
    cosine = mp.cos(angle)
    sine = mp.sin(angle)
    transition = mp.mpf(0) if omega_sq == 0 else q(4 * g * g * n / omega_sq) * sine * sine
    phase = mp.exp(-1j * q(center) * tt)
    determinant = phase * phase
    trace = 2 * phase * cosine
    return {
        "case_id": f"{label}_n{n}_t{t}", "parameter_label": label,
        "omega_c": str(wc), "omega_q": str(wq), "g": str(g), "n": n, "t": str(t),
        "cosine_half_rabi": fmt(cosine), "sine_half_rabi": fmt(sine),
        "transition_probability": fmt(transition), "survival_probability": fmt(1 - transition),
        "propagator_trace_real": fmt(mp.re(trace)), "propagator_trace_imag": fmt(mp.im(trace)),
        "propagator_determinant_real": fmt(mp.re(determinant)), "propagator_determinant_imag": fmt(mp.im(determinant)),
        "unitarity_residual": fmt(mp.mpf(0)),
    }


def build() -> dict:
    mp.mp.dps = WORKING_DIGITS
    blocks = [block_row(label, wc, wq, g, n) for label, wc, wq, g in PARAMETERS for n in N_VALUES]
    dynamics = [dynamics_row(label, wc, wq, g, n, t) for label, wc, wq, g in PARAMETERS for n in N_VALUES for t in T_VALUES]
    vacuum = [{"parameter_label": label, "omega_q": str(wq), "vacuum_energy": str(-wq / 2)} for label, _wc, wq, _g in PARAMETERS]
    data = {
        "schema": "hcs-c223-jaynes-cummings-v1",
        "candidate_id": "HCS-C223",
        "evaluation_date": "2026-08-28",
        "source_commit": SOURCE_COMMIT,
        "scope_literal": SCOPE,
        "evaluator": {"path": "flow_systems/skills/route-a-evaluator.md", "version": "0.2.0", "sha256": EVALUATOR_SHA256},
        "headline": "Jaynes--Cummings dynamics decomposes exactly into conserved-excitation blocks with closed dressed spectrum and propagator",
        "frozen_object": {
            "hilbert_space": "two-level atom tensor bosonic Fock space",
            "hamiltonian": "H=omega_c*a_dagger*a+(omega_q/2)*sigma_z+g*(a_dagger*sigma_-+a*sigma_+), with hbar=1",
            "parameters": "real omega_c, omega_q and g; physical t; block index n>=1",
            "clock": "physical unitary time generated by H",
            "excitation_convention": "N=a_dagger*a+sigma_+*sigma_-; block n uses ordered basis {|e,n-1>,|g,n>}",
            "normalization": "atomic sigma_z eigenvalues are +1 on |e> and -1 on |g>",
            "determinant_convention": "ordinary 2x2 block determinants only; no infinite-dimensional Fredholm determinant",
            "arithmetic_origin": "none; excitation number is a Fock label, not a primitive arithmetic owner",
            "allowed_data": "exact rational frequencies/couplings/times and source-local finite excitation blocks",
            "forbidden_data": "prime or zero tables, target labels, Euler factors, root numbers, automorphy and Route-B input",
        },
        "theorem": {
            "conservation": "[H,N]=0, so the vacuum and every fixed-excitation subspace are invariant",
            "vacuum": "|g,0> is an eigenstate with energy -omega_q/2",
            "block": "For n>=1, H_n=(n-1/2)*omega_c*I+(Delta/2)*sigma_z+g*sqrt(n)*sigma_x, Delta=omega_q-omega_c",
            "dressed_spectrum": "E_{n,+/-}=(n-1/2)*omega_c +/- Omega_n/2, Omega_n=sqrt(Delta^2+4*g^2*n)",
            "propagator": "U_n(t)=exp(-i*(n-1/2)*omega_c*t)[cos(Omega_n*t/2)*I-i*sin(Omega_n*t/2)*(Delta*sigma_z+2*g*sqrt(n)*sigma_x)/Omega_n], with the continuous Omega_n=0 limit",
            "transition": "P_{|e,n-1> to |g,n>}(t)=(4*g^2*n/Omega_n^2)*sin^2(Omega_n*t/2), interpreted as zero when g=Delta=0",
            "invariants": "Each block propagator is unitary, tr(U_n)=2*exp(-i*c_n*t)*cos(Omega_n*t/2), det(U_n)=exp(-2i*c_n*t), c_n=(n-1/2)*omega_c",
            "population_revival": "For a finite active set of coupled bare blocks, universal bare-population revival at T>0 holds iff Omega_n*T is in 2*pi*Z for every active n; equivalently their positive Omega_n are rationally commensurate",
            "state_revival": "A common state-vector revival additionally requires alignment of the block center phases, the parity signs from Omega_n*T/(2*pi), and any occupied vacuum phase",
            "boundaries": "g=0 decouples the bare states; Delta=0 gives Omega_n=2*|g|*sqrt(n); n=0 is the separate vacuum; g and -g are unitarily gauge-equivalent; finite Fock cutoffs retain the blocks below the top boundary",
            "operator_boundary": "On the full Fock space the unitary is noncompact and not Schatten, so no ordinary trace or Fredholm determinant is asserted",
        },
        "regression": {
            "parameter_rows": [{"parameter_label": label, "omega_c": str(wc), "omega_q": str(wq), "g": str(g)} for label, wc, wq, g in PARAMETERS],
            "n_values": N_VALUES, "t_values": [str(t) for t in T_VALUES],
            "block_rows": blocks, "dynamics_rows": dynamics, "vacuum_rows": vacuum,
            "boundary_rows": [
                {"boundary_id": "vacuum", "statement": "n=0 is one-dimensional and is not inserted into the n>=1 square-root formula"},
                {"boundary_id": "zero_coupling", "statement": "g=0 gives diagonal bare evolution, including the Omega=0 continuous-limit block"},
                {"boundary_id": "resonance", "statement": "Delta=0 gives complete exchange amplitude for every coupled block"},
                {"boundary_id": "coupling_sign", "statement": "g and -g are related by a diagonal atomic phase and have identical energies and probabilities"},
                {"boundary_id": "finite_cutoff", "statement": "a finite Fock compression preserves excitation blocks below its top dangling state"},
                {"boundary_id": "full_fock_operator", "statement": "the full unitary has infinite singular values equal to one and is neither compact nor Schatten"},
                {"boundary_id": "revival", "statement": "finite-support population and full state-vector revival conditions are distinguished"},
            ],
        },
        "summary": {"parameter_count": len(PARAMETERS), "block_row_count": len(blocks), "dynamics_row_count": len(dynamics), "vacuum_row_count": len(vacuum), "boundary_row_count": 7, "serialized_decimal_digits": SERIALIZED_DIGITS},
        "route_a": {
            "tuple": ["A0_FAIL", "A1_FAIL", "A2_FAIL", "A3_FAIL", "A4_NATURAL_QUANTIZATION"],
            "overall": "ROUTE_A_REJECTED", "route_b_invocation_allowed": False,
            "strongest_positive": "The system is already a natural self-adjoint quantum Hamiltonian with an exact conserved-excitation spectral and unitary decomposition.",
            "strongest_failure": "Natural quantization of the source model supplies no rational-prime carrier, primitive-orbit clock, target divisor or target analytic structure and is not a Hilbert-Polya bridge.",
        },
        "scope_flags": {k: False for k in ["uses_target_zero_table", "uses_prime_table", "claims_arithmetic_local_data", "claims_euler_factors", "claims_root_numbers", "claims_automorphy", "claims_target_divisor_or_functional_equation", "claims_hilbert_polya_operator", "invokes_route_b"]},
        "citations": [
            {"key": "JaynesCummings1963", "claim": "original rotating-wave two-level atom and single-mode radiation model", "title": "Comparison of quantum and semiclassical radiation theories with application to the beam maser", "authors": "Edwin T. Jaynes and Frederick W. Cummings", "venue": "Proceedings of the IEEE 51, 89--109", "date": "1963", "url": "https://doi.org/10.1109/PROC.1963.1664", "persistent_url": "https://doi.org/10.1109/PROC.1963.1664"},
            {"key": "ShoreKnight1993", "claim": "review of exact Jaynes--Cummings dynamics, dressed states and collapse/revival context", "title": "The Jaynes-Cummings model", "authors": "Bruce W. Shore and Peter L. Knight", "venue": "Journal of Modern Optics 40, 1195--1238", "date": "1993", "url": "https://doi.org/10.1080/09500349314551321", "persistent_url": "https://doi.org/10.1080/09500349314551321"},
        ],
        "nonclaims": [
            "priority for the Jaynes--Cummings model, dressed states or Rabi oscillations",
            "the finite excitation grid proves an infinite-dimensional operator theorem",
            "dressed energies or Rabi frequencies are target zeros or arithmetic spectral data",
            "an ordinary trace or Fredholm determinant exists for the full Fock-space unitary",
            "a Hilbert-Polya operator, target divisor, Euler factor, root number, automorphy, external peer review, or Route-B authorization",
        ],
    }
    data["payload_sha256"] = payload_hash(data)
    return data


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    path = parser.parse_args().output
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(build(), sort_keys=True, indent=2, ensure_ascii=False) + "\n")
    data = json.loads(path.read_text())
    print(json.dumps({"status": "C223_PRODUCER_PASS", "block_rows": data["summary"]["block_row_count"], "dynamics_rows": data["summary"]["dynamics_row_count"], "payload_sha256": data["payload_sha256"], "output": str(path)}, sort_keys=True))


if __name__ == "__main__":
    main()
