// Restricted Recovery1 serializer: local reads and stdout only; no networking.
const fs=require('fs'), crypto=require('crypto');
const base='papers/31-level11-conjugacy-owner-ledger/', old='notes/stage4_5_round4_', pre='notes/stage4_5_round4_recovery1_';
const read=p=>fs.readFileSync(base+p,'utf8'), json=p=>JSON.parse(read(p));
const sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const bind=p=>({path:base+p,sha256:sha(fs.readFileSync(base+p)),bytes:fs.statSync(base+p).size});
const draft=read('notes/stage4_prime_revision_round6.tex'), raw=Buffer.from(draft), draftHash=sha(raw);
if(draftHash!=='4bc1a960b5527a5d389b5c70e29fa0dc7b3199b93a808dd3f347616dd686d1a3')throw Error('STOP: locked draft mismatch');
const marks=[...draft.matchAll(/<!--block:(B\d+)-->\n/g)];
const blocks=marks.map((m,i)=>({id:m[1],start:m.index+m[0].length,text:draft.slice(m.index+m[0].length,marks[i+1]?.index||draft.length).trimEnd()}));
const bm=Object.fromEntries(blocks.map(b=>[b.id,b]));
const bib=read('notes/stage4_prime_references_round2.bib');
const entries=[...bib.matchAll(/@(\w+)\{(P31-S\d+),([\s\S]*?)(?=\n@|$)/g)].map(m=>({id:m[2],type:m[1],fields:Object.fromEntries([...m[3].matchAll(/^\s*(\w+)\s*=\s*\{(.*)\},?\s*$/gm)].map(x=>[x[1],x[2]]))}));
const citationIDs=[...draft.matchAll(/\\citep\{([^}]+)\}/g)].flatMap(m=>m[1].split(','));
const output={};
const A=[
 ['web_batch1','https://academic.oup.com/jlms/article/s2-1/1/351/947970','OUP article: Millington, title, 1969, s2-1(1), 351–357 and DOI.'],
 ['web_supp10','https://onlinelibrary.wiley.com/doi/full/10.5402/2012/685103','Publisher-hosted original research reference 4 supplies R. S. Kulkarni, exact title, 1991, 113(6), 1053–1133 and DOI; Numdam original reference 9 independently supplies full Ravi S. name and same fields. Some secondary or later bibliographies say 1134 or 1992; they do not displace these concordant primary reference records.'],
 ['web_supp11','https://sites.google.com/view/serpeowtan/publications','Coauthor Tan publication 4 confirms all four names, exact title, journal, 1993, 4(1), 11–34. DOI was not independently established on an accessible primary page.'],
 ['web_batch1','https://londmathsoc.onlinelibrary.wiley.com/doi/10.1112/jlms/51.3.491','Publisher confirms three authors, exact title, 1995, 51(3), 491–502 and DOI.'],
 ['web_supp2','https://wstein.org/edu/Fall2003/252/lectures/09-19-03/Hsu-Identifying_congruence_subgroups_of_the_modular_group.pdf','Original publisher-formatted paper confirms Tim Hsu/title/124(5)/May 1996/1351. Author-uploaded original record on ResearchGate supplies DOI and 1351–1359; AMS original book bibliography corroborates complete page range.'],
 ['web_batch2','https://archive.numdam.org/item/JTNB_2009__21_2_467_0/','Original archive article/BibTeX confirms John Voight, title, JTNB 21(2), 2009, 467–489 and DOI.'],
 ['web_supp8','https://msp.org/pjm/2013/261-2/pjm-v261-n2-p.pdf','Publisher-hosted original research reference confirms C. G. Latimer/C. C. MacDuffee, title, 1933, 34(2), 313–316; Annals original research bibliography in web_supp5 confirms DOI 10.2307/1968204.'],
 ['web_batch2','https://www.cambridge.org/core/journals/canadian-journal-of-mathematics/article/on-a-theorem-of-latimer-and-macduffee/A7185F4D644F242C297630826F6B4781','Publisher confirms Olga Taussky/title/1949/1(3)/300–302/DOI; later digital posting is not publication year.'],
 ['web_supp6','https://www.aimsciences.org/article/doi/10.3934/cpaa.2013.12.1183','Publisher original reference 36 confirms Wallace/exact title/1984/283/177–184/DOI; MSP original reference in web_supp8 confirms issue 1.'],
 ['web_batch3','https://www.tandfonline.com/doi/abs/10.1080/00927878108822637','Publisher confirms both authors/title/1981/9(11)/1121–1130/DOI; 2007 online posting is not original year.'],
 ['web_batch3','https://www.sciencedirect.com/science/chapter/bookseries/abs/pii/S0049237X08713351','Publisher original chapter confirms title, 1980, Studies in Logic and Foundations of Mathematics 95, 101–139 and DOI; author profile and original reference corroborate Fritz J. Grunewald / Word Problems II / North-Holland.'],
 ['web_batch3','https://www.jstor.org/stable/1971091','Original JSTOR record confirms both authors, Some General Algorithms. I: Arithmetic Groups, 1980, Annals 112(3), 531–583, DOI.'],
 ['web_batch4','https://londmathsoc.onlinelibrary.wiley.com/doi/10.1112/jlms.12246','Publisher confirms Eick/Hofmann/O’Brien, exact title, 2019, 100(3), 731–756 and DOI.'],
 ['web_batch4','https://www.sciencedirect.com/science/article/pii/0022314X82900282','Publisher original article confirms Peter Sarnak, exact title, JNT 15(2), 1982, 229–247 and DOI.'],
 ['web_batch4','https://academic.oup.com/jlms/article-abstract/s2-31/1/69/893542','Publisher confirms Caroline Series/title/1985/s2-31(1)/69–80/DOI; author bibliography typo 69–85 is not adopted. Bib 31 is journal numeric-volume variant of s2-31.'],
 ['web_supp6','https://doi.org/10.1142/S0218196706002986','Original publisher landing confirms authors/title/DOI; WRAP original institutional record in web_supp5 confirms 2006, 16(2), 287–305. The 287–306 secondary bibliographic error is not adopted.'],
 ['web_supp1','https://doi.org/10.1142/S0218196713500203','Publisher confirms Buckley/Holt/title/2013/DOI; author-hosted original bibliography in web_supp5 confirms 23(5), 1127–1150. 2011 is the preprint date, not publication year.'],
 ['web_supp1','https://research.unsw.edu.au/people/professor-john-anthony-gerard-roberts/publications?type=journalarticles','Author institutional publication list confirms both authors/title/2001/14/R1–R24/DOI; author-hosted published paper confirms issue-4 publication code and same 24-page range.'],
 ['web_batch5','https://www.ams.org/notices/200202/fea-lenstra.pdf','Original AMS paper first page confirms H. W. Lenstra Jr./title/49(2)/182 and February 2002; AMS original book bibliography confirms 182–192. URL is indexed; no claim of unrestricted PDF access.'],
 ['web_batch5','https://link.springer.com/book/10.1007/978-3-662-02945-9','Publisher confirms Henri Cohen/title/1993/Springer/GTM 138/DOI; 2013 ebook release does not change original book year.'],
 ['web_batch6','https://www.mathnet.ru/eng/sm3853','Original journal archive confirms both names/title/2008/199(7)/1009–1031/English DOI; Russian pagination is a different edition.'],
 ['web_supp9','https://ems.press/content/serial-article-files/30121','Publisher-hosted original research reference 29 confirms Charles Traina/title/1985/JNT 21(2)/176–184; original paper text agrees. Exact DOI field remains unavailable on accessible primary pages.'],
 ['web_supp1','https://doi.org/10.1145/263699.263712','Original ACM page confirms George C. Necula/title/POPL 24/1997/106–119/DOI/ACM.'],
 ['web_batch6','https://www.usenix.org/conference/usenixsecurity09/technical-sessions/presentation/efficient-data-structures-tamper-evident','Original USENIX page/BibTeX confirms both authors/title/2009/18th USENIX Security/Montreal/USENIX Association/URL.']
];
output.reference_audit={paper_id:'P31',audit_round:4,recovery:1,bibliography:bind('notes/stage4_prime_references_round2.bib'),checked:24,identity_verified:24,identity_not_found:0,identity_mismatch:0,field_gaps:2,rows:entries.map((e,i)=>({...e,verdict:'VERIFIED',verdict_scope:'work_identity_and_explicitly_confirmed_fields_not_unavailable_DOI_field',seed:'locked BibTeX author/title/year/identifier, never quarantined API metadata',web_audit:bind(pre+A[i][0]+'.json'),top_supporting_primary_url:A[i][1],confirmed_details:A[i][2],doi_field_status:[2,21].includes(i)?'UNVERIFIABLE_ACCESS':e.fields.doi?'VERIFIED':'NOT_APPLICABLE',source_identity_does_not_verify_passage:true})),ghost_citations:{bibliography_entries:entries.length,unique_cited_identifiers:new Set(citationIDs).size,citation_occurrences:citationIDs.length,orphans:entries.filter(e=>!citationIDs.includes(e.id)).map(e=>e.id),dangling:[...new Set(citationIDs)].filter(id=>!entries.some(e=>e.id===id))},metadata_issues:['P31-S03 DOI 10.1142/S0129167X93000030: primary field binding unavailable; work positively established by coauthor publication list.','P31-S22 DOI 10.1016/0022-314X(85)90049-6: primary field binding unavailable; work positively established by original paper and publisher-hosted original bibliography.'],interpretation:'The two access gaps are not work NOT_FOUND, are not evidence of fabricated works/wrong DOIs, and do not automatically invalidate a supported modest citation context. No citation/API cache or unauthorized return is controlling.'};
// Each source body below is fresh ordinary browser text, except the explicitly
// identified pre-existing locked S09 abstract. Only original source fields are read.
const sourceSpec=[
 ['P31-S05','web_supp2','https://wstein.org/edu/Fall2003/252/lectures/09-19-03/Hsu-Identifying_congruence_subgroups_of_the_modular_group.pdf','We exhibit a simple test (Theorem 2.4) for determining if a given (classical) modular subgroup is a congruence subgroup','Original published paper p. 1351, Abstract sentence 1'],
 ['P31-S06','web_batch2','https://archive.numdam.org/item/JTNB_2009__21_2_467_0/','We exhibit an algorithm to compute a Dirichlet domain for a Fuchsian group Γ with cofinite area.','Original journal archive, abstract sentence 1'],
 ['P31-S08','web_batch2','https://www.cambridge.org/core/journals/canadian-journal-of-mathematics/article/on-a-theorem-of-latimer-and-macduffee/A7185F4D644F242C297630826F6B4781','The matrix solutions of an irreducible algebraic equation with integral coefficients were studied by Latimer and MacDuffee.','Original publisher page, opening extract'],
 ['P31-S16','web_supp6','https://doi.org/10.1142/S0218196706002986','The main result proved in this paper is that the conjugacy problem in word-hyperbolic groups is solvable in linear time.','Original publisher page, Abstract sentence 1'],
 ['P31-S17','web_supp1','https://doi.org/10.1142/S0218196713500203','An (non-practical) algorithm is described that, given as input two lists A and B','Original publisher page, Abstract algorithm sentence'],
 ['P31-S19','web_batch5','https://www.ams.org/notices/200202/fea-lenstra.pdf','Modern textbooks usually give a formulation in terms of continued fractions','AMS original PDF p. 182, Pell’s Equation opening discussion']
];
const sourceMap={}, provenance=[];
for(const [id,file,url,excerpt,locator] of sourceSpec){const rec=json(pre+file+'.json');const text=rec.result??rec.r;const segments=text.split(/-{20,}/);const s=segments.find(s=>s.includes(url));if(!s)throw Error('Missing primary segment '+id);const body=s.replace(/\\Gamma/g,'Γ').replace(/\s+/g,' ').trim();if(!body.includes(excerpt))throw Error('Missing literal excerpt '+id);sourceMap[id]=body;provenance.push({ref_slug:id,carrier:bind(pre+file+'.json'),source_url:url,source_body_kind:'ordinary_configured_browser_original_source_segment',source_body_sha256:sha(body),normalization:'retain only named original-source result segment; collapse whitespace; normalize TeX Gamma to Γ',exact_locator:locator,excerpt,excerpt_word_count:excerpt.split(/\s+/).length,excerpt_literal_match:true,evidence_limit:'Bounded original text establishes only the deliberately modest contextual use, not the whole registered role, theorem truth, author reading or project execution.'});}
const net=json('notes/stage4_5_round1_reference_network_audit.json');
let body=net.references.find(r=>r.ref_slug==='P31-S09').query_attempts.crossref_doi.crossref_message.abstract;
body=body.replace(/<[^>]*>/g,'').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#x([0-9a-f]+);/gi,(_,v)=>String.fromCodePoint(parseInt(v,16))).replace(/&#(\d+);/g,(_,v)=>String.fromCodePoint(Number(v))).replace(/\s+/g,' ').trim();
if(!body.includes('conjugacy classes of hyperbolic matrices'))throw Error('Missing locked S09 raw excerpt');
sourceMap['P31-S09']=body;provenance.push({ref_slug:'P31-S09',carrier:bind('notes/stage4_5_round1_reference_network_audit.json'),raw_field:'references[ref_slug=P31-S09].query_attempts.crossref_doi.crossref_message.abstract',source_body_kind:'pre_existing_input_locked_original_publisher_abstract_not_incident_API_output',source_body_sha256:sha(body),normalization:'strip HTML tags; decode common/numeric entities; collapse whitespace',exact_locator:'Input-locked original publisher abstract, opening sentence bounded phrase',excerpt:'conjugacy classes of hyperbolic matrices',excerpt_word_count:5,excerpt_literal_match:true,dependency_reconciliation:'This exact raw carrier predates the audit, is in the original input lock, and is not one of the 23 unauthorized calls or derivatives. No historical verdict is read or imported. Current source identity separately re-established from ordinary primary references. New semantic comparison uses only these actual source words.',evidence_limit:'Bounded phrase is not full-role or theorem support.'});
output.source_map=sourceMap;output.source_provenance={sources:provenance,source_identity_audit:pre+'reference_audit.json',human_read_inferred:false,programmatic_network:false};
// Reuse quarantined registry only as exact-byte extraction, never prior judgment.
const extracted=json(old+'claim_registry.json');
const claims=extracted.claims.map(c=>{if(raw.subarray(c.draft_span.start_byte,c.draft_span.end_byte).toString()!==c.claim_text)throw Error('Extraction mismatch');return {...c,claim_id:c.claim_id.replace('P31-R4-','P31-R4R1-')};});
const authorStart=draft.indexOf('\\author{',bm.B0003.start),authorEnd=draft.indexOf('\n\\date{',authorStart);
claims.unshift({claim_id:'P31-R4R1-B0003-001',claim_text:draft.slice(authorStart,authorEnd),draft_span:{start_byte:Buffer.byteLength(draft.slice(0,authorStart)),end_byte:Buffer.byteLength(draft.slice(0,authorEnd))},claim_kinds:['other_factual'],ref_slugs:[],writer_anchors:[],paper_section:'Frontmatter author and affiliation metadata',selection_tier:'ALL'});
const sourcesBlocks=new Set(['B0021','B0025','B0029','B0032','B0016','B0022','B0023','B0026','B0030','B0037','B0038','B0039','B0112','B0089']);
function decide(c){const block=c.claim_id.match(/B\d+/)[0];let scope='prospective_project_definition_or_conditional_logic',basis=['notes/stage1_phase6_claim_intent_manifest.json','notes/stage1_phase1_methodology_blueprint.md','notes/stage4_prime_revision_evidence_bundle_round6.json'];let detail='Read in its whole current block as a proposed definition, conditional design consequence, or required future test. Resolved-domain canonicalizer and totality are distinguished; G/I/C cardinalities are conditional; root/inverse/primitive restrictions are retained. This is not verification that a solver, certificate or owner theorem exists or has executed.';
 if(sourcesBlocks.has(block)){scope='bounded_source_record_or_context';basis=['notes/stage4_prime_method_passage_matrix_round3.json',pre+'reference_audit.json',pre+'source_provenance.json'];detail='Current source-specific context is deliberately limited to metadata identification or the bounded original excerpt. Fresh ordinary primary-source identity checks and actual source text support that modest context; 15 historical method passages and 2 metadata-only neighbors do not gain substantive role/theorem support. Project coding and transfer exclusions are checked as local matrix records. S03/S22 DOI-field access gaps do not defeat independently established work identity or local prospective coding.';}
 if(['B0006','B0007','B0011','B0012','B0045'].includes(block)){scope='frozen_population_and_design_scope';basis.push('notes/stage1_phase1_rq_brief.md');detail='Compared frozen 138 inputs / 55 groups and the approved restricted owner-ledger design. Direct arithmetic: 138*137/2=9453 and 2+2+134=138. These are frozen input/control values, not a fresh census or primitive-owner result. Claims retain the literature-only and conditional-design qualifiers.';}
 if(['B0036','B0041'].includes(block)){scope='historical_execution_record';basis=['notes/stage1_phase2_annotated_bibliography.md','notes/stage4_prime_literature_replay_round2.raw.json','notes/stage4_prime_literature_screening_ledger_round2.json'];detail='The dated local replay has 20 recorded queries, one top metadata observation each, and an 18-retained/2-outside-scope split. The upstream aggregate arithmetic is 44−9=35−13=22; original capture/dedup/screen event rows remain unavailable. The later replay is explicitly a different observation and does not authenticate original execution.';}
 if(['B0079','B0105'].includes(block)){scope='artifact_recovery_boundary';basis=['notes/stage4_prime_reader_artifact_manifest_round2.json','notes/stage4_prime_method_passage_matrix_round3.json'];detail='The historical reader-manifest bytes and stale method-matrix descriptor are local observable records. Current prose explicitly disclaims exact current reconstruction and permanent archival deposit; no prospective synchronization has been counted as performed.';}
 if(['B0090','B0091','B0092','B0099','B0101','B0107','B0108'].includes(block)){scope='workflow_attribution_and_verification_boundary';detail='Compared only to named project records and exact author-authority chain. Approvals/contributions are recorded attributions, not authenticated personal acts or an attestation of reading exact source passages. Current any disclaimer is restored under R6; the R3 historical weakening remains E6 history. No full model chronology, solver execution, independent errors or global originality clearance is inferred.';}
 if(block==='B0104'){scope='non_empirical_ethics_applicability';basis=['notes/stage1_phase1_rq_brief.md','notes/stage4_5_round2_material_passport.json'];detail='Theoretical mathematics/published-source/workflow scope and the expressly empty experiment provenance support no participant/animal study in this project record. This is not an institutional ethics ruling.';}
 const pending=['B0003','B0102','B0103'].includes(block),historical=['B0036','B0041'].includes(block)&&/captured|deduplicated|screened|duplicates/.test(c.claim_text);
 if(pending){scope='author_owned_unresolved_attestation';basis=['BATCH_ROUND10_STAGE4_5_ROUND4_AUTHORIZATION.json'];detail='Funding and competing-interest facts are author-owned and explicitly remain unresolved. Neither existing prose, approval of the workflow, public pages about other works, nor model inference supplies the required exact attestation.';}
 if(block==='B0003'){scope='new_compound_author_metadata_finding';basis=['notes/stage1_phase6_claim_intent_manifest.json','notes/stage4_prime_revision_round6.tex'];detail='NEW finding, separate from the two preserved funding/interest pending items. Phase6 P31-P6-MNC-6 supports the supplied responsible-human name Liang Wang as a project attribution; the selected inputs do not independently confirm this person’s institutional affiliation, postal address or contact metadata. Existing frontmatter is the assertion, not its truth evidence. Treat the compound author block as UNVERIFIABLE pending original-author confirmation or neutral attribution. No false identity, false employment or misconduct is alleged, and no external employment investigation is requested.';}
 return {claim_id:c.claim_id,block_id:block,verdict:pending?'UNVERIFIABLE':historical?'UNVERIFIABLE_ACCESS':'VERIFIED',verification_scope:scope,evidence_basis:basis,detail};}
const decisions=claims.map(decide);
output.claim_registry={schema_version:'claim-registry/1.0',draft_raw_sha256:draftHash,claims};
output.semantic_claim_review={paper_id:'P31',draft:bind('notes/stage4_prime_revision_round6.tex'),recovery:1,extraction_reuse:{artifact:bind(old+'claim_registry.json'),scope:'400 exact claim strings, byte spans, source identifiers, descriptive kinds and ALL selection only. No verdict or source judgment imported. Added one separately reviewed exact compound frontmatter claim.',claims_rebound_to_new_ids:true},semantic_review:'Same fresh Round4 full-draft semantic pass, reconsidered with Recovery1 primary-source evidence and an explicit frontmatter completeness correction. Every selected claim has a new explicit decision. Source identities, source passages, local definitions, original execution and author attestations remain separate.',semantic_extraction_coverage:'not_machine_detectable',block_population:blocks.length,claim_count:claims.length,claim_decisions:decisions,limits:['Formal/prospective VERIFIED means accurately scoped local definition/conditional reasoning, not a fulfilled scientific proof obligation.','No machine or model claim of exhaustive semantic extraction.','Frontmatter is now explicitly registered and UNVERIFIABLE; supplied name/affiliation/contact are not independently authenticated.']};
const contexts=[];const matrix=json('notes/stage4_prime_method_passage_matrix_round3.json');
for(const b of blocks)for(const m of b.text.matchAll(/\\citep\{([^}]+)\}/g))for(const id of m[1].split(',')){let a=0,e=b.text.length;if(['B0021','B0025','B0029','B0032'].includes(b.id)){a=Math.max(0,b.text.lastIndexOf('The bibliographic record ',m.index),b.text.lastIndexOf('The located passage ',m.index));e=b.text.indexOf('\n% ARS-CITE',m.index);if(e<0)e=b.text.length;}const prov=provenance.find(p=>p.ref_slug===id);contexts.push({context_id:'P31-R4R1-CTX-'+String(contexts.length+1).padStart(3,'0'),block_id:b.id,ref_slug:id,citation_byte_span:{start_byte:Buffer.byteLength(draft.slice(0,b.start+m.index)),end_byte:Buffer.byteLength(draft.slice(0,b.start+m.index+m[0].length))},context_text:b.text.slice(a,e),verdict:'VERIFIED',verification_scope:prov?'bounded_original_context_not_whole_role':'positive_work_identity_plus_explicit_metadata_only_local_coding',source_body_sha256:prov?.source_body_sha256??null,detail:prov?'Actual named original source words agree with the modest contextual attribution. Current wording withholds theorem/complete-role/project-result transfer.':'Work identity is positively established and the current passage explicitly denies substantive attribution. Local prospective role and excluded transfer are checked against the frozen matrix. An unavailable DOI field is not made into a failed source-content claim.'});}
output.citation_context_audit={paper_id:'P31',recovery:1,draft:bind('notes/stage4_prime_revision_round6.tex'),total_citation_occurrences:contexts.length,sampled:contexts.length,coverage_percent:100,verified:contexts.length,contexts,limits:['26 occurrences involve 24 distinct sources; S23/S24 each appears twice.','VERIFIED is context-specific and not a full-text reading, theorem-correctness or author-reading claim.']};
const name=process.argv[2];if(!Object.hasOwn(output,name))throw Error('Unknown output');const rendered=JSON.stringify(output[name],null,2)+'\n';if(process.argv[3]!==undefined){const off=Number(process.argv[3]);console.log(JSON.stringify({total:rendered.length,offset:off,chunk:rendered.slice(off,off+16000)}));}else console.log(rendered);
