// Same-audit Recovery2 completion. Local read-only inputs; JSON stdout only.
// Does not fetch, modify a predecessor, build evidence rows, or run validators.
const fs = require('fs'), crypto = require('crypto');
const base = 'papers/31-level11-conjugacy-owner-ledger/';
const r1 = 'notes/stage4_5_round4_recovery1_', r2 = 'notes/stage4_5_round4_recovery2_', r0 = 'notes/stage4_5_round4_';
const read = p => JSON.parse(fs.readFileSync(base+p, 'utf8'));
const sha = b => crypto.createHash('sha256').update(b).digest('hex');
const bind = p => { const b=fs.readFileSync(base+p); return {path:base+p,bytes:b.length,sha256:sha(b)}; };
const now = '2026-09-06T12:47:06Z';
const draft = bind('notes/stage4_prime_revision_round6.tex');
if(draft.sha256 !== '4bc1a960b5527a5d389b5c70e29fa0dc7b3199b93a808dd3f347616dd686d1a3') throw Error('STOP locked draft mismatch');
const registry = read(r1+'claim_registry.json'), semantic=read(r1+'semantic_claim_review.json');
const decisions = new Map(semantic.claim_decisions.map(x=>[x.claim_id,x]));
const A=read(r1+'reference_audit.json'), B=read(r1+'citation_context_audit.json');
const rows=read(r1+'evidence_rows.json'), coverage=read(r1+'claim_registry_coverage.json');
const D=read(r0+'originality_audit.json'), E6=read(r0+'e6_semantic_audit.json');
const checked=registry.claims.length, verified=semantic.claim_decisions.filter(c=>c.verdict==='VERIFIED').length;
const dataRows=registry.claims.filter(c=>c.claim_kinds.includes('quantitative')).map(c=>({claim_id:c.claim_id,claim_text:c.claim_text,...decisions.get(c.claim_id)}));
const rawInputs=['notes/stage1_phase1_rq_brief.md','notes/stage1_phase1_methodology_blueprint.md','notes/stage1_phase6_claim_intent_manifest.json','notes/stage1_phase2_annotated_bibliography.md','notes/stage4_prime_literature_replay_round2.raw.json','notes/stage4_prime_literature_screening_ledger_round2.json','notes/stage4_prime_method_passage_matrix_round3.json','notes/stage4_prime_reader_artifact_manifest_round2.json','notes/stage4_5_round2_material_passport.json'];
const output={};
output.preservation_and_reuse={paper_id:'P31',audit_round:4,recovery:2,recorded_at:now,receipt:'BATCH_ROUND10_STAGE4_5_ROUND4_RECOVERY2_RESUMPTION_RECEIPT.json',receipt_sha256:'1ec8accbe205e07b013eebb00dd649b1f0015a428452a9edfb3bcc728867cd36',scoped_preflight:{checked_existing_p31_files:226,mismatches:[],tool_chunk_id:'84c5cb',exit_code:0},read_only_predecessors:true,same_audit_not_new_round:true,network_since_recovery2:'NONE',reused_valid_artifacts:[r1+'reference_audit.json',r1+'citation_context_audit.json',r1+'claim_registry.json',r1+'semantic_claim_review.json',r1+'source_map.json',r1+'source_provenance.json',r1+'evidence_rows.json',r1+'claim_registry_coverage.json',r1+'official_evidence_checks.json',r1+'fresh_semantic_conclusions.json',r0+'originality_audit.json',r0+'e6_semantic_audit.json',r0+'claim_strength_drift_findings.json',r0+'bundle_validation.json'].map(bind),quarantined_material_policy:'No incident API output or derivative judgment controls a result. Recovery1 separately re-established source identity and source judgments; the old 400-row registry was reused only for exact extraction and complemented by new frontmatter claim. D and full E6 use independent ordinary-web or local-authority inputs, explicitly reconciled here. All original and failed files remain read-only.',valid_unchanged_checks_not_repeated:true,changed_completion_outputs_only:true};
const screeningIssue={claim:'B0036 and B0041: original capture/deduplication/screening execution',expected:'Original event-level provenance or an explicitly retrospective aggregate-record attribution approved in scope',actual:'44−9=35−13=22 is supported as historical aggregate arithmetic. Original execution rows are unavailable. The later dated 20-query, 18-retained/2-outside-scope replay is a distinct observable record, not an original reconstruction.',severity:'MEDIUM'};
output.data_audit={paper_id:'P31',audit_round:4,recovery:2,draft,claims_checked:dataRows.length,verified:dataRows.filter(x=>x.verdict==='VERIFIED').length,selection:'All 168 quantitatively tagged current registry entries, including contextual sentences, plus the nonnumeric core checks below. This is not 168 independent measurements.',semantic_basis:bind(r1+'semantic_claim_review.json'),raw_input_bindings:rawInputs.map(bind),core_checks:[
 {id:'C01',claim:'Frozen population and pair universe',observation:'138 inputs / 55 groups remain frozen inputs; 138*137/2=9453. No census was run.',status:'VERIFIED_AS_FROZEN_DESIGN'},
 {id:'C02',claim:'Inherited 2/2/134',observation:'2+2+134=138; manuscript explicitly restricts these to instance controls, not owners.',status:'VERIFIED_AS_FROZEN_CONTROL'},
 {id:'C03',claim:'Original literature capture/screen',observation:screeningIssue.actual,status:'UNVERIFIABLE_ACCESS_AT_ORIGINAL_EXECUTION_LEVEL'},
 {id:'C04',claim:'Later literature replay',observation:'Locked raw record has 20 exact queries, one top metadata observation each, dated 2026-09-03T15:50:00Z; ledger has 18 retained and 2 outside scope. No new API call is used.',status:'VERIFIED_LOCAL_RECORD_NOT_ORIGINAL_SEARCH'},
 {id:'C05',claim:'Reference population',observation:'Recovery1 independently establishes 24 work identities; current TeX has 26 citation occurrences and 24 unique identifiers, no ghosts. Two DOI fields remain unavailable.',status:'VERIFIED_COUNTS_WITH_FIELD_GAPS',evidence:[bind(r1+'reference_audit.json'),bind(r1+'citation_context_audit.json')]},
 {id:'C06',claim:'Passage matrix',observation:'24 rows comprise 7 bounded locators, 15 explicit bounded-unavailability rows, and 2 metadata-only neighbors. These are record statuses, not complete role proofs.',status:'VERIFIED_RECORD_COUNTS_NOT_ROLE_PROOFS'},
 {id:'C07',claim:'Historical claim inventory',observation:'Phase6 lists 8 precommitted positions. Current B0042 treats this as historical; the new 401-claim registry is a separate population.',status:'VERIFIED_HISTORICAL_INVENTORY'},
 {id:'C08',claim:'Conditional G/I/C',observation:'Only if X_res=X does I have 138 incidences; G and C are projections with distinct cardinalities. Unresolved cases belong to I_diag. No populated output is claimed.',status:'VERIFIED_CONDITIONAL_DEFINITION'},
 {id:'C09',claim:'Fixture and pair logic',observation:'9453 unordered distinct pairs do not test self-pairs, ordered reversal or triples. Independent semantic adjudication remains prospective; three inverse branches are preserved.',status:'VERIFIED_CONDITIONAL_LOGIC'},
 {id:'C10',claim:'Historical reader-manifest binding',observation:'Digest 0b2d2692f93eccd104183aa45381ac461f310c3fdc912906b225ed26cc16be00 describes historical bytes; current text explicitly acknowledges stale matrix descriptor and lack of exact current package reconstruction.',status:'VERIFIED_HISTORICAL_BINDING_AND_LIMIT'},
 {id:'C11',claim:'Scientific execution scope',observation:'Scholar intake is no_experiments_declared at 2026-09-02T16:05:50Z with empty provenance. No implementation, primitive owner computation, independent certificate or scientific experiment is represented as completed.',status:'VERIFIED_SCOPED_NO_EXECUTION_RECORD'},
 {id:'C12',claim:'Description of older originality screen',observation:'Only after the fresh D conclusion, the historical report was consulted to verify the historical sentence: it records 21 ORIGINAL samples / 67 denominator / 10 sections. This is not evidence for the current originality verdict.',status:'VERIFIED_HISTORICAL_REPORT_DESCRIPTION',evidence:bind('notes/stage2_5_integrity_report.json')}
],registered_data_claims:dataRows,issues:[screeningIssue],limits:['No scientific result or full theorem has been verified by these record checks.','Arithmetic and raw-record identity do not establish that the original screening events occurred.','The two E-level access gaps share one underlying C/Mode6 issue; counts are not added twice.']};
output.coverage_candidate_review={paper_id:'P31',draft_raw_sha256:draft.sha256,registry_raw_sha256:coverage.registry_raw_sha256,registered_claim_count:checked,official_candidate_unregistered_count:coverage.candidate_unregistered_count,official_report:bind(r1+'claim_registry_coverage.json'),official_checks:bind(r1+'official_evidence_checks.json'),candidates:coverage.candidates.map(c=>({candidate_id:c.candidate_id,disposition:'NONCLAIM_TEX_ANNOTATION_PERCENT_ENCODING_FALSE_POSITIVE',reason:'The exact line begins % ARS-CITE; 201% and 80% are URI-encoding fragments, not manuscript percentages. Source-use prose and P31-S19 tuple are registered. The official count remains 1; the official report is not edited.'})),semantic_extraction_coverage:'not_machine_detectable'};
output.scope_novelty_advisories={paper_id:'P31',audit_round:4,recovery:2,E4:{status:'completed',scope_source:bind('notes/stage1_phase1_rq_brief.md'),refinements:[bind('notes/stage1_phase6_claim_intent_manifest.json'),bind('notes/stage4_prime_revision_evidence_bundle_round6.json')],claims_checked:checked,effective_scope:'138 registered inputs, 55 groups, positive level-11 time change, oriented primitive Gamma_0(11) ownership, Hecke degree distinct from traversal power, conditional G/I/C, A1-only design. Later approved literature-only architecture does not enlarge the scientific population.',section_fallback:'No current section-to-subquestion map was bound; each section was compared with the whole approved parent scope and later explicit authority.',scope_broadened:[],limit:'Added frontmatter attribution is not a scientific scope extension; it is separately unresolved.'},E5:{status:'completed',claims_checked:checked,novelty_assertions_requiring_classification:[],rationale:'Current text disclaims global priority and exhaustive novelty. Next-test recommendations and architectural judgments are not claims that no previous literature exists. No novelty clearance is emitted.'},claim_standing_requested:false,claim_standing_run:false};
output.failure_mode_audit={paper_id:'P31',audit_round:4,recovery:2,experiment_intake:{status:'no_experiments_declared',declared_by:'scholar',declared_at:'2026-09-02T16:05:50Z',experiment_provenance:[]},all_seven_explicitly_rechecked:true,modes:[
 {mode:1,name:'Implementation bug passing AI self-review',status:'CLEAR',evidence:'No scientific code/result exists in the declared intake or current asserted output. Canonicalizer, all-pairs and fixtures are proposed.',limit:'No correctness certificate for a future solver.'},
 {mode:2,name:'Hallucinated citation',status:'CLEAR',evidence:'Recovery1 ordinary original-source/author/publisher pages establish all 24 work identities. All 26 modest current contexts were compared. S03/S22 DOI fields remain UNVERIFIABLE_ACCESS, not NOT_FOUND or fabricated works.',limit:'No full theorem verification, clean retraction screen or clearance of unavailable metadata.'},
 {mode:3,name:'Hallucinated experimental result',status:'CLEAR',evidence:'No experiments declared; current no-solver/no-owner-result qualifiers preserved. Frozen 138/55 and 9453 are inputs and arithmetic.',limit:'Original literature execution evidence gap is recorded separately as Mode6.'},
 {mode:4,name:'Shortcut reliance',status:'CLEAR',evidence:'No trained-model outcome comparison. The text expressly denies that byte-derived pair agreement supplies independent semantic truth; future target-blind adjudication remains required.',limit:'Future adjudicator robustness is untested.'},
 {mode:5,name:'Implementation bug reframed as novel insight',status:'CLEAR',evidence:'No debugging surprise or computed phenomenon is represented as new science; proposed architecture disclaims result/theorem/novelty.',limit:'Mathematical feasibility is not established.'},
 {mode:6,name:'Methodology fabrication / execution correspondence',status:'INSUFFICIENT EVIDENCE',evidence:screeningIssue.actual,limit:'Unavailable original evidence is not a finding that events were fabricated. The current caveat is recognized.',checkpoint_effect:'block pending exact protocol-compliant resolution; no override inferred'},
 {mode:7,name:'Early frame-lock',status:'CLEAR',evidence:'All 57 operations across 6 rounds were semantically checked against exact authority. Approved canonicalizer reframing stays conditional; unresolved replaces unsupported negative answers.',limit:'Approved reframing does not establish theorem feasibility.'}
],evidence:[bind(r1+'reference_audit.json'),bind(r1+'citation_context_audit.json'),bind(r1+'semantic_claim_review.json'),bind(r0+'e6_semantic_audit.json')],overall_checkpoint_effect:'block_due_to_Mode6_insufficient_execution_evidence',user_override:null};
const authorIssues=semantic.claim_decisions.filter(x=>x.verdict==='UNVERIFIABLE');
const accessIssues=semantic.claim_decisions.filter(x=>x.verdict==='UNVERIFIABLE_ACCESS');
output.compliance_report={mode:'primary_research',stage:'4.5',generated_at:now,prisma_trAIce:null,raise:{mode:'principles_only',principles:{human_oversight:'warn',transparency:'warn',reproducibility:'warn',fit_for_purpose:'pass'},principle_evidence:{human_oversight:['notes/stage1_phase6_claim_intent_manifest.json: named responsible human and recorded design approvals, not authenticated personal acts.','notes/stage4_prime_revision_round6.tex B0003/B0102/B0103: [MATERIAL GAP: human_oversight] frontmatter and two author-owned declarations remain unconfirmed. B0108 denies source-level reading attestation.'],transparency:['notes/stage4_prime_revision_round6.tex B0107/B0108 explicitly limits available AI metadata and source verification; no complete tool chronology or backend version is inferred.','BATCH_ROUND10_STAGE4_5_ROUND4_RECOVERY1_QUARANTINE_MANIFEST.json and RECOVERY2_RESUMPTION_RECEIPT.json preserve the API-boundary incident, contaminated predecessors and later validation stop; no retroactive authority.'],reproducibility:['notes/stage4_5_round4_recovery1_official_evidence_checks.json binds exact 401-claim coverage and 403-row replay; reproducible checks are not evidence that an original search occurred.','notes/stage4_prime_revision_round6.tex B0079/B0105 recognizes the historical manifest is not exact current-package reconstruction. [MATERIAL GAP: reproducibility] original screening event rows remain unavailable.'],fit_for_purpose:['notes/stage1_phase1_rq_brief.md and notes/stage1_phase6_claim_intent_manifest.json bind a finite literature-only conditional architecture, not an implemented owner theorem.','notes/stage4_5_round4_recovery1_semantic_claim_review.json and notes/stage4_5_round4_e6_semantic_audit.json verify preservation of current conditional/scoped wording, not scientific feasibility.']},block_decision:'warn'},overall_decision:'block',user_action_required:true,evidence:['Non-SR primary_research / principles_only was explicitly locked; the RAISE contribution is capped at warn, not promoted into an SR checklist.','Independent integrity FAIL: three UNVERIFIABLE author-owned/metadata claims, two access-limited historical-execution claims, two DOI-field access gaps, and Mode6 insufficient evidence. No user override or new author attestation exists.','Historical ADV-E6-1 was introduced at R3 operation 13, inherited in R4/R5 and textually restored in R6. The root checkpoint must route the new exact finding set; no duplicate restoration or inherited disposition is synthesized.']};
output.compliance_selfcheck={paper_id:'P31',generated_at:now,CA_1:'PASS: no PRISMA items quoted; non-SR branch explicitly locked.',CA_2:'PASS: principles-only contribution warn; independent integrity and Mode6 aggregate block.',CA_3:'NOT_APPLICABLE: not systematic review.',CA_4:'PASS: fit_for_purpose is the sole pass and has named evidence; other principles are warn with explicit gaps.',upstream_freshness:'No live upstream comparison was performed in this restricted scope; optional upstream_sync_status is omitted, not asserted current.'};
output.integrity_report={verdict:'FAIL',mode:'final-check',phases:{A_references:{checked:A.checked,passed:A.identity_verified,failed:0,issues:A.rows.filter(x=>x.doi_field_status==='UNVERIFIABLE_ACCESS').map(x=>({ref_id:x.id,issue_type:'UNVERIFIABLE_ACCESS_DOI_FIELD',severity:'MEDIUM',detail:'Work identity is positively established. The exact DOI field '+x.fields.doi+' was not independently bound on an accessible primary page. This is not work NOT_FOUND, a wrong DOI finding, or evidence of fabrication.'}))},B_citation_context:{sampled:B.sampled,verified:B.verified,issues:[]},C_data:{claims_checked:dataRows.length,verified:dataRows.filter(x=>x.verdict==='VERIFIED').length,issues:[screeningIssue]},D_originality:{checked:true,issues:[]},E_claims:{checked,verified,distortions:[...authorIssues,...accessIssues].map(d=>({claim:registry.claims.find(c=>c.claim_id===d.claim_id).claim_text,source:d.evidence_basis.join('; '),verdict:d.verdict,detail:d.claim_id+': '+d.detail})),claim_registry_coverage:{status:'completed',registry_schema_version:'claim-registry/1.0',report_path:base+r1+'claim_registry_coverage.json',report_sha256:bind(r1+'claim_registry_coverage.json').sha256,draft_raw_sha256:coverage.draft_raw_sha256,registry_raw_sha256:coverage.registry_raw_sha256,candidate_unregistered_count:coverage.candidate_unregistered_count,semantic_extraction_coverage:'not_machine_detectable'},evidence_rows:rows,claim_strength_drift_findings:{schema_version:'claim-strength-drift-findings/1.0',artifact_path:base+r0+'claim_strength_drift_findings.json',artifact_sha256:bind(r0+'claim_strength_drift_findings.json').sha256}}},overall_issues:{SERIOUS:3,MEDIUM:3,MINOR:0},citation_integrity_score:1.0,fabrication_risk_score:0.0,timestamp:now};
output.report_interpretation={paper_id:'P31',current_draft:draft,verdict:'FAIL',issue_counting:'3 SERIOUS claim-level gaps: new compound frontmatter, preserved funding, preserved competing interests. 3 MEDIUM issue groups: two source DOI fields and one original-screening provenance gap affecting two E claims. C and E manifestations are not double-counted. Historical E6 is retained separately, not counted as a present every/any textual defect.',score_limits:{citation_integrity_score:'1.0 = 24/24 identified works and 26/26 bounded current citation contexts, not complete DOI-field accuracy or full theorem support. Two metadata fields remain unavailable.',fabrication_risk_score:'0.0 reports no actually detected fabricated work or scientific result in this bounded audit; it is not a probability, uncertainty estimate, author clearance or claim that unresolved facts are true.'},D_scope:{body_denominator:D.body_denominator,body_sampled:D.body_sampled,body_coverage_percent:D.body_coverage_percent,changed_content_blocks:D.changed_content_blocks,changed_content_checked:D.changed_content_checked,searches_executed:D.searches_executed,professional_detector_used:false,self_plagiarism_limit:D.D2_author_candidates.limit,originality_limit:'No identifiable copying in returned exact/paraphrase fragments. Not global plagiarism or novelty clearance.'},E_scope:{registered:checked,checked,verified,evidence_rows:rows.length,unverifiable:authorIssues.length,unverifiable_access:accessIssues.length,mechanical_candidates:coverage.candidate_unregistered_count,semantic_extraction_coverage:'not_machine_detectable'},E6_scope:{rounds:E6.rounds_checked,operations:E6.operations_checked,historical_finding:'ADV-E6-1 R3 op13 any→every, inherited R4/R5, restored R6 under exact authorization. New finding bytes require root checkpoint routing; no author disposition minted.'},final_schema5_schema12:'Root-owned final validation is not yet represented as run by this producer.',scientific_execution:false,canonical_writes:false,stage5_authorized:false};
const name=process.argv[2];if(!Object.hasOwn(output,name))throw Error('Unknown named output');
const rendered=JSON.stringify(output[name],null,2)+'\n';
if(process.argv[3]!==undefined){const off=Number(process.argv[3]);console.log(JSON.stringify({total:rendered.length,offset:off,chunk:rendered.slice(off,off+16000)}));}else console.log(rendered);
