#!/usr/bin/env python3
"""Producer-independent strict checker for HCS-C327."""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from fractions import Fraction
from pathlib import Path

import mpmath as mp
import yaml


ROOT = Path(__file__).resolve().parents[1]
EVIDENCE = ROOT / "results/c327_kronig_penney_evidence.json"
EVALUATION = ROOT / "evaluations/route_a/HCS-C327/2026-09-03.yaml"
SOURCE = "1aba1f6fd0cf81baa7c137a2ce7ce3d097ba63fc"
EVALUATOR = "6f13fc94be84eaf22c518dd0c530e442cd625f3cdcb9d3d34e67cc11c881194c"
SCOPE = "NO_BAD_EULER_OR_ROOT_NUMBER"
EVALUATION_RAW_SHA256 = "d20325d6c1b58e2a44520440111543020b113ab806964a49d94e1742529befb1"
EVALUATION_SEMANTIC_SHA256 = "3bd209b81c1ec9ab135121e25a01048e258021e6a8bbf64aad0d3c54ae986faa"
mp.mp.dps = 100

FLAGS = {
    "claims_target_arithmetic_local_data": False,
    "claims_target_euler_factors": False,
    "claims_root_number": False,
    "claims_automorphy": False,
    "claims_target_divisor_or_counting_law": False,
    "claims_target_functional_equation": False,
    "claims_target_zero_match": False,
    "claims_hilbert_polya_operator": False,
    "invokes_route_b": False,
}
Q_VALUES = [Fraction(-8), Fraction(-6), Fraction(-4), Fraction(-3), Fraction(-1),
            Fraction(1), Fraction(3), Fraction(4), Fraction(8)]
MODEL = {
    "operator": "H=-d^2/dx^2+g sum_{n in Z} delta(x-na)",
    "domain": "a>0 and g real",
    "jump": "psi continuous and psi'(na+)-psi'(na-)=g psi(na)",
    "dimensionless_coupling": "q=ga",
    "dimensionless_energy": "z=Ea^2",
    "discriminant": "Delta=cos(ka)+g sin(ka)/(2k), continuously continued through E=0",
    "clock": "physical unitary time generated by the self-adjoint form owner",
}
THEOREM = {
    "operator_owner": "the H1 quadratic form is closed and lower semibounded and its operator has the stated point-interaction matching conditions",
    "floquet_spectrum": "spectrum iff abs(Delta(E))<=1; it is purely absolutely continuous",
    "multiplicity": "band interiors have full-line Bloch multiplicity two; nonzero-g edges are simple periodic or antiperiodic fibre edges; g=0 Bragg contacts are double",
    "negative_atlas": "for g<0 the plus edge is h=2y tanh(y/2); a minus edge exists iff -ga>4, with ga=-4 the exact zero threshold",
    "positive_atlas": "nonfixed Bragg partners satisfy ga=2x tan((x-npi)/2); their side is the sign of g and every nonzero-g Bragg gap is open",
    "gap_asymptotic": "the nth high-energy gap has width 2abs(g)/a+O_{ga}(n^-2/a^2)",
    "ids_dos": "on band j, N=(j+acos((-1)^j Delta)/pi)/a and density=abs(Delta_E')/(pi*a*sqrt(1-Delta^2)); N is constant in gaps",
}
REFERENCES = [
    {"identifier": "10.1098/rspa.1931.0019", "role": "original periodic crystal band-model owner"},
    {"identifier": "10.1090/chel/350", "role": "authoritative point-interaction operator reference"},
    {"identifier": "math/0109129", "role": "pure absolute continuity for periodic singular potentials"},
]
COLLISIONS = {
    "C288": "one isolated point interaction and scattering/resolvent data, not an infinite periodic delta comb with Bloch bands",
    "C308": "non-Hermitian Hatano--Nelson lattice transport, not a self-adjoint continuum singular periodic operator",
    "C318": "finite-range dimerized SSH bulk--edge topology, not a continuum equal-spacing delta-comb band atlas",
    "C323": "finite complete-graph oracle search, not an infinite-volume Floquet Hamiltonian",
}
NONCLAIMS = [
    "No literature-priority claim is made for the Kronig--Penney dispersion, point-interaction realization, or Floquet theory.",
    "The determinant-one transfer matrix is not an Euler factor and Bloch energies are not target zeros.",
    "No target arithmetic datum, root number, automorphy, target divisor, functional equation, Hilbert--Polya operator, or Route-B input is claimed.",
]
EVALUATION_KEYS = {
    "schema", "candidate_id", "title", "evaluation_date", "source_commit", "fixed_epoch",
    "scope_literal", "evaluator_authority", "evaluator_version", "evaluator_authority_sha256",
    "obstruction_id", "candidate_definition", "family", "phase_space", "dynamics", "parameters",
    "parameter_provenance", "arithmetic_origin", "clock", "normalization", "determinant_convention",
    "orbit_cutoff", "precision", "training_data", "forbidden_data", "artifact_paths",
    "a0", "a1", "a2", "a3", "a4", "tuple", "overall_verdict",
    "route_b_invocation_allowed", "route_b_lock_reason", "scope_flags", "theorem_status",
    "finite_evidence_role", "source_owner_tokens",
}
GATES = {
    "a0": ("A0_FAIL", "PROVED"), "a1": ("A1_WEAK", "PROVED"),
    "a2": ("A2_FAIL", "STOP_SCOPED"), "a3": ("A3_FAIL", "STOP_SCOPED"),
    "a4": ("A4_NATURAL_QUANTIZATION", "PROVED"),
}


class UniqueLoader(yaml.SafeLoader):
    pass


UniqueLoader.yaml_implicit_resolvers = {
    key: [(tag, regexp) for tag, regexp in values if tag != "tag:yaml.org,2002:timestamp"]
    for key, values in yaml.SafeLoader.yaml_implicit_resolvers.items()
}


def unique_mapping(loader, node, deep=False):
    result = {}
    for key_node, value_node in node.value:
        if key_node.tag == "tag:yaml.org,2002:merge":
            raise ValueError("YAML merge forbidden")
        key = loader.construct_object(key_node, deep=deep)
        if type(key) is not str or key in result:
            raise ValueError("duplicate or non-string YAML key")
        result[key] = loader.construct_object(value_node, deep=deep)
    return result


UniqueLoader.add_constructor(yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, unique_mapping)


def duplicate_pairs(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError("duplicate JSON key")
        result[key] = value
    return result


def strict_json(path: Path):
    value = json.loads(
        path.read_text(), object_pairs_hook=duplicate_pairs,
        parse_constant=lambda token: (_ for _ in ()).throw(ValueError(f"nonfinite {token}")),
    )
    if type(value) is not dict:
        raise TypeError("JSON root must be object")
    return value


def strict_yaml(path: Path):
    raw = path.read_text()
    for token in yaml.scan(raw):
        if isinstance(token, (yaml.tokens.AnchorToken, yaml.tokens.AliasToken)):
            raise ValueError("YAML aliases forbidden")
    value = yaml.load(raw, Loader=UniqueLoader)
    if type(value) is not dict:
        raise TypeError("YAML root must be object")
    return value


def sha(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


def semantic_hash(value) -> str:
    return sha(json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode())


def payload_hash(data: dict) -> str:
    body = dict(data)
    body.pop("payload_sha256", None)
    return sha(json.dumps(body, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode())


def qstr(value: Fraction) -> str:
    return str(value.numerator) if value.denominator == 1 else f"{value.numerator}/{value.denominator}"


def frac(value) -> Fraction:
    if type(value) is not str:
        raise TypeError("rational must be a string")
    result = Fraction(value)
    if qstr(result) != value:
        raise ValueError("noncanonical rational")
    return result


def mpq(value: Fraction) -> mp.mpf:
    return mp.mpf(value.numerator) / value.denominator


def leaves(value) -> int:
    if type(value) is dict:
        return sum(leaves(item) for item in value.values())
    if type(value) is list:
        return sum(leaves(item) for item in value)
    return 1


CHECKS = 0


def need(condition: bool, label: str) -> None:
    global CHECKS
    CHECKS += 1
    if not condition:
        raise AssertionError(label)


def keys(value, expected, label: str) -> None:
    need(type(value) is dict and set(value) == set(expected), label)


def exact(value, expected, label: str) -> None:
    need(type(value) is dict and value == expected, label)


def near(value, expected, label: str, tolerance=mp.mpf("1e-65")) -> None:
    if type(value) is not str:
        raise TypeError(f"{label}: decimal must be string")
    got = mp.mpf(value)
    need(mp.isfinite(got) and abs(got - expected) <= tolerance * max(1, abs(expected)), label)


def delta(z: mp.mpf, coupling: mp.mpf) -> mp.mpf:
    if z > 0:
        x = mp.sqrt(z)
        return mp.cos(x) + coupling * mp.sin(x) / (2 * x)
    if z < 0:
        y = mp.sqrt(-z)
        return mp.cosh(y) + coupling * mp.sinh(y) / (2 * y)
    return 1 + coupling / 2


def ddelta(z: mp.mpf, coupling: mp.mpf) -> mp.mpf:
    if z > 0:
        x = mp.sqrt(z)
        return -mp.sin(x) / (2 * x) + coupling * (x * mp.cos(x) - mp.sin(x)) / (4 * x**3)
    if z < 0:
        y = mp.sqrt(-z)
        return -(mp.sinh(y) + coupling * (y * mp.cosh(y) - mp.sinh(y)) / (2 * y**2)) / (2 * y)
    return -mp.mpf("0.5") - coupling / 12


def root_from_receipt(value, function, target, left, right, label):
    root = mp.mpf(value)
    need(left <= root <= right, f"{label} interval")
    need(abs(function(root) - target) < mp.mpf("2e-67") * max(1, abs(target)), f"{label} equation")
    return root


def main() -> None:
    if sys.flags.optimize:
        raise RuntimeError("C327 checker refuses optimized Python")
    parser = argparse.ArgumentParser()
    parser.add_argument("--evidence", type=Path, default=EVIDENCE)
    parser.add_argument("--evaluation", type=Path, default=EVALUATION)
    args = parser.parse_args()
    data = strict_json(args.evidence)
    evaluation = strict_yaml(args.evaluation)

    top = {
        "schema", "candidate_id", "obstruction_id", "source_commit", "fixed_epoch", "scope_literal",
        "evaluator", "evaluation", "model", "theorem_contract", "references", "collision_boundary",
        "nonclaims", "route_a", "scope_flags", "parameter_grid", "negative_atlas_rows",
        "low_edge_rows", "bragg_rows", "transfer_rows", "ids_dos_rows", "enumeration", "payload_sha256",
    }
    keys(data, top, "top schema")
    need(data["schema"] == "hcs-c327-kronig-penney-v1", "schema")
    need(data["candidate_id"] == "HCS-C327" and data["obstruction_id"] == "HEN-O311", "identity")
    need(data["source_commit"] == SOURCE and data["fixed_epoch"] == 1788393600, "provenance")
    need(data["scope_literal"] == SCOPE, "scope")
    exact(data["evaluator"], {
        "authority": "flow_systems/skills/route-a-evaluator.md",
        "version": "0.2.0", "sha256": EVALUATOR,
    }, "evaluator")
    exact(data["model"], MODEL, "model")
    exact(data["theorem_contract"], THEOREM, "theorem")
    need(data["references"] == REFERENCES, "references")
    exact(data["collision_boundary"], COLLISIONS, "collisions")
    need(data["nonclaims"] == NONCLAIMS, "nonclaims")
    exact(data["scope_flags"], FLAGS, "flags")
    exact(data["route_a"], {
        "tuple": ["A0_FAIL", "A1_WEAK", "A2_FAIL", "A3_FAIL", "A4_NATURAL_QUANTIZATION"],
        "overall": "ROUTE_A_REJECTED", "route_b_invocation_allowed": False,
    }, "route A")
    need(payload_hash(data) == data["payload_sha256"], "payload hash")

    raw = args.evaluation.read_bytes()
    need(sha(raw) == EVALUATION_RAW_SHA256, "YAML raw hash")
    need(semantic_hash(evaluation) == EVALUATION_SEMANTIC_SHA256, "YAML semantic hash")
    exact(data["evaluation"], {
        "path": "evaluations/route_a/HCS-C327/2026-09-03.yaml",
        "raw_sha256": EVALUATION_RAW_SHA256, "semantic_sha256": EVALUATION_SEMANTIC_SHA256,
    }, "evidence YAML lock")
    keys(evaluation, EVALUATION_KEYS, "YAML schema")
    need(evaluation["schema"] == "route-a-evaluation-v0.2.0", "YAML schema literal")
    need(evaluation["candidate_id"] == "HCS-C327" and evaluation["obstruction_id"] == "HEN-O311", "YAML identity")
    need(evaluation["source_commit"] == SOURCE and evaluation["fixed_epoch"] == 1788393600, "YAML provenance")
    need(evaluation["scope_literal"] == SCOPE, "YAML scope")
    need(evaluation["evaluator_authority"] == "flow_systems/skills/route-a-evaluator.md", "YAML authority")
    need(evaluation["evaluator_version"] == "0.2.0" and evaluation["evaluator_authority_sha256"] == EVALUATOR, "YAML evaluator")
    for gate, (verdict, status) in GATES.items():
        keys(evaluation[gate], {"verdict", "evidence_status", "strongest_evidence", "strongest_failure"}, f"YAML {gate} keys")
        need(evaluation[gate]["verdict"] == verdict and evaluation[gate]["evidence_status"] == status, f"YAML {gate}")
    need(evaluation["tuple"] == data["route_a"]["tuple"], "YAML tuple")
    need(evaluation["overall_verdict"] == "ROUTE_A_REJECTED", "YAML verdict")
    need(evaluation["route_b_invocation_allowed"] is False, "YAML Route B")
    exact(evaluation["scope_flags"], FLAGS, "YAML flags")
    need(evaluation["theorem_status"] == "PROVABLE_AS_STATED", "YAML theorem")
    need(evaluation["source_owner_tokens"] == ["10.1098/rspa.1931.0019", "10.1090/chel/350", "math/0109129"], "YAML sources")

    grid = {
        "q_values": [qstr(value) for value in Q_VALUES],
        "negative_q_values": ["-8", "-6", "-4", "-3", "-1"],
        "bragg_n": "1..24", "transfer_a": ["1/2", "1", "2"],
        "transfer_scaled_energy": ["-4", "0", "1", "pi_squared", "9pi_squared/4"],
        "ids_band_index": "0..6",
    }
    exact(data["parameter_grid"], grid, "grid")

    negative_keys = {"q_equals_ga", "h_equals_minus_ga", "delta_at_zero", "zero_location", "y_plus",
                     "plus_edge_residual", "y_minus", "minus_edge_residual", "negative_band_lower_scaled_energy",
                     "negative_band_upper_scaled_energy", "negative_gap_to_zero"}
    expected_negative = [value for value in Q_VALUES if value < 0]
    need(len(data["negative_atlas_rows"]) == len(expected_negative), "negative count")
    negative_edges = {}
    for row, coupling in zip(data["negative_atlas_rows"], expected_negative):
        keys(row, negative_keys, "negative row keys")
        h = -coupling
        need(frac(row["q_equals_ga"]) == coupling and frac(row["h_equals_minus_ga"]) == h, "negative q")
        need(frac(row["delta_at_zero"]) == 1 + coupling / 2, "zero delta")
        location = "BAND_INTERIOR" if h < 4 else ("BAND_EDGE_MINUS" if h == 4 else "GAP")
        need(row["zero_location"] == location and row["negative_gap_to_zero"] is (h > 4), "negative class")
        yp = root_from_receipt(row["y_plus"], lambda y: 2*y*mp.tanh(y/2), mpq(h), 0, mpq(h)+2, "y plus")
        near(row["plus_edge_residual"], 0, "plus residual")
        near(row["negative_band_lower_scaled_energy"], -yp**2, "negative lower")
        ym = None
        if h > 4:
            ym = root_from_receipt(row["y_minus"], lambda y: 2*y/mp.tanh(y/2), mpq(h), 0, yp, "y minus")
            near(row["minus_edge_residual"], 0, "minus residual")
            near(row["negative_band_upper_scaled_energy"], -ym**2, "negative upper")
            need(ym < yp, "negative edge order")
        else:
            need(row["y_minus"] is None and row["minus_edge_residual"] is None, "minus absent")
            near(row["negative_band_upper_scaled_energy"], 0, "negative reaches zero")
        negative_edges[coupling] = (yp, ym)

    low_keys = {"q_equals_ga", "kind", "positive_edge_x", "scaled_energy", "equation_residual"}
    need(len(data["low_edge_rows"]) == len(Q_VALUES), "low count")
    low_edges = {}
    for row, coupling in zip(data["low_edge_rows"], Q_VALUES):
        keys(row, low_keys, "low row keys")
        need(frac(row["q_equals_ga"]) == coupling, "low q")
        if coupling > 0:
            want_kind, n, left, right = "REPULSIVE_POSITIVE_BOTTOM", 0, 0, mp.pi
        elif coupling > -4:
            want_kind, n, left, right = "ATTRACTIVE_ZERO_CONNECTED_UPPER", 1, 0, mp.pi
        elif coupling == -4:
            want_kind, n, left, right = "ZERO_ANTIPERIODIC_THRESHOLD", 1, 0, 0
        else:
            want_kind, n, left, right = "STRONG_ATTRACTION_NO_FIRST_POSITIVE_SHIFTED_EDGE", 1, 0, 0
        need(row["kind"] == want_kind, "low kind")
        if coupling < -4:
            need(row["positive_edge_x"] is None and row["scaled_energy"] is None and row["equation_residual"] is None, "low absent")
            low_edges[coupling] = None
        else:
            edge = mp.mpf(row["positive_edge_x"])
            need(left <= edge <= right, "low interval")
            if coupling == -4:
                need(edge == 0, "zero threshold edge")
            else:
                need(abs(2*edge*mp.tan((edge-n*mp.pi)/2)-mpq(coupling)) < mp.mpf("2e-66"), "low equation")
            near(row["scaled_energy"], edge**2, "low energy")
            near(row["equation_residual"], 0, "low residual")
            low_edges[coupling] = edge

    bragg_keys = {"q_equals_ga", "n", "fixed_edge_x", "fixed_discriminant", "shifted_edge_exists",
                  "shifted_edge_x", "side", "edge_equation_residual", "scaled_gap_width",
                  "positive_axis_gap_portion", "n_squared_width_error", "gap_open"}
    need(len(data["bragg_rows"]) == len(Q_VALUES) * 24, "bragg count")
    bragg_edges = {}
    cursor = 0
    for coupling in Q_VALUES:
        for n in range(1, 25):
            row = data["bragg_rows"][cursor]
            cursor += 1
            keys(row, bragg_keys, "bragg keys")
            need(frac(row["q_equals_ga"]) == coupling and row["n"] == n, "bragg index")
            fixed = n * mp.pi
            near(row["fixed_edge_x"], fixed, "fixed x")
            need(row["fixed_discriminant"] == ((-1) ** n), "fixed delta")
            absent = coupling < -4 and n == 1
            need(row["shifted_edge_exists"] is (not absent), "shift existence")
            need(row["gap_open"] is True, "gap open")
            if absent:
                need(row["shifted_edge_x"] is None and row["edge_equation_residual"] is None, "absent shifted")
                need(row["side"] == "NONPOSITIVE_THRESHOLD", "absent side")
                need(row["scaled_gap_width"] is None, "full first gap not misreported")
                near(row["positive_axis_gap_portion"], fixed**2, "positive gap component")
                need(row["n_squared_width_error"] is None, "absent error")
                bragg_edges[(coupling, n)] = None
                continue
            edge = mp.mpf(row["shifted_edge_x"])
            left, right = ((fixed, (n+1)*mp.pi) if coupling > 0 else ((n-1)*mp.pi, fixed))
            need(left <= edge <= right, "shifted interval")
            if coupling == -4 and n == 1:
                need(edge == 0, "Bragg zero threshold")
            else:
                need(abs(2*edge*mp.tan((edge-fixed)/2)-mpq(coupling)) < mp.mpf("2e-66"), "edge equation")
            near(row["edge_equation_residual"], 0, "edge residual")
            width = abs(edge**2-fixed**2)
            near(row["scaled_gap_width"], width, "gap width")
            need(row["positive_axis_gap_portion"] is None, "positive portion absent")
            side = "RIGHT" if coupling > 0 else ("ZERO_THRESHOLD" if coupling == -4 and n == 1 else "LEFT")
            need(row["side"] == side, "edge side")
            if n >= 2:
                near(row["n_squared_width_error"], n*n*(width-2*abs(mpq(coupling))), "scaled width error")
            else:
                need(row["n_squared_width_error"] is None, "first error absent")
            bragg_edges[(coupling, n)] = edge

    transfer_keys = {"a", "q_equals_ga", "scaled_energy", "g", "energy", "m00", "m01", "m10", "m11",
                     "determinant", "half_trace", "closed_formula", "in_spectrum"}
    energy_map = {"-4": -mp.mpf(4), "0": mp.mpf(0), "1": mp.mpf(1),
                  "pi_squared": mp.pi**2, "9pi_squared/4": 9*mp.pi**2/4}
    need(len(data["transfer_rows"]) == 3*10*5, "transfer count")
    cursor = 0
    for spacing in map(Fraction, (Fraction(1,2), 1, 2)):
        av = mp.mpf(spacing.numerator)/spacing.denominator
        for coupling in Q_VALUES + [Fraction(0)]:
            gv = mp.mpf(coupling.numerator)/coupling.denominator/av
            for token in energy_map:
                row = data["transfer_rows"][cursor]
                cursor += 1
                keys(row, transfer_keys, "transfer keys")
                need(frac(row["a"]) == spacing and frac(row["q_equals_ga"]) == coupling, "transfer parameters")
                need(row["scaled_energy"] == token and frac(row["g"]) == coupling/spacing, "transfer energy key")
                z = energy_map[token]
                energy = z/av**2
                near(row["energy"], energy, "physical energy")
                if z > 0:
                    k=mp.sqrt(energy); c=mp.cos(k*av); s=mp.sin(k*av)
                    p00,p01,p10,p11=c,s/k,-k*s,c
                elif z < 0:
                    k=mp.sqrt(-energy); c=mp.cosh(k*av); s=mp.sinh(k*av)
                    p00,p01,p10,p11=c,s/k,k*s,c
                else:
                    p00,p01,p10,p11=mp.mpf(1),av,mp.mpf(0),mp.mpf(1)
                matrix=(p00,p01,gv*p00+p10,gv*p01+p11)
                for field, expected in zip(("m00","m01","m10","m11"), matrix):
                    near(row[field], expected, f"transfer {field}")
                determinant=matrix[0]*matrix[3]-matrix[1]*matrix[2]
                half=(matrix[0]+matrix[3])/2
                near(row["determinant"], 1, "transfer determinant")
                near(row["half_trace"], half, "transfer trace")
                near(row["closed_formula"], delta(z, mpq(coupling)), "discriminant formula")
                need(row["in_spectrum"] is (abs(half) <= 1+mp.mpf("1e-80")), "spectrum flag")

    ids_keys = {"q_equals_ga", "band_index", "lower_scaled_energy", "upper_scaled_energy", "mid_scaled_energy",
                "delta_mid", "delta_prime_scaled_energy", "unwrapped_phase", "ids_per_unit_length_at_a_one",
                "dos_per_unit_length_at_a_one"}
    need(len(data["ids_dos_rows"]) == 10*7, "IDS count")
    cursor=0
    for coupling in Q_VALUES+[Fraction(0)]:
        cv=mpq(coupling)
        for index in range(7):
            row=data["ids_dos_rows"][cursor]; cursor+=1
            keys(row,ids_keys,"IDS keys")
            need(frac(row["q_equals_ga"])==coupling and row["band_index"]==index,"IDS index")
            lower=mp.mpf(row["lower_scaled_energy"]); upper=mp.mpf(row["upper_scaled_energy"])
            need(lower<upper,"band nonempty")
            if coupling>0:
                edge=low_edges[coupling] if index==0 else bragg_edges[(coupling,index)]
                expected_lower=edge**2; expected_upper=((index+1)*mp.pi)**2
            elif coupling==0:
                expected_lower=(index*mp.pi)**2; expected_upper=((index+1)*mp.pi)**2
            elif index==0:
                yp,ym=negative_edges[coupling]; expected_lower=-yp**2
                expected_upper=(low_edges[coupling]**2 if coupling>-4 else (mp.mpf(0) if coupling==-4 else -ym**2))
            else:
                expected_lower=(index*mp.pi)**2; expected_upper=bragg_edges[(coupling,index+1)]**2
            need(abs(lower-expected_lower)<mp.mpf("3e-67")*max(1,abs(expected_lower)),"band lower")
            need(abs(upper-expected_upper)<mp.mpf("3e-67")*max(1,abs(expected_upper)),"band upper")
            middle=(lower+upper)/2
            near(row["mid_scaled_energy"],middle,"band middle")
            dv=delta(middle,cv); derivative=ddelta(middle,cv)
            need(abs(dv)<1,"mid inside")
            near(row["delta_mid"],dv,"mid delta")
            near(row["delta_prime_scaled_energy"],derivative,"mid derivative")
            phase=mp.acos(((-1)**index)*dv)
            near(row["unwrapped_phase"],index*mp.pi+phase,"phase")
            near(row["ids_per_unit_length_at_a_one"],index+phase/mp.pi,"IDS")
            near(row["dos_per_unit_length_at_a_one"],abs(derivative)/(mp.pi*mp.sqrt(1-dv**2)),"DOS")

    enumeration=data["enumeration"]
    keys(enumeration,{"negative_atlas_rows","low_edge_rows","bragg_rows","transfer_rows","ids_dos_rows","audited_leaf_count"},"enumeration keys")
    need(enumeration["negative_atlas_rows"]==5 and enumeration["low_edge_rows"]==9,"enumeration low")
    need(enumeration["bragg_rows"]==216 and enumeration["transfer_rows"]==150 and enumeration["ids_dos_rows"]==70,"enumeration main")
    need(enumeration["audited_leaf_count"]==leaves(data),"leaf count")
    print(f"C327 independent Kronig--Penney checker: PASS {CHECKS} checks")


if __name__ == "__main__":
    main()
