#!/usr/bin/env python3
"""Deterministic Round-2 word-ball ledger for a level-(3) Bianchi subgroup.

This program deliberately enumerates only the word ball in the subgroup
generated by four elementary level-(3) matrices.  It does not claim that this
generator set is all of Gamma((3)), that the word ball is a conjugacy-class
fundamental domain, or that a row owns a Gaussian/rational prime.
"""

from __future__ import annotations

import argparse
import cmath
import csv
import hashlib
import io
import json
import math
from collections import Counter
from pathlib import Path
from typing import Iterable


Gaussian = tuple[int, int]
Matrix = tuple[Gaussian, Gaussian, Gaussian, Gaussian]
Word = tuple[str, ...]

ZERO: Gaussian = (0, 0)
ONE: Gaussian = (1, 0)
I_GAUSSIAN: Gaussian = (0, 1)
IDENTITY: Matrix = (ONE, ZERO, ZERO, ONE)

MAX_WORD_LENGTH = 5
SHUFFLE_SEED_LABEL = "P24-2026-08-27-target-free-holonomy-shuffle-v1"
COMPLETENESS_BOUNDARY = (
    "ELEMENTARY_GENERATED_SUBGROUP_REDUCED_WORD_BALL_LE_5;"
    "NOT_FULL_GAMMA3;NOT_FULL_CONJUGACY_ENUMERATION"
)


def g_add(x: Gaussian, y: Gaussian) -> Gaussian:
    return (x[0] + y[0], x[1] + y[1])


def g_neg(x: Gaussian) -> Gaussian:
    return (-x[0], -x[1])


def g_mul(x: Gaussian, y: Gaussian) -> Gaussian:
    return (x[0] * y[0] - x[1] * y[1], x[0] * y[1] + x[1] * y[0])


def g_square(x: Gaussian) -> Gaussian:
    return g_mul(x, x)


def g_mod3(x: Gaussian) -> Gaussian:
    return (x[0] % 3, x[1] % 3)


def g_to_text(x: Gaussian) -> str:
    a, b = x
    if b == 0:
        return str(a)
    if a == 0:
        return "i" if b == 1 else "-i" if b == -1 else f"{b}i"
    sign = "+" if b > 0 else "-"
    coeff = "" if abs(b) == 1 else str(abs(b))
    return f"{a}{sign}{coeff}i"


def mat_mul(a: Matrix, b: Matrix) -> Matrix:
    a00, a01, a10, a11 = a
    b00, b01, b10, b11 = b
    return (
        g_add(g_mul(a00, b00), g_mul(a01, b10)),
        g_add(g_mul(a00, b01), g_mul(a01, b11)),
        g_add(g_mul(a10, b00), g_mul(a11, b10)),
        g_add(g_mul(a10, b01), g_mul(a11, b11)),
    )


def mat_det(a: Matrix) -> Gaussian:
    return g_add(g_mul(a[0], a[3]), g_neg(g_mul(a[1], a[2])))


def mat_trace(a: Matrix) -> Gaussian:
    return g_add(a[0], a[3])


def mat_inv(a: Matrix) -> Matrix:
    if mat_det(a) != ONE:
        raise ValueError("matrix is not in SL_2")
    return (a[3], g_neg(a[1]), g_neg(a[2]), a[0])


def mat_pow(a: Matrix, exponent: int) -> Matrix:
    if exponent < 0:
        return mat_pow(mat_inv(a), -exponent)
    result = IDENTITY
    base = a
    n = exponent
    while n:
        if n & 1:
            result = mat_mul(result, base)
        base = mat_mul(base, base)
        n >>= 1
    return result


def mat_flat(a: Matrix) -> tuple[int, ...]:
    return tuple(coordinate for entry in a for coordinate in entry)


def mat_text(a: Matrix) -> str:
    return f"[[{g_to_text(a[0])},{g_to_text(a[1])}],[{g_to_text(a[2])},{g_to_text(a[3])}]]"


def matrix_id(a: Matrix) -> str:
    raw = ",".join(str(x) for x in mat_flat(a)).encode("ascii")
    return "M" + hashlib.sha256(raw).hexdigest()[:16]


def in_level_three(a: Matrix) -> bool:
    residues = tuple(g_mod3(x) for x in a)
    return residues == (ONE, ZERO, ZERO, ONE)


def elementary_generators() -> tuple[dict[str, Matrix], dict[str, str], tuple[str, ...]]:
    three = (3, 0)
    three_i = g_mul(three, I_GAUSSIAN)
    positive = {
        "U1": (ONE, three, ZERO, ONE),
        "Ui": (ONE, three_i, ZERO, ONE),
        "L1": (ONE, ZERO, three, ONE),
        "Li": (ONE, ZERO, three_i, ONE),
    }
    generators: dict[str, Matrix] = {}
    inverse_name: dict[str, str] = {}
    order: list[str] = []
    for name in ("U1", "Ui", "L1", "Li"):
        inverse = name + "m"
        generators[name] = positive[name]
        generators[inverse] = mat_inv(positive[name])
        inverse_name[name] = inverse
        inverse_name[inverse] = name
        order.extend((name, inverse))
    return generators, inverse_name, tuple(order)


GENERATORS, INVERSE_NAME, GENERATOR_ORDER = elementary_generators()


def word_text(word: Word) -> str:
    return ".".join(word) if word else "e"


def inverse_word(word: Word) -> Word:
    return tuple(INVERSE_NAME[name] for name in reversed(word))


def canonical_rotation(word: Word) -> Word:
    if not word:
        return word
    return min(word[index:] + word[:index] for index in range(len(word)))


def symbolic_root(word: Word) -> tuple[Word, int]:
    n = len(word)
    if n == 0:
        return word, 1
    for size in range(1, n):
        if n % size == 0:
            root = word[:size]
            exponent = n // size
            if root * exponent == word:
                return root, exponent
    return word, 1


def enumerate_word_ball(max_word_length: int = MAX_WORD_LENGTH) -> dict[Matrix, dict[str, object]]:
    records: dict[Matrix, dict[str, object]] = {
        IDENTITY: {"representative": (), "word_collision_count": 1}
    }
    frontier: list[tuple[Word, Matrix]] = [((), IDENTITY)]
    for _length in range(1, max_word_length + 1):
        next_frontier: list[tuple[Word, Matrix]] = []
        for word, matrix in frontier:
            for name in GENERATOR_ORDER:
                if word and INVERSE_NAME[name] == word[-1]:
                    continue
                new_word = word + (name,)
                new_matrix = mat_mul(matrix, GENERATORS[name])
                next_frontier.append((new_word, new_matrix))
                record = records.get(new_matrix)
                if record is None:
                    records[new_matrix] = {
                        "representative": new_word,
                        "word_collision_count": 1,
                    }
                else:
                    record["word_collision_count"] = int(record["word_collision_count"]) + 1
                    if new_word < record["representative"]:
                        record["representative"] = new_word
        frontier = next_frontier
    return records


def classification(matrix: Matrix) -> str:
    if matrix == IDENTITY:
        return "IDENTITY"
    trace = mat_trace(matrix)
    if g_square(trace) == (4, 0):
        return "PARABOLIC"
    return "LOXODROMIC"


def complex_length(trace: Gaussian) -> tuple[float, float, float]:
    trace_complex = complex(trace[0], trace[1])
    value = 2.0 * cmath.acosh(trace_complex / 2.0)
    if value.real < 0:
        value = -value
    theta = ((value.imag + math.pi) % (2.0 * math.pi)) - math.pi
    if theta <= -math.pi + 1e-14:
        theta = math.pi
    normalized = complex(value.real, theta)
    reconstructed = 2.0 * cmath.cosh(normalized / 2.0)
    # The ledger is for the projected PSL_2(C) element.  Normalizing the
    # holonomy angle modulo 2*pi may exchange the two SL_2 lifts, so the trace
    # identity is projectively valid up to sign.
    residual = min(abs(reconstructed - trace_complex), abs(reconstructed + trace_complex))
    return normalized.real, normalized.imag, residual


def exact_power_roots(
    elements: dict[Matrix, dict[str, object]], max_exponent: int = MAX_WORD_LENGTH
) -> dict[Matrix, tuple[Matrix, int]]:
    roots: dict[Matrix, tuple[Matrix, int]] = {}
    ordered = sorted(
        (matrix for matrix in elements if matrix != IDENTITY),
        key=lambda matrix: (len(elements[matrix]["representative"]), mat_flat(matrix)),
    )
    for root in ordered:
        candidate = root
        for exponent in range(2, max_exponent + 1):
            candidate = mat_mul(candidate, root)
            if candidate not in elements:
                continue
            current = roots.get(candidate)
            proposal_key = (
                len(elements[root]["representative"]),
                exponent,
                mat_flat(root),
            )
            if current is None:
                roots[candidate] = (root, exponent)
            else:
                current_key = (
                    len(elements[current[0]]["representative"]),
                    current[1],
                    mat_flat(current[0]),
                )
                if proposal_key < current_key:
                    roots[candidate] = (root, exponent)
    return roots


def _float(value: float) -> str:
    return format(value, ".15g")


def _corr(xs: list[float], ys: list[float]) -> float:
    if len(xs) < 2:
        return 0.0
    mean_x = sum(xs) / len(xs)
    mean_y = sum(ys) / len(ys)
    dx = [x - mean_x for x in xs]
    dy = [y - mean_y for y in ys]
    denominator = math.sqrt(sum(x * x for x in dx) * sum(y * y for y in dy))
    if denominator == 0:
        return 0.0
    return sum(x * y for x, y in zip(dx, dy, strict=True)) / denominator


def phase_length_score(lengths: list[float], angles: list[float]) -> float:
    return math.hypot(
        _corr(lengths, [math.cos(angle) for angle in angles]),
        _corr(lengths, [math.sin(angle) for angle in angles]),
    )


LEDGER_FIELDS = [
    "row_id",
    "representative_word",
    "word_length",
    "matrix",
    "determinant",
    "level3_membership",
    "matrix_class",
    "trace_re",
    "trace_im",
    "complex_length_re",
    "holonomy_angle",
    "trace_reconstruction_residual",
    "symbolic_cyclic_class",
    "symbolic_unoriented_class",
    "symbolic_root",
    "symbolic_repetition_exponent",
    "exact_power_root_id",
    "exact_power_exponent",
    "primitive_status",
    "orientation_pair_id",
    "orientation",
    "word_collision_multiplicity",
    "trace_collision_multiplicity",
    "parabolic_cusp_risk",
    "conjugacy_scope",
    "completeness_boundary",
    "evidence_status",
]

CONTROL_FIELDS = [
    "control_id",
    "row_id",
    "complex_length_fixed",
    "repetition_exponent_fixed",
    "original_holonomy_angle",
    "shuffled_holonomy_angle",
    "shuffled_from_row_id",
    "orientation_reversal_angle",
    "shuffle_seed_label",
    "target_data_used",
    "evidence_status",
]


def build_payload(max_word_length: int = MAX_WORD_LENGTH) -> tuple[list[dict[str, str]], list[dict[str, str]], dict[str, object]]:
    elements = enumerate_word_ball(max_word_length)
    power_roots = exact_power_roots(elements, max_word_length)
    trace_counts = Counter(mat_trace(matrix) for matrix in elements)
    rows: list[dict[str, str]] = []

    for matrix in sorted(elements, key=mat_flat):
        record = elements[matrix]
        word = record["representative"]
        assert isinstance(word, tuple)
        matrix_class = classification(matrix)
        trace = mat_trace(matrix)
        if matrix_class == "LOXODROMIC":
            length, theta, residual = complex_length(trace)
        else:
            length, theta, residual = math.nan, math.nan, 0.0

        symbolic_base, symbolic_exponent = symbolic_root(word)
        exact_root = power_roots.get(matrix)
        if exact_root is None:
            exact_root_id = ""
            exact_exponent = 1
        else:
            exact_root_id = matrix_id(exact_root[0])
            exact_exponent = exact_root[1]

        if matrix_class == "LOXODROMIC" and exact_exponent == 1:
            primitive_status = "PRIMITIVE_WITHIN_WORD_BALL_NOT_GROUP_CERTIFIED"
        elif matrix_class == "LOXODROMIC":
            primitive_status = "REPETITION_CERTIFIED_WITHIN_ENUMERATED_SET"
        else:
            primitive_status = "NOT_A_LOXODROMIC_PERIODIC_OBJECT"

        inverse = mat_inv(matrix)
        paired = sorted((mat_flat(matrix), mat_flat(inverse)))
        pair_raw = repr(paired).encode("ascii")
        orientation_pair_id = "O" + hashlib.sha256(pair_raw).hexdigest()[:16]
        orientation = "CANONICAL" if mat_flat(matrix) <= mat_flat(inverse) else "REVERSED"

        cyclic = canonical_rotation(word)
        unoriented = min(cyclic, canonical_rotation(inverse_word(word)))
        if matrix_class == "IDENTITY":
            cusp_risk = "IDENTITY_NOT_ORBIT"
        elif matrix_class == "PARABOLIC":
            cusp_risk = "PARABOLIC_CUSP_ELEMENT_EXCLUDED_FROM_CLOSED_GEODESICS"
        else:
            cusp_risk = "GLOBAL_CUSP_SCATTERING_TERMS_NOT_COMPUTED"

        rows.append(
            {
                "row_id": matrix_id(matrix),
                "representative_word": word_text(word),
                "word_length": str(len(word)),
                "matrix": mat_text(matrix),
                "determinant": g_to_text(mat_det(matrix)),
                "level3_membership": "true" if in_level_three(matrix) else "false",
                "matrix_class": matrix_class,
                "trace_re": str(trace[0]),
                "trace_im": str(trace[1]),
                "complex_length_re": "" if math.isnan(length) else _float(length),
                "holonomy_angle": "" if math.isnan(theta) else _float(theta),
                "trace_reconstruction_residual": _float(residual),
                "symbolic_cyclic_class": word_text(cyclic),
                "symbolic_unoriented_class": word_text(unoriented),
                "symbolic_root": word_text(symbolic_base),
                "symbolic_repetition_exponent": str(symbolic_exponent),
                "exact_power_root_id": exact_root_id,
                "exact_power_exponent": str(exact_exponent),
                "primitive_status": primitive_status,
                "orientation_pair_id": orientation_pair_id,
                "orientation": orientation,
                "word_collision_multiplicity": str(record["word_collision_count"]),
                "trace_collision_multiplicity": str(trace_counts[trace]),
                "parabolic_cusp_risk": cusp_risk,
                "conjugacy_scope": "SYMBOLIC_CYCLIC_CLASS_ONLY_NOT_FULL_GROUP_CONJUGACY",
                "completeness_boundary": COMPLETENESS_BOUNDARY,
                "evidence_status": "NUMERICALLY_CERTIFIED",
            }
        )

    control_candidates = [
        row
        for row in rows
        if row["matrix_class"] == "LOXODROMIC" and row["exact_power_exponent"] == "1"
    ]
    source_order = sorted(
        control_candidates,
        key=lambda row: hashlib.sha256(
            f"{SHUFFLE_SEED_LABEL}:{row['row_id']}".encode("utf-8")
        ).hexdigest(),
    )
    controls: list[dict[str, str]] = []
    for target, source in zip(control_candidates, source_order, strict=True):
        theta = float(target["holonomy_angle"])
        source_theta = float(source["holonomy_angle"])
        controls.append(
            {
                "control_id": "HC" + target["row_id"][1:],
                "row_id": target["row_id"],
                "complex_length_fixed": target["complex_length_re"],
                "repetition_exponent_fixed": target["exact_power_exponent"],
                "original_holonomy_angle": target["holonomy_angle"],
                "shuffled_holonomy_angle": source["holonomy_angle"],
                "shuffled_from_row_id": source["row_id"],
                "orientation_reversal_angle": _float(-theta),
                "shuffle_seed_label": SHUFFLE_SEED_LABEL,
                "target_data_used": "false",
                "evidence_status": "NUMERICALLY_CERTIFIED",
            }
        )

    class_counts = Counter(row["matrix_class"] for row in rows)
    primitive_count = sum(
        row["primitive_status"] == "PRIMITIVE_WITHIN_WORD_BALL_NOT_GROUP_CERTIFIED"
        for row in rows
    )
    repetition_count = sum(
        row["primitive_status"] == "REPETITION_CERTIFIED_WITHIN_ENUMERATED_SET"
        for row in rows
    )
    lengths = [float(row["complex_length_fixed"]) for row in controls]
    original_angles = [float(row["original_holonomy_angle"]) for row in controls]
    shuffled_angles = [float(row["shuffled_holonomy_angle"]) for row in controls]
    metrics: dict[str, object] = {
        "candidate_id": "P24-BIANCHI-LEVEL3-ELEMENTARY-WORDBALL-R2",
        "generated_on": "2026-08-27",
        "max_reduced_word_length": max_word_length,
        "generator_names": list(GENERATOR_ORDER),
        "generator_claim": "FOUR_ELEMENTARY_GENERATORS_AND_INVERSES_ONLY",
        "enumerated_reduced_words_including_identity": 1
        + sum(8 * (7 ** (length - 1)) for length in range(1, max_word_length + 1)),
        "unique_exact_matrices": len(rows),
        "identity_rows": class_counts["IDENTITY"],
        "parabolic_rows": class_counts["PARABOLIC"],
        "loxodromic_rows": class_counts["LOXODROMIC"],
        "primitive_within_word_ball_not_group_certified": primitive_count,
        "certified_repetitions_within_enumerated_set": repetition_count,
        "holonomy_shuffle_rows": len(controls),
        "phase_length_score_original": phase_length_score(lengths, original_angles),
        "phase_length_score_shuffled": phase_length_score(lengths, shuffled_angles),
        "holonomy_control_evidence": "NUMERICAL_OBSERVATION",
        "holonomy_control_verdict": "OPEN",
        "max_trace_reconstruction_residual": max(
            float(row["trace_reconstruction_residual"]) for row in rows
        ),
        "all_determinants_one": all(row["determinant"] == "1" for row in rows),
        "all_level3_membership": all(row["level3_membership"] == "true" for row in rows),
        "all_orientation_inverses_present": all(mat_inv(matrix) in elements for matrix in elements),
        "prime_or_zero_tables_used": False,
        "orbit_to_prime_ideal_map": "OPEN_NOT_ESTABLISHED",
        "full_gamma3_enumeration": "OPEN_NOT_ESTABLISHED",
        "full_conjugacy_enumeration": "OPEN_NOT_ESTABLISHED",
        "formal_route_a_tuple": "UNASSIGNED",
        "route_b_evaluation": "NOT_RUN",
        "route_b_invocation_allowed": False,
        "completeness_boundary": COMPLETENESS_BOUNDARY,
        "evidence_status": "NUMERICALLY_CERTIFIED",
    }
    return rows, controls, metrics


def csv_bytes(rows: Iterable[dict[str, str]], fieldnames: list[str]) -> bytes:
    stream = io.StringIO(newline="")
    writer = csv.DictWriter(stream, fieldnames=fieldnames, lineterminator="\n")
    writer.writeheader()
    writer.writerows(rows)
    return stream.getvalue().encode("utf-8")


def json_bytes(payload: object) -> bytes:
    return (json.dumps(payload, indent=2, sort_keys=True) + "\n").encode("utf-8")


def core_outputs(max_word_length: int = MAX_WORD_LENGTH) -> tuple[dict[str, bytes], dict[str, object]]:
    rows, controls, metrics = build_payload(max_word_length)
    outputs = {
        "results/bianchi_complex_length_ledger_round2.csv": csv_bytes(rows, LEDGER_FIELDS),
        "results/bianchi_holonomy_shuffle_control_round2.csv": csv_bytes(controls, CONTROL_FIELDS),
        "results/round2_metrics.json": json_bytes(metrics),
    }
    return outputs, metrics


def combined_hash(outputs: dict[str, bytes]) -> str:
    digest = hashlib.sha256()
    for name in sorted(outputs):
        digest.update(name.encode("utf-8"))
        digest.update(b"\0")
        digest.update(outputs[name])
        digest.update(b"\0")
    return digest.hexdigest()


def validation_markdown(metrics: dict[str, object], hashes: dict[str, str], digest: str) -> bytes:
    text = f"""# P24 Round-2 validation report

## Material Passport

- Origin Skill: experiment-agent
- Origin Mode: run + validate
- Origin Date: 2026-08-27
- Verification Status: VERIFIED
- Version Label: p24_round2_validation_v1

## Reproducibility verdict

- Determinism class: deterministic exact Gaussian-integer enumeration.
- Verdict: `REPRODUCIBLE`.
- Core-output combined SHA-256: `{digest}`.
- A second in-process generation produced the identical byte stream before any
  artifact was written.

## Exact validation checks

- Enumerated reduced words including identity: {metrics['enumerated_reduced_words_including_identity']}.
- Unique exact matrices: {metrics['unique_exact_matrices']}.
- All determinants exactly one: `{str(metrics['all_determinants_one']).lower()}`.
- All entries exactly congruent to `I mod 3`: `{str(metrics['all_level3_membership']).lower()}`.
- All orientation inverses present: `{str(metrics['all_orientation_inverses_present']).lower()}`.
- Maximum trace reconstruction residual: `{metrics['max_trace_reconstruction_residual']:.3e}`.
- Loxodromic / parabolic / identity rows: {metrics['loxodromic_rows']} / {metrics['parabolic_rows']} / {metrics['identity_rows']}.
- Primitive-within-word-ball candidates / certified observed repetitions:
  {metrics['primitive_within_word_ball_not_group_certified']} / {metrics['certified_repetitions_within_enumerated_set']}.
- Holonomy-shuffle control rows: {metrics['holonomy_shuffle_rows']}.
- Prime or zero tables used: `false`.

## File hashes

"""
    for name in sorted(hashes):
        text += f"- `{name}`: `{hashes[name]}`\n"
    text += f"""

## Claim boundary

`[NUMERICALLY_CERTIFIED]` applies only to exact matrix arithmetic, the stated
elementary-generator reduced-word ball, deterministic collision counts, and the
reported floating reconstruction tolerance.  The sample is **not** a complete
enumeration of `Gamma((3))`, **not** a complete conjugacy-class or primitive
closed-geodesic ledger, and establishes no orbit-to-prime-ideal map.  Those
claims remain `[OPEN]`.  Cusp/scattering terms are not computed.
"""
    return text.encode("utf-8")


def run(project_root: Path, max_word_length: int = MAX_WORD_LENGTH) -> str:
    outputs_first, metrics_first = core_outputs(max_word_length)
    outputs_second, metrics_second = core_outputs(max_word_length)
    if outputs_first != outputs_second or metrics_first != metrics_second:
        raise RuntimeError("deterministic in-process regeneration mismatch")

    hashes = {name: hashlib.sha256(data).hexdigest() for name, data in outputs_first.items()}
    digest = combined_hash(outputs_first)
    receipt = {
        "candidate_id": "P24-BIANCHI-LEVEL3-ELEMENTARY-WORDBALL-R2",
        "command": "python3 code/round2_bianchi_ledger.py",
        "date": "2026-08-27",
        "status": "COMPLETED",
        "verification_status": "VERIFIED",
        "reproducibility_verdict": "REPRODUCIBLE",
        "determinism": "DETERMINISTIC_EXACT_CORE_OUTPUTS",
        "combined_sha256": digest,
        "core_file_sha256": hashes,
        "script_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        "expected_outputs": sorted(outputs_first),
        "anomalies": [],
        "prime_or_zero_tables_used": False,
        "formal_route_a_tuple": "UNASSIGNED",
        "route_b_evaluation": "NOT_RUN",
        "route_b_invocation_allowed": False,
        "claim_boundary": COMPLETENESS_BOUNDARY,
        "evidence_status": "NUMERICALLY_CERTIFIED",
    }
    outputs = dict(outputs_first)
    outputs["experiments/round2_receipt.json"] = json_bytes(receipt)
    outputs["experiments/round2_validation.md"] = validation_markdown(
        metrics_first, hashes, digest
    )
    for relative, data in outputs.items():
        destination = project_root / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(data)
    return digest


def validate_existing(project_root: Path, max_word_length: int = MAX_WORD_LENGTH) -> str:
    expected, _metrics = core_outputs(max_word_length)
    mismatches = []
    for relative, data in expected.items():
        path = project_root / relative
        if not path.exists() or path.read_bytes() != data:
            mismatches.append(relative)
    if mismatches:
        raise RuntimeError("existing artifact mismatch: " + ", ".join(mismatches))
    return combined_hash(expected)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--max-word-length", type=int, default=MAX_WORD_LENGTH)
    parser.add_argument("--verify-existing", action="store_true")
    args = parser.parse_args()
    if args.max_word_length != MAX_WORD_LENGTH:
        raise SystemExit("Round-2 cutoff is frozen at max word length 5")
    project_root = Path(__file__).resolve().parents[1]
    digest = (
        validate_existing(project_root, args.max_word_length)
        if args.verify_existing
        else run(project_root, args.max_word_length)
    )
    print(json.dumps({"status": "PASS", "combined_sha256": digest}, sort_keys=True))


if __name__ == "__main__":
    main()
