#!/usr/bin/env python3
"""Deterministic controls for the P1/F2 Frobenius suspension.

The program uses exact finite polynomial arithmetic over F_2 and finite
enumerations.  It contains no Riemann-zero data, fitting, optimization,
randomness, or network access.  Floating-point rows only regression-test
analytic formulas that are proved independently in notes/proof_audit.md.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
from fractions import Fraction
from pathlib import Path
from typing import Iterable, Sequence


def poly_degree(poly: int) -> int:
    """Degree of a polynomial encoded by coefficient bits; deg(0) = -1."""
    return poly.bit_length() - 1


def poly_to_string(poly: int) -> str:
    """Render a bit-encoded polynomial over F_2."""
    if poly == 0:
        return "0"
    terms: list[str] = []
    for exponent in range(poly_degree(poly), -1, -1):
        if not (poly >> exponent) & 1:
            continue
        if exponent == 0:
            terms.append("1")
        elif exponent == 1:
            terms.append("x")
        else:
            terms.append(f"x^{exponent}")
    return "+".join(terms)


def poly_mod(dividend: int, divisor: int) -> int:
    """Polynomial remainder over F_2."""
    if divisor == 0:
        raise ZeroDivisionError("polynomial division by zero")
    remainder = dividend
    divisor_degree = poly_degree(divisor)
    while remainder and poly_degree(remainder) >= divisor_degree:
        remainder ^= divisor << (poly_degree(remainder) - divisor_degree)
    return remainder


def poly_gcd(left: int, right: int) -> int:
    """Monic gcd over F_2 (all nonzero leading coefficients equal one)."""
    while right:
        left, right = right, poly_mod(left, right)
    return left


def poly_multiply(left: int, right: int) -> int:
    """Polynomial multiplication over F_2 without reduction."""
    product = 0
    multiplier = right
    multiplicand = left
    while multiplier:
        if multiplier & 1:
            product ^= multiplicand
        multiplier >>= 1
        multiplicand <<= 1
    return product


def poly_multiply_mod(left: int, right: int, modulus: int) -> int:
    return poly_mod(poly_multiply(left, right), modulus)


def poly_power_mod(base: int, exponent: int, modulus: int) -> int:
    """Binary exponentiation in F_2[x]/(modulus)."""
    if exponent < 0:
        raise ValueError("exponent must be nonnegative")
    result = 1
    factor = poly_mod(base, modulus)
    power = exponent
    while power:
        if power & 1:
            result = poly_multiply_mod(result, factor, modulus)
        factor = poly_multiply_mod(factor, factor, modulus)
        power >>= 1
    return result


def integer_prime_divisors(value: int) -> list[int]:
    """Distinct prime divisors generated by trial division."""
    if value < 1:
        raise ValueError("value must be positive")
    divisors: list[int] = []
    remainder = value
    candidate = 2
    while candidate * candidate <= remainder:
        if remainder % candidate == 0:
            divisors.append(candidate)
            while remainder % candidate == 0:
                remainder //= candidate
        candidate += 1
    if remainder > 1:
        divisors.append(remainder)
    return divisors


def is_integer_prime(value: int) -> bool:
    if value < 2:
        return False
    return integer_prime_divisors(value) == [value]


def is_irreducible_f2(poly: int) -> bool:
    """Rabin irreducibility test for a monic polynomial over F_2.

    A degree-n polynomial f is irreducible iff x^(2^n) = x mod f and, for
    every prime q dividing n, gcd(f, x^(2^(n/q)) - x) = 1.  Subtraction is XOR
    in characteristic two.
    """
    degree = poly_degree(poly)
    if degree < 1:
        return False
    if not (poly >> degree) & 1:
        return False
    x_poly = 0b10
    x_residue = poly_mod(x_poly, poly)
    for prime in integer_prime_divisors(degree):
        frobenius_residue = poly_power_mod(
            x_poly, 1 << (degree // prime), poly
        )
        if poly_gcd(poly, frobenius_residue ^ x_residue) != 1:
            return False
    return poly_power_mod(x_poly, 1 << degree, poly) == x_residue


def monic_polynomials(degree: int) -> range:
    if degree < 1:
        raise ValueError("degree must be positive")
    return range(1 << degree, 1 << (degree + 1))


def irreducible_polynomials_f2(degree: int) -> list[int]:
    return [poly for poly in monic_polynomials(degree) if is_irreducible_f2(poly)]


def integer_divisors(value: int) -> list[int]:
    return [candidate for candidate in range(1, value + 1) if value % candidate == 0]


def moebius(value: int) -> int:
    if value < 1:
        raise ValueError("value must be positive")
    remainder = value
    sign = 1
    candidate = 2
    while candidate * candidate <= remainder:
        if remainder % candidate == 0:
            remainder //= candidate
            sign = -sign
            if remainder % candidate == 0:
                return 0
            while remainder % candidate == 0:
                remainder //= candidate
        candidate += 1
    if remainder > 1:
        sign = -sign
    return sign


def affine_irreducible_count_formula(degree: int) -> int:
    numerator = sum(
        moebius(divisor) * (2 ** (degree // divisor))
        for divisor in integer_divisors(degree)
    )
    quotient, remainder = divmod(numerator, degree)
    if remainder:
        raise ArithmeticError("Möbius irreducible count was not integral")
    return quotient


def projective_closed_point_count(degree: int, affine_count: int) -> int:
    """P1 adds its rational point at infinity in degree one."""
    return affine_count + (1 if degree == 1 else 0)


def fixed_point_count_p1_f2(extension_degree: int) -> int:
    return 2**extension_degree + 1


def recovered_fixed_point_count(
    extension_degree: int, closed_point_counts: dict[int, int]
) -> int:
    return sum(
        degree * closed_point_counts[degree]
        for degree in integer_divisors(extension_degree)
    )


def orbit_product_coefficients(
    max_order: int, closed_point_counts: dict[int, int]
) -> list[int]:
    """Coefficients of product_d (1-z^d)^(-a_d) through z^max_order."""
    coefficients = [0] * (max_order + 1)
    coefficients[0] = 1
    for degree in range(1, max_order + 1):
        multiplicity = closed_point_counts[degree]
        factor = [0] * (max_order + 1)
        for repetition in range(0, max_order // degree + 1):
            factor[repetition * degree] = math.comb(
                multiplicity + repetition - 1, repetition
            )
        updated = [0] * (max_order + 1)
        for left_order, left_value in enumerate(coefficients):
            if left_value == 0:
                continue
            for right_order in range(max_order - left_order + 1):
                if factor[right_order]:
                    updated[left_order + right_order] += (
                        left_value * factor[right_order]
                    )
        coefficients = updated
    return coefficients


def rational_p1_coefficients(max_order: int) -> list[int]:
    """Coefficients of 1/((1-z)(1-2z))."""
    return [2 ** (order + 1) - 1 for order in range(max_order + 1)]


def partial_orbit_log(
    sigma: float, max_degree: int, closed_point_counts: dict[int, int]
) -> float:
    return sum(
        -closed_point_counts[degree]
        * math.log1p(-(2.0 ** (-sigma * degree)))
        for degree in range(1, max_degree + 1)
    )


def continued_zeta_p1(s_value: complex) -> complex:
    first = 1.0 - 2.0 ** (-s_value)
    second = 1.0 - 2.0 ** (1.0 - s_value)
    return 1.0 / (first * second)


def circle_compiler_log_product(lengths: Sequence[float], sigma: float) -> float:
    if any(length <= 0.0 for length in lengths):
        raise ValueError("all circle lengths must be positive")
    return sum(-math.log1p(-math.exp(-sigma * length)) for length in lengths)


def generated_primes(limit: int) -> list[int]:
    return [value for value in range(2, limit + 1) if is_integer_prime(value)]


def clock_intersection_solutions(
    characteristic_limit: int = 11,
    target_prime_limit: int = 31,
    max_field_exponent: int = 3,
    max_orbit_degree: int = 6,
    max_target_repetition: int = 18,
) -> list[dict[str, int]]:
    """Exhaust ell^(f*n) = p^r on a generated finite grid."""
    rows: list[dict[str, int]] = []
    for characteristic in generated_primes(characteristic_limit):
        for field_exponent in range(1, max_field_exponent + 1):
            for orbit_degree in range(1, max_orbit_degree + 1):
                left = characteristic ** (field_exponent * orbit_degree)
                for target_prime in generated_primes(target_prime_limit):
                    for repetition in range(1, max_target_repetition + 1):
                        if left == target_prime**repetition:
                            rows.append(
                                {
                                    "characteristic": characteristic,
                                    "field_exponent": field_exponent,
                                    "orbit_degree": orbit_degree,
                                    "target_prime": target_prime,
                                    "target_repetition": repetition,
                                    "common_integer": left,
                                }
                            )
    return rows


def write_csv(
    path: Path, fieldnames: list[str], rows: Iterable[dict[str, object]]
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def run(output_dir: Path, max_degree: int = 12) -> dict[str, object]:
    if max_degree < 4:
        raise ValueError("max_degree must be at least four")
    output_dir.mkdir(parents=True, exist_ok=True)

    irreducibles: dict[int, list[int]] = {
        degree: irreducible_polynomials_f2(degree)
        for degree in range(1, max_degree + 1)
    }
    affine_counts = {
        degree: len(polynomials) for degree, polynomials in irreducibles.items()
    }
    closed_counts = {
        degree: projective_closed_point_count(degree, affine_counts[degree])
        for degree in range(1, max_degree + 1)
    }

    polynomial_path = output_dir / "irreducible_polynomials_f2.csv"
    write_csv(
        polynomial_path,
        ["degree", "bit_encoding", "coefficient_bits", "polynomial"],
        (
            {
                "degree": degree,
                "bit_encoding": polynomial,
                "coefficient_bits": format(polynomial, f"0{degree + 1}b"),
                "polynomial": poly_to_string(polynomial),
            }
            for degree in range(1, max_degree + 1)
            for polynomial in irreducibles[degree]
        ),
    )

    ledger_path = output_dir / "closed_point_ledger.csv"
    ledger_rows: list[dict[str, object]] = []
    for degree in range(1, max_degree + 1):
        formula_count = affine_irreducible_count_formula(degree)
        recovered = recovered_fixed_point_count(degree, closed_counts)
        expected_fixed = fixed_point_count_p1_f2(degree)
        ledger_rows.append(
            {
                "degree": degree,
                "affine_irreducible_count_enumerated": affine_counts[degree],
                "affine_irreducible_count_moebius": formula_count,
                "projective_closed_point_count": closed_counts[degree],
                "fixed_points_P1_F2n": expected_fixed,
                "fixed_points_recovered_from_cycles": recovered,
                "count_match": affine_counts[degree] == formula_count,
                "fixed_point_match": recovered == expected_fixed,
                "primitive_period_log2_units": degree,
                "primitive_period": f"{degree}*log(2)",
            }
        )
    write_csv(
        ledger_path,
        [
            "degree",
            "affine_irreducible_count_enumerated",
            "affine_irreducible_count_moebius",
            "projective_closed_point_count",
            "fixed_points_P1_F2n",
            "fixed_points_recovered_from_cycles",
            "count_match",
            "fixed_point_match",
            "primitive_period_log2_units",
            "primitive_period",
        ],
        ledger_rows,
    )

    observed_coefficients = orbit_product_coefficients(max_degree, closed_counts)
    expected_coefficients = rational_p1_coefficients(max_degree)
    series_path = output_dir / "zeta_formal_series_identity.csv"
    write_csv(
        series_path,
        [
            "power",
            "orbit_product_coefficient",
            "rational_function_coefficient",
            "coefficient_match",
            "log_derivative_log2_units",
            "fixed_point_count",
            "log_derivative_match",
        ],
        (
            {
                "power": order,
                "orbit_product_coefficient": observed_coefficients[order],
                "rational_function_coefficient": expected_coefficients[order],
                "coefficient_match": (
                    observed_coefficients[order] == expected_coefficients[order]
                ),
                "log_derivative_log2_units": (
                    0
                    if order == 0
                    else recovered_fixed_point_count(order, closed_counts)
                ),
                "fixed_point_count": (
                    0 if order == 0 else fixed_point_count_p1_f2(order)
                ),
                "log_derivative_match": (
                    True
                    if order == 0
                    else recovered_fixed_point_count(order, closed_counts)
                    == fixed_point_count_p1_f2(order)
                ),
            }
            for order in range(max_degree + 1)
        ),
    )

    repetition_path = output_dir / "repetition_weight_ledger.csv"
    write_csv(
        repetition_path,
        [
            "power",
            "primitive_degree",
            "repetition",
            "primitive_orbit_count",
            "log_zeta_contribution",
            "single_orbit_length_log2_units",
            "minus_log_derivative_contribution_log2_units",
        ],
        (
            {
                "power": degree * repetition,
                "primitive_degree": degree,
                "repetition": repetition,
                "primitive_orbit_count": closed_counts[degree],
                "log_zeta_contribution": str(
                    Fraction(closed_counts[degree], repetition)
                ),
                "single_orbit_length_log2_units": degree,
                "minus_log_derivative_contribution_log2_units": (
                    closed_counts[degree] * degree
                ),
            }
            for degree in range(1, max_degree + 1)
            for repetition in range(1, max_degree // degree + 1)
        ),
    )

    convergence_path = output_dir / "euler_product_convergence_controls.csv"
    convergence_rows: list[dict[str, object]] = []
    cutoffs = sorted(
        set(value for value in (1, 2, 4, 6, 8, 10, max_degree) if value <= max_degree)
    )
    for sigma in (0.75, 1.0, 1.25, 2.0):
        analytic_log = (
            -math.log1p(-(2.0 ** -sigma))
            - math.log1p(-(2.0 ** (1.0 - sigma)))
            if sigma > 1.0
            else None
        )
        for cutoff in cutoffs:
            partial = partial_orbit_log(sigma, cutoff, closed_counts)
            convergence_rows.append(
                {
                    "sigma": sigma,
                    "degree_cutoff": cutoff,
                    "partial_log_euler_product": f"{partial:.17g}",
                    "continued_positive_log_reference": (
                        "" if analytic_log is None else f"{analytic_log:.17g}"
                    ),
                    "partial_minus_reference": (
                        "" if analytic_log is None else f"{partial - analytic_log:.17g}"
                    ),
                    "theorem_domain_label": (
                        "absolute_convergence" if sigma > 1.0 else "divergent_boundary_or_left"
                    ),
                }
            )
    write_csv(
        convergence_path,
        [
            "sigma",
            "degree_cutoff",
            "partial_log_euler_product",
            "continued_positive_log_reference",
            "partial_minus_reference",
            "theorem_domain_label",
        ],
        convergence_rows,
    )

    periodicity_path = output_dir / "imaginary_periodicity_controls.csv"
    base_s = complex(1.5, 0.37)
    base_value = continued_zeta_p1(base_s)
    imaginary_period = 2.0 * math.pi / math.log(2.0)
    write_csv(
        periodicity_path,
        [
            "period_multiple",
            "s_real",
            "s_imag",
            "zeta_real",
            "zeta_imag",
            "absolute_difference_from_base",
        ],
        (
            {
                "period_multiple": multiple,
                "s_real": f"{base_s.real:.17g}",
                "s_imag": f"{base_s.imag + multiple * imaginary_period:.17g}",
                "zeta_real": f"{continued_zeta_p1(base_s + 1j * multiple * imaginary_period).real:.17g}",
                "zeta_imag": f"{continued_zeta_p1(base_s + 1j * multiple * imaginary_period).imag:.17g}",
                "absolute_difference_from_base": f"{abs(continued_zeta_p1(base_s + 1j * multiple * imaginary_period) - base_value):.17g}",
            }
            for multiple in range(-3, 4)
        ),
    )

    clock_rows = clock_intersection_solutions()
    clock_path = output_dir / "clock_intersection_controls.csv"
    write_csv(
        clock_path,
        [
            "characteristic",
            "field_exponent",
            "orbit_degree",
            "target_prime",
            "target_repetition",
            "common_integer",
            "same_characteristic",
            "exponent_identity",
        ],
        (
            {
                **row,
                "same_characteristic": (
                    row["characteristic"] == row["target_prime"]
                ),
                "exponent_identity": (
                    row["field_exponent"] * row["orbit_degree"]
                    == row["target_repetition"]
                ),
            }
            for row in clock_rows
        ),
    )

    compiler_profiles: dict[str, list[float]] = {
        "integer_log_lengths": [math.log(value) for value in range(4, 10)],
        "composites_only_log_lengths": [
            math.log(value)
            for value in range(4, 17)
            if not is_integer_prime(value)
        ],
        "quadratic_irrational_lengths": [math.sqrt(value) for value in range(2, 8)],
    }
    compiler_path = output_dir / "universal_circle_compiler_controls.csv"
    compiler_rows: list[dict[str, object]] = []
    for profile_name, lengths in compiler_profiles.items():
        for sigma in (0.75, 1.25, 2.0):
            orbit_log = circle_compiler_log_product(lengths, sigma)
            direct_log = math.log(
                math.prod(
                    (1.0 - math.exp(-sigma * length)) ** -1
                    for length in lengths
                )
            )
            compiler_rows.append(
                {
                    "profile": profile_name,
                    "length_count": len(lengths),
                    "sigma": sigma,
                    "orbit_log_product": f"{orbit_log:.17g}",
                    "direct_encoded_log_product": f"{direct_log:.17g}",
                    "absolute_difference": f"{abs(orbit_log - direct_log):.17g}",
                    "route_a_interpretation": "PROVES_TOO_MUCH_WITHOUT_A0",
                }
            )
    write_csv(
        compiler_path,
        [
            "profile",
            "length_count",
            "sigma",
            "orbit_log_product",
            "direct_encoded_log_product",
            "absolute_difference",
            "route_a_interpretation",
        ],
        compiler_rows,
    )

    artifacts = [
        polynomial_path,
        ledger_path,
        series_path,
        repetition_path,
        convergence_path,
        periodicity_path,
        clock_path,
        compiler_path,
    ]
    manifest: dict[str, object] = {
        "schema": "frobenius-suspension-controls/1",
        "candidate_id": "FF-FROB-SUSP-P1-F2",
        "max_degree": max_degree,
        "monic_polynomials_examined": sum(2**degree for degree in range(1, max_degree + 1)),
        "affine_irreducibles_found": sum(affine_counts.values()),
        "projective_closed_points_through_cutoff": sum(closed_counts.values()),
        "all_moebius_counts_match": all(
            affine_counts[degree] == affine_irreducible_count_formula(degree)
            for degree in range(1, max_degree + 1)
        ),
        "all_fixed_point_ledgers_match": all(
            recovered_fixed_point_count(degree, closed_counts)
            == fixed_point_count_p1_f2(degree)
            for degree in range(1, max_degree + 1)
        ),
        "all_formal_zeta_coefficients_match": (
            observed_coefficients == expected_coefficients
        ),
        "clock_solution_count": len(clock_rows),
        "all_clock_solutions_same_characteristic": all(
            row["characteristic"] == row["target_prime"]
            and row["field_exponent"] * row["orbit_degree"]
            == row["target_repetition"]
            for row in clock_rows
        ),
        "forbidden_data": [
            "Riemann zeros",
            "fitted scales or shifts",
            "random seeds",
            "network data",
            "hard-coded rational-prime table",
        ],
        "interpretation_boundary": (
            "Finite deterministic regression controls for exact proofs; not "
            "numerical evidence for a Riemann or Hilbert--Polya candidate."
        ),
        "route_a_native": {
            "target": "Z(P1/F2, 2^(-s))",
            "a0": "A0_ANALYTIC_ARITHMETIC_ORIGIN",
            "a1": "A1_PASS_ANALYTIC",
            "a2": "A2_ANALYTIC_DETERMINANT",
            "a3": "A3_CONTROLLED_CONTINUATION",
            "a4": "A4_FAIL",
            "overall": "ROUTE_A_SUCCESS_ROUTE_B_NOT_READY",
            "scope": "native finite-field calibration only; no Riemann-route promotion",
        },
        "route_a_riemann_target": {
            "target": "Riemann zeta/xi",
            "a0": "A0_FAIL",
            "a1": "A1_PASS_ANALYTIC",
            "a1_boundary": "exact flow ledger for the wrong arithmetic support",
            "a2": "A2_FAIL",
            "a3": "A3_FAIL",
            "a4": "A4_FAIL",
            "overall": "ROUTE_A_REJECTED",
        },
        "route_a_tautological_compiler": {
            "candidate_id": "SPECZ-TAUT-NORM-CIRCLES",
            "a0": "A0_FAIL",
            "a1": "A1_PASS_ANALYTIC",
            "a2": "A2_ANALYTIC_DETERMINANT",
            "a2_boundary": "exact only because target primitive labels and roofs are inputs",
            "a3": "A3_FAIL",
            "a4": "A4_FAIL",
            "overall": "ROUTE_A_REJECTED",
            "adversarial_verdict": "STOP_SCOPED / PROVES_TOO_MUCH",
        },
        "route_b_invocation_allowed": False,
        "artifacts": {path.name: sha256(path) for path in artifacts},
    }
    manifest_path = output_dir / "frobenius_suspension_manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--max-degree", type=int, default=12)
    args = parser.parse_args()
    manifest = run(args.output_dir, args.max_degree)
    print(json.dumps(manifest, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
