#!/usr/bin/env python3
"""Build and validate the self-excluded C220 release manifest.

The manifest is intentionally a closure check rather than a second producer:
all mathematical data are regenerated by the independent scripts, while this
file records hashes for exactly the 27 payload files.  The manifest itself is
the sole excluded file, giving a 28-file release contract.
"""
from __future__ import annotations

from hashlib import sha256
import json
from pathlib import Path
import re
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "C220_RELEASE_MANIFEST.json"
EVIDENCE = ROOT / "results/c220_tasep_evidence.json"
PDF = ROOT / "paper/main.pdf"
EVALUATION = ROOT / "evaluations/route_a/HCS-C220/2026-08-28.yaml"
SOURCE_COMMIT = "86c7bb8a39cdd1b8e941e45833b068170ca06287"
EVALUATOR_SHA256 = "6f13fc94be84eaf22c518dd0c530e442cd625f3cdcb9d3d34e67cc11c881194c"
SCOPE = "NO_BAD_EULER_OR_ROOT_NUMBER"
FIXED_EPOCH = 1787875200

EXPECTED = {
    "EXPERIMENT_PLAN.md", "NARRATIVE_REPORT.md", "PAPER_IMPROVEMENT_LOG.md", "PAPER_PLAN.md",
    "README.md", "RESEARCH_QUESTION.md", "SOURCE_AUDIT.md", "THEOREM_PACKAGE.md",
    "code/README.md", "code/c220_tasep_checker.py", "code/c220_tasep_mutation.py",
    "code/c220_tasep_producer.py", "code/c220_tasep_replay.py",
    "code/c220_tasep_sympy_crosscheck.py", "code/c220_release_manifest.py",
    "evaluations/route_a/HCS-C220/2026-08-28.yaml",
    "paper/COMPILE_REPORT.md", "paper/README.md", "paper/main.pdf", "paper/main.tex",
    "paper/main_round0_original.pdf", "paper/main_round1.pdf", "paper/main_round2.pdf",
    "results/HOSTILE_AUDIT.md", "results/RESULTS.md", "results/TEST_REPORT.md",
    "results/c220_tasep_evidence.json",
}


def digest(path: Path) -> str:
    return sha256(path.read_bytes()).hexdigest()


def payload_hash(data: dict) -> str:
    body = dict(data)
    body.pop("payload_sha256", None)
    encoded = json.dumps(body, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode()
    return sha256(encoded).hexdigest()


def sidecar(path: Path) -> bool:
    return (path.suffix in {".aux", ".log", ".out", ".toc", ".fls", ".fdb_latexmk", ".pyc"}
            or path.name.endswith(".synctex.gz") or "__pycache__" in path.parts)


def run_json(script: str) -> dict:
    output = subprocess.check_output([sys.executable, "-B", str(ROOT / "code" / script)], text=True)
    try:
        return json.loads(output.strip().splitlines()[-1])
    except (IndexError, json.JSONDecodeError) as exc:
        raise AssertionError(f"{script} did not emit a final JSON result: {output!r}") from exc


def main() -> None:
    evidence = json.loads(EVIDENCE.read_text())
    assert evidence["candidate_id"] == "HCS-C220"
    assert evidence["source_commit"] == SOURCE_COMMIT
    assert evidence["fixed_epoch"] == FIXED_EPOCH
    assert evidence["evaluator"]["sha256"] == EVALUATOR_SHA256
    assert evidence["scope_literal"] == SCOPE
    assert evidence["payload_sha256"] == payload_hash(evidence)
    assert evidence["route_a"]["tuple"] == ["A0_FAIL", "A1_FAIL", "A2_FAIL", "A3_FAIL", "A4_FORMAL_HINT"]
    assert evidence["route_a"]["overall"] == "ROUTE_A_REJECTED"
    assert evidence["route_a"]["route_b_invocation_allowed"] is False
    assert all(value is False for value in evidence["scope_flags"].values())
    assert evidence["summary"]["phase_row_count"] == 7
    assert "affine dimension L" in evidence["theorem"]["zero_faces"]
    assert any(row["phase_id"] == "CRIT_CORNER" and row["condition"] == "alpha=beta=1/2"
               and row["boundary_note"] == "multicritical/phase-boundary junction with finite-size critical corrections"
               for row in evidence["regression"]["phase_rows"])
    assert any(row["phase_id"] == "COEXISTENCE" and row["condition"] == "0<alpha=beta<1/2"
               for row in evidence["regression"]["phase_rows"])

    evaluation_text = EVALUATION.read_text()
    for literal in (
        "candidate_id: HCS-C220", f"source_commit: {SOURCE_COMMIT}", f"code_commit: {SOURCE_COMMIT}",
        f"scope_literal: {SCOPE}", f"evaluator_authority_sha256: {EVALUATOR_SHA256}",
        "overall_verdict: ROUTE_A_REJECTED", "route_b_invocation_allowed: false",
    ):
        assert literal in evaluation_text, literal

    physical = {str(path.relative_to(ROOT)): path for path in ROOT.rglob("*") if path.is_file()}
    bad = [name for name, path in physical.items() if sidecar(path)]
    assert not bad, f"build sidecar present: {bad}"
    files = {name: digest(path) for name, path in sorted(physical.items()) if path != MANIFEST}
    assert set(files) == EXPECTED, (
        f"payload mismatch missing={sorted(EXPECTED - set(files))} "
        f"extra={sorted(set(files) - EXPECTED)}"
    )

    rounds = [ROOT / "paper/main_round0_original.pdf", ROOT / "paper/main_round1.pdf", ROOT / "paper/main_round2.pdf"]
    round_hashes = [digest(path) for path in rounds]
    assert len(set(round_hashes)) == 3, "revision PDFs must differ"
    assert digest(PDF) == round_hashes[2], "main.pdf must equal round 2"
    info = subprocess.check_output(["pdfinfo", str(PDF)], text=True)
    pages = int(next(line.split(":", 1)[1] for line in info.splitlines() if line.startswith("Pages:")))
    assert 2 <= pages <= 6, pages
    fonts = subprocess.check_output(["pdffonts", str(PDF)], text=True).splitlines()[2:]
    assert fonts and all(line.split()[-5:-3] == ["yes", "yes"] for line in fonts), "fonts not embedded/subset"
    extracted = subprocess.check_output(["pdftotext", str(PDF), "-"], text=True)
    for phrase in ["TASEP", "matrix", "current", "phase", "ROUTE_A_REJECTED", SCOPE, "Derrida"]:
        assert phrase.lower() in extracted.lower(), phrase

    producer = run_json("c220_tasep_producer.py")
    checker = run_json("c220_tasep_checker.py")
    sympy = run_json("c220_tasep_sympy_crosscheck.py")
    replay = run_json("c220_tasep_replay.py")
    mutation = run_json("c220_tasep_mutation.py")
    assert producer["status"] == "C220_PRODUCER_PASS"
    assert checker["status"] == "C220_CHECKER_PASS" and checker["producer_imported"] is False
    assert sympy["status"] == "C220_SYMPY_PASS"
    assert replay["status"] == "C220_REPLAY_PASS"
    assert mutation["status"] == "C220_MUTATION_PASS"

    # The compile and test reports are payload files, so their source-level
    # statements are checked before hashes are sealed.
    compile_text = (ROOT / "paper/COMPILE_REPORT.md").read_text()
    test_text = (ROOT / "results/TEST_REPORT.md").read_text()
    for literal in (round_hashes[0], round_hashes[1], round_hashes[2], "no `Warning`", "18 embedded"):
        assert literal in compile_text, literal
    for literal in ("3597 assertions", "576 checks", "29 total", "27 payload files", "0<alpha=beta<1/2"):
        assert literal in test_text, literal

    result = {
        "schema": "hcs-c220-release-v1",
        "status": "RELEASE_COMPLETE",
        "candidate_id": "HCS-C220",
        "evaluation_date": "2026-08-28",
        "source_commit": SOURCE_COMMIT,
        "scope_literal": SCOPE,
        "headline": evidence["headline"],
        "build_contract": {
            "engine": "LuaLaTeX", "fixed_epoch": FIXED_EPOCH, "passes_per_round": 2,
            "round_artifacts": ["paper/main_round0_original.pdf", "paper/main_round1.pdf", "paper/main_round2.pdf"],
            "final_equals": "paper/main_round2.pdf",
        },
        "gates": {
            "G0_source_scope_evaluator_lock": "PASS",
            "G1_finite_generator_unique_stationary": "PASS",
            "G2_DEHP_closed_normalization_current_boundaries": "PASS",
            "G3_checker_sympy_replay_mutation": "PASS",
            "G4_two_substantive_revisions": "PASS",
            "G5_fixed_epoch_pdf_fonts_text_visual": "PASS",
            "G6_manifest_hash_closure": "PASS",
            "G7_target_operator_and_route_b": "NOT_CLAIMED",
        },
        "results": {
            "interior_rows": len(evidence["regression"]["interior_rows"]),
            "boundary_rows": len(evidence["regression"]["boundary_rows"]),
            "total_interior_states": evidence["summary"]["total_interior_states"],
            "max_L": evidence["summary"]["max_L"],
            "checker_assertions": checker["assertions"],
            "sympy_checks": sympy["checks"],
            "word_algebra_checks": sympy["word_algebra_checks"],
            "replay_bytes": replay["bytes"],
            "hostile_rejections": mutation["total_rejections"],
            "repaired_hash_rejections": mutation["repaired_hash_rejections"],
            "stale_hash_rejections": mutation["stale_hash_rejections"],
            "pdf_pages": pages,
            "embedded_subset_fonts": len(fonts),
            "evidence_bytes": EVIDENCE.stat().st_size,
            "evidence_payload_sha256": evidence["payload_sha256"],
            "evidence_sha256": digest(EVIDENCE),
            "pdf_sha256": digest(PDF),
            "round_pdf_sha256": round_hashes,
        },
        "route_a_verdict": evidence["route_a"],
        "nonclaims": evidence["nonclaims"],
        "excluded_from_manifest": ["C220_RELEASE_MANIFEST.json", "code/__pycache__/", "*.pyc", "paper build sidecars"],
        "files": files,
    }
    assert len(files) == 27
    MANIFEST.write_text(json.dumps(result, sort_keys=True, indent=2, ensure_ascii=False) + "\n")
    physical_after = [path for path in ROOT.rglob("*") if path.is_file()]
    assert len(physical_after) == 28, f"physical file count {len(physical_after)}"
    print(json.dumps({
        "status": "C220_MANIFEST_PASS", "payload_file_count": len(files),
        "physical_file_count": len(physical_after), "manifest_sha256": digest(MANIFEST),
        "evidence_sha256": digest(EVIDENCE), "pdf_sha256": digest(PDF),
    }, sort_keys=True))


if __name__ == "__main__":
    main()
