#!/usr/bin/env python3
"""Generate result-dependent LaTeX includes after the independent audit."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
FIGURE_DIR = PROJECT_ROOT / "paper" / "figures"
DEPENDENCY_LOCK = PROJECT_ROOT / "refine-logs" / "INHERITED_DEPENDENCIES.json"
ARTIFACTS = (
    ("frozen protocol", PROJECT_ROOT / "refine-logs" / "R000_FROZEN_PROTOCOL.json"),
    ("period-20 catalogue", PROJECT_ROOT / "results" / "catalog_robustness.json"),
    ("period-20 roots", PROJECT_ROOT / "results" / "roots_robustness.json"),
    ("controls", PROJECT_ROOT / "results" / "controls.json"),
    ("analysis summary", PROJECT_ROOT / "results" / "analysis_summary.json"),
    ("independent check", PROJECT_ROOT / "results" / "independent_check.json"),
)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def write_hash_rows() -> None:
    rows = [
        "% Generated by code/make_paper_includes.py; do not edit by hand.",
        r"\begin{table}[ht]",
        r"\centering",
        r"\caption{Deterministic primary source locks, generated after the independent audit.}",
        r"\label{tab:hashes}",
        r"\begin{tabular}{ll}",
        r"\toprule",
        r"artifact&abbreviated SHA-256\\",
        r"\midrule",
    ]
    for label, path in ARTIFACTS:
        digest = sha256(path)
        rows.append(f"{label}&\\texttt{{{digest[:8]}...{digest[-5:]}}}\\\\")
    rows.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}"])
    (FIGURE_DIR / "artifact_hashes.tex").write_text(
        "\n".join(rows) + "\n", encoding="utf-8"
    )


def tex_scientific(value: float) -> str:
    mantissa, exponent = f"{value:.1e}".split("e")
    return rf"{mantissa}\times10^{{{int(exponent)}}}"


def write_dependency_list() -> None:
    payload = json.loads(DEPENDENCY_LOCK.read_text(encoding="utf-8"))
    rows = [
        "% Generated by code/make_paper_includes.py from the inherited dependency lock.",
        r"\begingroup\small\raggedright",
        r"\begin{itemize}",
    ]
    for dependency in payload["dependencies"]:
        rows.extend(
            [
                rf"\item \path{{{dependency['path']}}}\\",
                rf"role: {dependency['role']};\\",
                rf"full SHA-256: \path{{{dependency['sha256']}}}.",
            ]
        )
    rows.extend([r"\end{itemize}", r"\endgroup"])
    (FIGURE_DIR / "inherited_dependencies.tex").write_text(
        "\n".join(rows) + "\n", encoding="utf-8"
    )


def write_figure_include() -> None:
    summary = json.loads(
        (PROJECT_ROOT / "results" / "analysis_summary.json").read_text(
            encoding="utf-8"
        )
    )
    valid = {
        row["control"]: float(row["tail_ratio_vs_henon"])
        for row in summary["control_rows"]
        if row["control"]
        in {"positive_random_weights", "random_phases", "same_density_random_lengths"}
    }
    lower = min(valid.values())
    upper = max(valid.values())
    content = rf"""% Generated by code/make_paper_includes.py from results/analysis_summary.json.
\begin{{figure}}[t]
  \centering
  \includegraphics[width=\textwidth]{{figures/figure1_stability_controls.pdf}}
  \caption{{Finite-section stability is structural evidence, not arithmetic
  evidence.  (a) The untwisted positive real root approaches its displayed
  cutoff-20 value rapidly; the cutoff-20 point is plotted at a numerical floor
  because it defines the displayed reference, not because a limiting zero has
  been certified.  (b) Valid randomized orbit controls have degree-9--16
  coefficient tails between \({tex_scientific(lower)}\) and
  \({tex_scientific(upper)}\) times the
  H\'enon tail.  The exact constant-roof parent is smaller still.  No fitted
  curve or external arithmetic target is used.}}
  \label{{fig:stability-controls}}
\end{{figure}}
"""
    (FIGURE_DIR / "latex_includes.tex").write_text(content, encoding="utf-8")


def main() -> None:
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    write_hash_rows()
    write_dependency_list()
    write_figure_include()
    print(FIGURE_DIR / "artifact_hashes.tex")
    print(FIGURE_DIR / "inherited_dependencies.tex")
    print(FIGURE_DIR / "latex_includes.tex")


if __name__ == "__main__":
    main()
