from __future__ import annotations

import hashlib
import subprocess
import sys
from pathlib import Path


FIG_DIR = Path(__file__).resolve().parent
SCRIPTS = [
    "gen_fig1_theorem_certificate.py",
    "gen_fig2_exact_audit_controls.py",
    "gen_fig3_symplectic_bridge_scope.py",
]

FIGURES = [
    "fig1_theorem_certificate",
    "fig2_exact_audit_controls",
    "fig3_symplectic_scope",
]


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def write_latex_includes() -> None:
    snippets = r"""
% Auto-generated by paper/figures/generate_all.py

\begin{figure}[t]
    \centering
    \includegraphics[width=\linewidth]{figures/fig1_theorem_certificate.pdf}
    \caption{Three-panel theorem certificate: the all-period divisibility chain, the rational target gates, and the regular zero-section cotangent scope. The rational raw-prime target is closed by theorem, odd exponent-prime bases are excluded, rational $p=2$ at periods $n\ge 2$ remains open, and the cotangent bridge is displayed only on the regular locus.}
    \label{fig:theorem-certificate}
\end{figure}

\begin{figure}[t]
    \centering
    \includegraphics[width=\linewidth]{figures/fig2_exact_audit_controls.pdf}
    \caption{Exact low-period audit and matched controls. Left: the frozen candidate audit through periods $1\le n\le 4$, with exact degree equal to formal degree and no rational roots in every audited period. Right: controls that recover the $2^n$ clock, the Chebyshev fixed-point residue, the odd raw prime $3$ when the algebraic-integer assumption is violated, and the full removal of the formal period-two contamination for $z^2-3/4$.}
    \label{fig:exact-audit-controls}
\end{figure}

\begin{figure}[t]
    \centering
    \includegraphics[width=\linewidth]{figures/fig3_symplectic_scope.pdf}
    \caption{Scope of the cotangent bridge certified by the frozen bridge audit. The map is exact symplectic on the two regular branches $q<0$ and $q>0$, carries reciprocal return eigenvalues $(\lambda,\lambda^{-1})$ on zero-section periodic orbits avoiding $q=0$, and fails to globalize because of the critical singularity, overlapping branch images, and noncompactness.}
    \label{fig:symplectic-scope}
\end{figure}
""".strip() + "\n"
    (FIG_DIR / "latex_includes.tex").write_text(snippets, encoding="utf-8")


def main() -> None:
    for script in SCRIPTS:
        subprocess.run([sys.executable, script], cwd=FIG_DIR, check=True)
    write_latex_includes()
    for stem in FIGURES:
        for suffix in (".pdf", ".png"):
            path = FIG_DIR / f"{stem}{suffix}"
            if not path.exists() or path.stat().st_size == 0:
                raise RuntimeError(f"missing generated output: {path}")
    latex_path = FIG_DIR / "latex_includes.tex"
    if not latex_path.exists() or latex_path.stat().st_size == 0:
        raise RuntimeError("latex_includes.tex was not generated")

    manifest_lines = ["Generated figure hashes:"]
    for stem in FIGURES:
        for suffix in (".pdf", ".png"):
            path = FIG_DIR / f"{stem}{suffix}"
            manifest_lines.append(f"{path.name}  {sha256(path)}")
    manifest_lines.append(f"latex_includes.tex  {sha256(latex_path)}")
    print("\n".join(manifest_lines))


if __name__ == "__main__":
    main()
