#!/usr/bin/env python3
"""Exact, dependency-free verification for first-occurrence Stirling promotion.

The exhaustive pass is intentionally independent of the tree proof in the
certificate.  Stirling permutations are generated by adjacent insertion of
the new maximum pair; the map itself is evaluated literally on words.

Default scope is n=0,...,8 (2,027,025 states at the terminal rank).  Use
``--max-n 7`` for a quick replay.
"""

from __future__ import annotations

import argparse
from collections import Counter
from math import factorial


ASSERTIONS = 0


def check(condition: bool, label: str) -> None:
    global ASSERTIONS
    ASSERTIONS += 1
    if not condition:
        raise AssertionError(label)


def odd_double_factorial(n: int) -> int:
    """Return (2n-1)!!, with (-1)!!=1 at n=0."""
    answer = 1
    for value in range(1, 2 * n, 2):
        answer *= value
    return answer


def stirling_permutations(n: int):
    """Yield every order-n Stirling permutation exactly once."""
    if n == 0:
        yield ()
        return
    pair = (n, n)
    for smaller in stirling_permutations(n - 1):
        for gap in range(len(smaller) + 1):
            yield smaller[:gap] + pair + smaller[gap:]


def is_stirling(word: tuple[int, ...]) -> bool:
    n = len(word) // 2
    if len(word) != 2 * n or Counter(word) != Counter({j: 2 for j in range(1, n + 1)}):
        return False
    for j in range(1, n + 1):
        left = word.index(j)
        right = word.index(j, left + 1)
        if any(value <= j for value in word[left + 1 : right]):
            return False
    return True


def fosp(word: tuple[int, ...]) -> tuple[int, ...]:
    """The frozen literal map, with empty and order-one conventions included."""
    n = len(word) // 2
    if n <= 1:
        return word
    first_one = word.index(1)
    reduced = tuple(value - 1 for value in word if value != 1)
    return reduced[:first_one] + (n, n) + reduced[first_one:]


def internal_labels(word: tuple[int, ...]) -> tuple[int, ...]:
    """Labels whose two copies are nonadjacent (nonleaves in the tree model)."""
    result = []
    for label in range(1, len(word) // 2 + 1):
        left = word.index(label)
        if word[left + 1] != label:
            result.append(label)
    return tuple(result)


def depth(word: tuple[int, ...]) -> int:
    labels = internal_labels(word)
    return max(labels, default=0)


def root_children(word: tuple[int, ...]) -> tuple[int, ...]:
    """Recover the ordered root-child labels from the contour word."""
    opened = set()
    stack: list[int] = []
    children: list[int] = []
    for value in word:
        if value not in opened:
            if not stack:
                children.append(value)
            opened.add(value)
            stack.append(value)
        else:
            check(bool(stack) and stack[-1] == value, "properly nested pair intervals")
            stack.pop()
    check(not stack, "closed pair intervals")
    return tuple(children)


def target_fibre_formula(target: tuple[int, ...]) -> int:
    """Every-target one-step fibre formula."""
    n = len(target) // 2
    if n == 0:
        return 1
    children = root_children(target)
    if n not in children:
        return 0
    return len(children) - children.index(n)


def is_max_fibre_target(target: tuple[int, ...]) -> bool:
    n = len(target) // 2
    if n == 0:
        return True
    children = root_children(target)
    return len(children) == n and children[0] == n


def cdf_formula(n: int, t: int) -> int:
    """Number of states of depth at most t; the t=-1 convention is zero."""
    if t < 0:
        return 0
    if n == 0:
        return 1
    if t >= n - 1:
        return odd_double_factorial(n)
    return factorial(n + t) // (2**t * factorial(t))


def image_formula(n: int) -> int:
    return 1 if n == 0 else 2 ** (n - 1) * factorial(n - 1)


def iterate(state: tuple[int, ...], times: int) -> tuple[int, ...]:
    for _ in range(times):
        state = fosp(state)
    return state


def verify_rank(n: int) -> dict[str, object]:
    fibres: Counter[tuple[int, ...]] = Counter()
    depth_hist: Counter[int] = Counter()
    states = 0
    recurrent = 0
    fixed = 0

    # Forward/lifetime pass.  This uses only the literal word map.
    for word in stirling_permutations(n):
        states += 1
        check(is_stirling(word), "generated carrier word is Stirling")
        target = fosp(word)
        check(is_stirling(target), "FOSP is a self-map")
        fibres[target] += 1

        tau = depth(word)
        target_tau = depth(target)
        check(target_tau == max(tau - 1, 0), "pointwise depth decrement")
        depth_hist[tau] += 1
        if tau == 0:
            recurrent += 1
            period = 1 if n <= 1 else n
            check(iterate(word, period) == word, "star orbit closes at advertised period")
            for earlier in range(1, period):
                check(iterate(word, earlier) != word, "star orbit has exact period")
        if target == word:
            fixed += 1

    check(states == odd_double_factorial(n), "carrier double-factorial count")
    check(len(fibres) == image_formula(n), "one-step image closed form")
    check(recurrent == factorial(n), "ordered-star recurrent count")
    check(max(depth_hist, default=0) == max(0, n - 1), "sharp maximum tail")

    # The CDF and its difference are checked separately to guard against the
    # common mistake of calling a cumulative value an exact-depth count.
    cumulative = 0
    for t in range(0, max(0, n - 1) + 1):
        exact = depth_hist[t]
        predicted_exact = cdf_formula(n, t) - cdf_formula(n, t - 1)
        check(exact == predicted_exact, "exact-depth difference formula")
        cumulative += exact
        check(cumulative == cdf_formula(n, t), "depth CDF formula")

    # Independent inverse pass over every labelled target, including empty
    # fibres.  It also characterizes every maximizer, not only its value.
    expected_max = 1 if n == 0 else n
    maximizers = 0
    for target in stirling_permutations(n):
        observed = fibres.get(target, 0)
        predicted = target_fibre_formula(target)
        check(observed == predicted, "every-target fibre atlas")
        check((observed > 0) == (n == 0 or n in root_children(target)), "image criterion")
        check((observed == expected_max) == is_max_fibre_target(target), "all fibre maximizers")
        maximizers += observed == expected_max

    check(max(fibres.values()) == expected_max, "sharp fibre maximum")
    expected_maximizers = 1 if n == 0 else factorial(n - 1)
    check(maximizers == expected_maximizers, "max-fibre target census")

    expected_period = 1 if n <= 1 else n
    expected_cycles = factorial(n) // expected_period
    expected_fixed = 1 if n <= 1 else 0
    check(fixed == expected_fixed, "fixed-point boundary")

    return {
        "n": n,
        "states": states,
        "image": len(fibres),
        "recurrent": recurrent,
        "tail": max(depth_hist, default=0),
        "period": expected_period,
        "cycles": expected_cycles,
        "fixed": fixed,
        "max_fibre": max(fibres.values()),
        "max_targets": maximizers,
        "depth_hist": tuple(depth_hist[t] for t in range(max(depth_hist, default=0) + 1)),
    }


def verify_root_degree_recurrence(max_n: int) -> None:
    """Symbolically verify the catalytic recurrence behind the image count.

    A polynomial is stored coefficient-first.  R_m(z) sums z^(d_root+1)
    over increasing plane trees with m nonroot vertices.
    """
    polynomial = [0, 1]  # R_0(z)=z
    check(sum(polynomial) == 1, "root polynomial base total")
    for m in range(max_n):
        derivative = [index * coefficient for index, coefficient in enumerate(polynomial)][1:]
        next_polynomial = [0] * (len(polynomial) + 1)
        # (2m+1)R_m
        for exponent, coefficient in enumerate(polynomial):
            next_polynomial[exponent] += (2 * m + 1) * coefficient
        # z(z-1)R'_m = z^2 R'_m - z R'_m
        for exponent, coefficient in enumerate(derivative):
            next_polynomial[exponent + 2] += coefficient
            next_polynomial[exponent + 1] -= coefficient
        polynomial = next_polynomial
        check(all(coefficient >= 0 for coefficient in polynomial), "root polynomial nonnegative")
        check(sum(polynomial) == odd_double_factorial(m + 1), "root polynomial tree total")
        derivative_at_one = sum(i * c for i, c in enumerate(polynomial))
        check(derivative_at_one == 2 ** (m + 1) * factorial(m + 1), "root-gap derivative")


def format_row(stats: dict[str, object]) -> str:
    return (
        "n={n} states={states} image={image} recurrent={recurrent} "
        "tail={tail} period={period} cycles={cycles} fixed={fixed} "
        "max_fibre={max_fibre} max_targets={max_targets} depth={depth_hist}"
    ).format(**stats)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--max-n", type=int, default=8)
    args = parser.parse_args()
    if not 0 <= args.max_n <= 8:
        raise SystemExit("this exact certificate supports 0 <= --max-n <= 8")

    verify_root_degree_recurrence(args.max_n)
    rows = [verify_rank(n) for n in range(args.max_n + 1)]

    print("map=FOSP_first_occurrence_Stirling_promotion")
    print("status=PROMOTE_SPIKE_OWNER_AMBER_HOLD_EXTERNAL")
    print("literal=delete_1_pair_decrement_insert_nn_at_first_1_gap")
    for row in rows:
        print(format_row(row))
    print("image_formula=n0:1;n>=1:2^(n-1)(n-1)!")
    print("cdf_formula=n0:1;n>=1:(n+t)!/(2^t*t!),0<=t<=n-1")
    print("exact_depth=CDF(t)-CDF(t-1),CDF(-1)=0")
    print("fibre=0_unless_n_root_leaf_else_1+#root_children_after_n")
    print("max_targets=n0:empty;n>=1:ordered_stars_with_n_first")
    print(f"assertions={ASSERTIONS}")


if __name__ == "__main__":
    main()
